### ISSUE TITLE
How to construct

### ISSUE THREAD

**Issue by quetim** [codetheweb/tuyapi#10]
Hello @codetheweb,

Thank you for your awesome code. Im a completely noob (I'm a humble MD student trying to make my home smart on a budget) and I'm having a hard time figuring out how to use all the information here to get my outlet to work with Homebridge. For example, I'm able to get all the parameters

>   ip: 'xxx.yyy.0.zzz', (The IP on the tuya server and the local IP on my router)
  id: 'xxxxxxxxxxxxxxxxxxxx',
  uid: 'xxxxxxxxxxxxxxxxxxxx',
  key: 'xxxxxxxxxxxxxxxx'});

but I have no Idea what to do with them, what file I have to create (if any) or in which file do I have to put them to make it work. Could you please direct me on the right track, or provide me with some links to read and learn how I can make it work?

I would really appreciate any help, and sorry for any inconvenience.

**Comment by jepsonrob** [comment]
It looks like @codetheweb has a [Homebridge Plugin repo](https://github.com/codetheweb/homebridge-tuya-outlet), so that might point you in the right direction!

**Comment by quetim** [comment]
Thank you @jepsonrob for the information. So that means that I only have to configure things in the Homebridge config and that’s it?

Thanks again!

**Comment by codetheweb** [comment]
Yep, just setup Homebridge according to the instructions in [their repo](https://github.com/nfarina/homebridge), install my [Homebridge plugin](https://www.npmjs.com/package/homebridge-tuya-outlet), put the needed configuration parameters in your Homebridge configuration, and you should be good to go.

**Comment by quetim** [comment]
Thank you. Made it appear on homebridge, now dealing with the `{ Error: read ECONNRESET` (reading [this post](https://github.com/codetheweb/homebridge-tuya-outlet/issues/1)) but I'm progressing little by little.
Thanks again.

**Comment by codetheweb** [comment]
Not sure if you already did this, but make sure nothing else is also trying to connect to your device.  I.E. turn off your phone and see if it works.  ECONNRESET is usually due to two different TCP connections being opened simultaneously with a device.
