### ISSUE TITLE
No devices listed tuya-cli list-app

### ISSUE THREAD

**Issue by kurokiji** [codetheweb/tuyapi#107]
HI!

Just waiting for response after 
"tuya-cli list-app"
No list shows :(

**Comment by codetheweb** [comment]
Have you both trusted and installed the certificate on your phone, as well as correctly set up the proxy?

If everything is set up right, you should be able to browse the internet normally.

Do you have an Android or iPhone?

**Comment by kurokiji** [comment]
Hi, thanks for response! 

Im using iPhone, let me show you.

This is the only error it gives me.

`/homebridge # npm i @tuyapi/cli -g
npm WARN deprecated clipboard-js@0.3.6: Please migrate to https://github.com/lgarron/clipboard-polyfill
/usr/local/bin/tuya-cli -> /usr/local/lib/node_modules/@tuyapi/cli/cli.js
npm WARN svg-inline-react@1.0.3 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.`

The profile is perfectly installed and verified. The proxy is configured on the port that Homebridge it's giving to me.

**Comment by codetheweb** [comment]
That warning is fine.

Are you using the port that's printed when you start Homebridge (`homebridge`), or when you start the CLI tool (`tuya-cli list-app`)?  If everything is set to default, the port should be 8001.

**Comment by kurokiji** [comment]
I'm using "Set your HTTP proxy IP to 192.168.31.50 with port 8001" this config to iPhone proxy.

When I pull down on Tuya App, it shows me a no internet connection alert. But "waiting for request" is still there :(

**Comment by djraw** [comment]
Hi there, I got the same issue, but I know my proxy is set up correctly as I am able to open other websites.
I'm using the SmartLife app, so maybe there is an issue with the user-agent. I attached a screenshot of the AnyProxy web interface, maybe that helps narrowing down the issue.
![2018-11-12 10-24-38_anyproxy](https://user-images.githubusercontent.com/10433914/48338621-6cba4700-e666-11e8-84d4-1f0407947d39.png)

**Comment by djraw** [comment]
@codetheweb you are right, no https connection works, just http.
I  did this again (just using sudo to rule out permission issues):
# sudo anyproxy-ca
# sudo tuya-cli list-app
Deleted the old and added the new cert to my iPhone profiles, it shows as "Überprüft" (german for "verified") with a green tick. Honestly it seems to me that everything is set up correctly.

**Comment by codetheweb** [comment]
Trusting it is a different step than installing it.  Settings -> General -> About -> Certificate Trust Settings should look something like this:
![unadjustednonraw_thumb_2fe](https://user-images.githubusercontent.com/7410405/48365144-f804fe00-e6a1-11e8-92d4-4179560a9089.jpg)

**Comment by djraw** [comment]
Oh man, you already have that step in the instructions, I just overlooked it.
I need to RTFM better. ;)

**Comment by codetheweb** [comment]
No problem, glad you got it working @djraw.

**Comment by TRColT** [comment]
Hi!
Not sure if I need to start a new issue. 
I get this error after the QR code. When I pull down in the Tuya app, it does nothing.


```
Set your HTTP proxy IP to 192.168.0.112 with port 8001.
⠋ Waiting for request...error happened in proxy websocket: { Error: listen EADDRINUSE :::8001
    at Server.setupListenHandle [as _listen2] (net.js:1345:14)
    at listenInCluster (net.js:1386:12)
    at Server.listen (net.js:1474:7)
    at async.series.tipText (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/anyproxy/proxy.js:205:32)
    at /usr/local/lib/node_modules/@tuyapi/cli/node_modules/async/lib/async.js:607:21
    at /usr/local/lib/node_modules/@tuyapi/cli/node_modules/async/lib/async.js:246:17
    at iterate (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/async/lib/async.js:146:13)
    at /usr/local/lib/node_modules/@tuyapi/cli/node_modules/async/lib/async.js:157:25
    at /usr/local/lib/node_modules/@tuyapi/cli/node_modules/async/lib/async.js:248:21
    at /usr/local/lib/node_modules/@tuyapi/cli/node_modules/async/lib/async.js:612:34
    at /usr/local/lib/node_modules/@tuyapi/cli/node_modules/anyproxy/proxy.js:200:11
    at /usr/local/lib/node_modules/@tuyapi/cli/node_modules/async/lib/async.js:607:21
    at /usr/local/lib/node_modules/@tuyapi/cli/node_modules/async/lib/async.js:246:17
    at iterate (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/async/lib/async.js:146:13)
    at /usr/local/lib/node_modules/@tuyapi/cli/node_modules/async/lib/async.js:157:25
    at /usr/local/lib/node_modules/@tuyapi/cli/node_modules/async/lib/async.js:248:21
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 8001 }
Waiting for request...
```

`pi@raspberrypi:~ $  sudo netstat -plnt | grep ':8001'
tcp6       0      0 :::8001                 :::*                    LISTEN      2056/node
`

I'm totally new to this, so I might miss something really simple.
Thanks

**Comment by codetheweb** [comment]
AnyProxy is somewhat unstable in its current state, I would just try a few more times and see if it works.

It looks like there might be a second process running as well that's listening on the same port.  You could try restarting your Pi or setting the `-p` argument to something other than the default port (8001).

**Comment by TRColT** [comment]
I restarted the Pi and after few more attempts, I got it to list the devices.

Thanks,

**Comment by codetheweb** [comment]
👍
