### ISSUE TITLE
tuya-cli list-app does not print out a QR-Code

### ISSUE THREAD

**Issue by carsten-h** [codetheweb/tuyapi#108]
I did all the things mentioned on https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md

This is what I got:

> sudo npm i @tuyapi/cli -g
npm WARN deprecated clipboard-js@0.3.6: Please migrate to https://github.com/lgarron/clipboard-polyfill
/usr/local/bin/tuya-cli -> /usr/local/lib/node_modules/@tuyapi/cli/cli.js
npm WARN svg-inline-react@1.0.3 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
>
>\+ @tuyapi/cli@1.4.1
added 386 packages from 353 contributors in 404.522s

> sudo npm i anyproxy -g
npm WARN deprecated clipboard-js@0.3.6: Please migrate to https://github.com/lgarron/clipboard-polyfill
/usr/local/bin/anyproxy-ca -> /usr/local/lib/node_modules/anyproxy/bin/anyproxy-ca
/usr/local/bin/anyproxy -> /usr/local/lib/node_modules/anyproxy/bin/anyproxy
npm WARN svg-inline-react@1.0.3 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
>
>\+ anyproxy@4.0.12
added 240 packages from 273 contributors in 244.663s

> sudo anyproxy-ca
detecting CA status...
AnyProxy CA does not exist.
? Would you like to generate one ? Yes
temp certs cleared
rootCA generated
PLEASE TRUST the rootCA.crt in /root/.anyproxy/certificates
The cert is generated at /root/.anyproxy/certificates. Please trust the rootCA.crt.

> sudo tuya-cli list-app
(node:2765) UnhandledPromiseRejectionWarning: RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at Object.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/brotli/build/encode.js:21:207)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/brotli/compress.js:1:76)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
(node:2765) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2765) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

There was no QR-code printed out by tuya-cli list-app. What am I doing wrong?

I have it installed on a Raspberry Pi zero W with Rasbian Strech lite.

Thank you for help!

**Comment by codetheweb** [comment]
Can you please provide the output of `node -v`?

**Comment by carsten-h** [comment]
Sure, this is:
v11.1.0

**Comment by carsten-h** [comment]
Sure, this is:
v11.1.0

**Comment by codetheweb** [comment]
Ok, so it's up to date.

The error looks like the Raspberry Pi is running out of RAM.  Are you able to try using it on Windows or macOS?

**Comment by carsten-h** [comment]
It is only a Pi zero W and I have homebridge and pi-hole running. Maybe this is too much?

**Comment by carsten-h** [comment]
I stopped pi-hole and now I get the QR-Code and the settings for the proxy. This is working. I can install the certificate in my iPhone and I can set the proxy to the given parameters (IP address of the Pi and port 8001).

If I try to reach anything on my iphone in the browser I am getting an error message, that there is no connection to this server. Also the Smartlife App is showing me a network error.
So the process is not working. I will search what can be also wrong.

**Comment by codetheweb** [comment]
Looks like AnyProxy is complaining that the root CA certificate isn't installed, which would result in the behavior you're experiencing.  Did you run `anyproxy-ca` to generate the certificate (may need to prefix that command with `sudo`)?

**Comment by carsten-h** [comment]
I wrote in one message above this:
--
sudo anyproxy-ca
detecting CA status...
AnyProxy CA does not exist.
? Would you like to generate one ? Yes
temp certs cleared
rootCA generated
PLEASE TRUST the rootCA.crt in /root/.anyproxy/certificates
The cert is generated at /root/.anyproxy/certificates. Please trust the rootCA.crt.
--

I thought that this installed the root CA certificate. I read the QR-Code it with my iPhone and installed this certificate on it.
Or do I also have to do one step more in the raspberry pi?

**Comment by codetheweb** [comment]
It looks like since you're using `sudo` to install the root certificate it's going in the root user's directory.  Try running `sudo tuya-cli list-app` and see what happens.

**Comment by carsten-h** [comment]
Yes, I am using sudo because otherwise it was not working. I also used sudo for tuya-cli.

This is the certificate I installed on my iPhone:
![img_34ffecbb9097-1](https://user-images.githubusercontent.com/44360828/48353019-a30bbc80-e68e-11e8-9ab9-288d4a36073e.jpeg)

**Comment by carsten-h** [comment]
**I did a freah install of anyproxy:**
sudo npm i anyproxy -g
npm WARN deprecated clipboard-js@0.3.6: Please migrate to https://github.com/lgarron/clipboard-polyfill
/usr/local/bin/anyproxy-ca -> /usr/local/lib/node_modules/anyproxy/bin/anyproxy-ca
/usr/local/bin/anyproxy -> /usr/local/lib/node_modules/anyproxy/bin/anyproxy
npm WARN svg-inline-react@1.0.3 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.

+ anyproxy@4.0.12
removed 3 packages and updated 2 packages in 93.064s

**Then this:**
sudo anyproxy-ca
detecting CA status...
AnyProxy CA exists, but not be trusted
? Would you like to open the folder and trust it ? Yes

**Then this:**
sudo anyproxy -i
[AnyProxy WARN][2018-11-12 15:27:43]: ROOT CA NOT INSTALLED YET
[AnyProxy Log][2018-11-12 15:27:43]: The root CA file path is: /root/.anyproxy/certificates/rootCA.crt
[AnyProxy Log][2018-11-12 15:27:59]: Http proxy started on port 8001
[AnyProxy Log][2018-11-12 15:27:59]: web interface started on port 8002
AnyProxy Log][2018-11-12 15:28:19]: received https CONNECT request www.google.de
[AnyProxy Log][2018-11-12 15:28:19]: will forward to local https server
[AnyProxy Log][2018-11-12 15:28:19]: [internal https]proxy server for www.google.de established
[AnyProxy Log][2018-11-12 15:28:19]: received https CONNECT request www.google.de
[AnyProxy Log][2018-11-12 15:28:19]: will forward to local https server
^C[AnyProxy Log][2018-11-12 15:29:16]: destorying https connection : 127.0.0.1:33499
[AnyProxy Log][2018-11-12 15:29:16]: endding https cltSocket : 127.0.0.1:33499
[AnyProxy Log][2018-11-12 15:29:16]: clearing cache file...
[AnyProxy Log][2018-11-12 15:29:16]: ==>>> clearing cache 
[AnyProxy Log][2018-11-12 15:29:16]: closing webserver...

**Then this:**
sudo npm i @tuyapi/cli -g
npm WARN deprecated clipboard-js@0.3.6: Please migrate to https://github.com/lgarron/clipboard-polyfill
/usr/local/bin/tuya-cli -> /usr/local/lib/node_modules/@tuyapi/cli/cli.js
npm WARN svg-inline-react@1.0.3 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.

+ @tuyapi/cli@1.4.1
removed 3 packages and updated 3 packages in 131.518s

The strange thing is that anyproxy is telling this: "AnyProxy CA exists, but not be trusted" and this: "AnyProxy CA exists, but not be trusted" or is this normal?

**Comment by carsten-h** [comment]
Oh my god, I saw the thing in the other thread I was missing to do.
I also didn't set the Certificate trust settings.

Now I am one step further. When I call google.de in Safari on my iPhone I am getting:
![img_f3bb350fff2b-1](https://user-images.githubusercontent.com/44360828/48373716-f4ce3a00-e6c2-11e8-8418-b4bf9196bf39.jpeg)

And the Smartlife App is still showing the same error.

**Comment by carsten-h** [comment]
Hmm, strange. I stiil get the error in the Smartlife App, but tuyapi-cli prints me out two id/key pairs.
Is it normal that the id/key pair is also printed for devices that are not online?

And also I had it five times now that the call to "tuyapi-cli list-app" is showing me only this:

![bildschirmfoto 2018-11-12 um 21 54 23](https://user-images.githubusercontent.com/44360828/48374567-8ccd2300-e6c5-11e8-807b-e6a6fc5e3573.png)


I had to kill the ssh connection as CTRL-C is not working.

**Comment by codetheweb** [comment]
@carsten-h no problem.

It will show devices that are offline because it just intercepts the Tuya cloud response which includes all devices.

You should see key/ID pairs being printed out, then an error will pop up in the app because the proxy is killed.  Sounds like it's working.

**Comment by carsten-h** [comment]
Ah, OK I see. Then this is clear.

Do you know why the tuya-cli output stops in the middle of the QR-code? Is this also a problem of too less RAM?

**Comment by codetheweb** [comment]
Not sure what you mean, are you saying that you don't see a spinner and the text "Waiting for request..." or something similar?  If so, it could be a RAM issue but I'm not sure.

**Comment by carsten-h** [comment]
Yes, the output stops at this point. There is no more reaction in this SSH session.

But today I installed homebridge-tuya and both devices worked without any problem!
Thank you for you great work and support!

One question at last: Is the plugin working completely in the local net to switch the outlets? So I can cut them off from internet?

**Comment by codetheweb** [comment]
Yes, it's completely local.  It doesn't talk with Tuya's cloud servers at all.
