### ISSUE TITLE
I get no ID/Key pairs

### ISSUE THREAD

**Issue by carsten-h** [codetheweb/tuyapi#112]
Yesterday I managed to get two ID/key pairs of my two Tuya outlets with your great help.

Today I got two new outlets and wanted to get their ID/key pairs. I used the same steps like yesterday, but I am getting nothing.
tuya-cli is waiting forever and nothing happens. When I am running anyproxy -i I see many messages going to tuyaeu.com or tuyacn.com regarding which app I am using on my iPhone. But not line is showing my old or my new ID/key pairs. Are the ID/key pairs scrambled or something like that?

I am really lost, because I did everything linke yesterday and nothing is working.

Is it of help If I am posting here the anyproxy -i output?

**Comment by codetheweb** [comment]
Yeah, posting the output of `anyproxy -i` might help.

You're running `list-app` after adding your devices, correct?

**Comment by codetheweb** [comment]
So it looks like your phone is correctly connecting to the proxy, but the proxy can't connect to the wider internet.  What kind of computer are you running `tuya-cli` on?  A Raspberry Pi?  I would suggest trying a different host computer.

**Comment by carsten-h** [comment]
Ok. What do I have to install e.g. on my Mac to get npm etc.? Is there a manual anywhere available?

**Comment by codetheweb** [comment]
NPM comes with NodeJS.

If you've never installed Node before, I highly recemend using Node with [`nvm`](https://github.com/creationix/nvm).  After you've installed NVM, just do `nvm install node` and `nvm use node` (which will install the latest version of Node and make it available).

**Comment by carsten-h** [comment]
> but the proxy can't connect to the wider internet. 

Yes, that was correct. I didn't realise that my Pi had DNS problems. After fixing that everything was working fine and I got my four ID/key pairs.
Next time I will ask a few days later...

Thank you for your time!

**Comment by codetheweb** [comment]
Glad you got it working. 👍
