### ISSUE TITLE
Tuya-cli setting brightness on dimmer switch

### ISSUE THREAD

**Issue by yurimataev** [codetheweb/tuyapi#113]
I'm trying to use tuya-cli to set brightness on a dimmer switch. I can use the cli to turn the switch on or off using:

`tuya-cli set --id XXX --key YYY --dps 1 --set true`
`tuya-cli set --id XXX --key YYY --dps 1 --set false`

When I run the following, I get the current brightness value

`tuya-cli get --id XXX --key YYY --dps 2`

If I change the brightness value using the Tuya app, this value is updated.

However, trying to set the brightness value from the cli using the following command makes no difference, even though I get "Set succeeded". The value stays the same.

`tuya-cli set --id XXX --key YYY --dps 2 --set 128`

Any ideas?

**Comment by codetheweb** [comment]
That's my bad, it [looks like](https://github.com/TuyaAPI/cli/blob/master/lib/control.js#L53) it's always trying to cast whatever you pass in to a boolean value.

I'll have to update the parsing logic.

**Comment by yurimataev** [comment]
I modified the code at the location you specified in the following way, and it now works:

`if (!isNaN(options.set)) {
	options.set = parseInt(options.set);
} else if (options.set.toLowerCase() === 'true') {
	options.set = true;
} else if (options.set.toLowerCase() === 'false') {
	options.set = false;
}`

**Comment by codetheweb** [comment]
What is the source code for the `isNaN()` function?

**Comment by yurimataev** [comment]
It's a standard Javascript function

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN

**Comment by codetheweb** [comment]
Oops, sorry.

Fixed in v1.4.2.
