### ISSUE TITLE
Problems with communication

### ISSUE THREAD

**Issue by jodibb** [codetheweb/tuyapi#115]
Hi,
In few last days I have problem with communication to my tuya oil diffuser. Few days back, everything worked fine without any issue, but now, in most cases I'm not able to connect. I'm using Raspberry with Openhabian. I have two scripts.

First one:
> const TuyAPI = require('tuyapi');
> 
> const device = new TuyAPI({
>   id: 'xxxx',
>   key: 'xxxx',
>   ip: '10.1.0.10'});
> 
> device.on('data', data => {
>   const status = data.dps['127'];
> });
> 
> device.get().then(status => {
> 	console.log('Status:', status);
> 
> 	device.set({dps: 123, set: '1'}).then(() => console.log('Diffuser High Mist'));
> 	device.set({dps: 127, set: true}).then(() => console.log('Diffuser ON'));
>     device.get().then(status => {
> 		console.log('New status:', status);
> 		return;
>     });
> });

And it gives me result:

> (node:27865) UnhandledPromiseRejectionWarning: Error: Error communicating with device. Make sure nothing else is trying to control it or connected to it.
>     at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
> (node:27865) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:27865) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Second one:

> const TuyAPI = require('tuyapi');
> 
> const device = new TuyAPI({
>   id: 'xxxxx',
>   key: 'xxxxx',
>   ip: '10.1.0.10',
>   persistentConnection: true});
> 
> device.on('connected',() => {
>   console.log('Connected to device.');
> });
> 
> device.on('disconnected',() => {
>   console.log('Disconnected from device.');
> });
> 
> device.on('data', data => {
>   console.log('Data from device:', data);
> 
>   const status = data.dps['1'];
> 
>   console.log('Current status:', status);
> 
>   device.set({set: !status}).then(result => {
>     console.log('Result of setting status:', result);
>   });
> });
> 
> device.on('error',(err) => {
>   console.log('Error: ' + err);
> });
> 
> device.connect();
> 
> // Disconnect after 10 seconds
> setTimeout(() => { device.disconnect(); }, 10000);
 

And it gives me result:

> ....
> Connected to device.
> Error: Error: Error from socket
> Disconnected from device.
> ....

Debug for first one:

> sudo DEBUG=* node scripts/oilON.js
>   TuyAPI Payload:  { gwId: 'xxxx', devId: 'xxxx' } +0ms
>   TuyAPI Send attempt 1 +49ms
>   TuyAPI Sending this data: 000055aa000000000000000a000000467b2267774964223a223037323030323035623465363264323162393964222c226465764964223a223037323030323035623465363264323162393964227d000000000000aa55 +3ms
>   TuyAPI Connect 10.1.0.10 +6ms
>   TuyAPI Error event from socket. 10.1.0.10 { Error: connect ECONNRESET 10.1.0.10:6668
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
>   errno: 'ECONNRESET',
>   code: 'ECONNRESET',
>   syscall: 'connect',
>   address: '10.1.0.10',
>   port: 6668 } +38ms
>   TuyAPI Error event from socket. +8ms
>   TuyAPI Socket closed: 10.1.0.10 +4ms
>   TuyAPI Send attempt 2 +1s
>   TuyAPI Sending this data: 000055aa000000000000000a000000467b2267774964223a223037323030323035623465363264323162393964222c226465764964223a223037323030323035623465363264323162393964227d000000000000aa55 +0ms
>   TuyAPI Connect 10.1.0.10 +1ms
>   TuyAPI Socket connected. +7ms
>   TuyAPI Error event from socket. 10.1.0.10 { Error: write EPIPE
>     at WriteWrap.afterWrite [as oncomplete] (net.js:788:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' } +7ms
>   TuyAPI Error event from socket. +1ms
>   TuyAPI Socket closed: 10.1.0.10 +1ms
>   TuyAPI Send attempt 3 +2s
>   TuyAPI Sending this data: 000055aa000000000000000a000000467b2267774964223a223037323030323035623465363264323162393964222c226465764964223a223037323030323035623465363264323162393964227d000000000000aa55 +1ms
>   TuyAPI Connect 10.1.0.10 +0ms
>   TuyAPI Socket connected. +30ms
>   TuyAPI Error event from socket. 10.1.0.10 { Error: read ECONNRESET
>     at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' } +18ms
>   TuyAPI Error event from socket. +2ms
>   TuyAPI Socket closed: 10.1.0.10 +1ms
>   TuyAPI Send attempt 4 +2s
>   TuyAPI Sending this data: 000055aa000000000000000a000000467b2267774964223a223037323030323035623465363264323162393964222c226465764964223a223037323030323035623465363264323162393964227d000000000000aa55 +1ms
>   TuyAPI Connect 10.1.0.10 +1ms
>   TuyAPI Socket connected. +5ms
>   TuyAPI Error event from socket. 10.1.0.10 { Error: read ECONNRESET
>     at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' } +2ms
>   TuyAPI Error event from socket. +1ms
>   TuyAPI Socket closed: 10.1.0.10 +1ms
>   TuyAPI Send attempt 5 +3s
>   TuyAPI Sending this data: 000055aa000000000000000a000000467b2267774964223a223037323030323035623465363264323162393964222c226465764964223a223037323030323035623465363264323162393964227d000000000000aa55 +1ms
>   TuyAPI Connect 10.1.0.10 +0ms
>   TuyAPI Socket connected. +3ms
>   TuyAPI Error event from socket. 10.1.0.10 { Error: read ECONNRESET
>     at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' } +3ms
>   TuyAPI Error event from socket. +0ms
>   TuyAPI Socket closed: 10.1.0.10 +3ms
> (node:28561) UnhandledPromiseRejectionWarning: Error: read ECONNRESET
>     at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
> (node:28561) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:28561) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 

For second one:

> $ sudo DEBUG=* node scripts/oilSTATUS.js
>   TuyAPI Connect 10.1.0.10 +0ms
>   TuyAPI Socket connected. +42ms
> Connected to device.
>   TuyAPI Payload:  { gwId: 'xxxxxx', devId: 'xxxxxx' } +10ms
>   TuyAPI Send attempt 1 +30ms
>   TuyAPI Sending this data: 000055aa000000000000000a000000467b2267774964223a223037323030323035623465363264323162393964222c226465764964223a223037323030323035623465363264323162393964227d000000000000aa55 +2ms
>   TuyAPI Error event from socket. 10.1.0.10 { Error: write EPIPE
>     at WriteWrap.afterWrite [as oncomplete] (net.js:788:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' } +10ms
> Error: Error: Error from socket
>   TuyAPI Socket closed: 10.1.0.10 +5ms
> Disconnected from device.
>   TuyAPI Connect 10.1.0.10 +1s
>   TuyAPI Socket connected. +10ms
> Connected to device.
>   TuyAPI Payload:  { gwId: 'xxxxxx', devId: 'xxxxxxx' } +1ms
>   TuyAPI Send attempt 1 +2ms
>   TuyAPI Sending this data: 000055aa000000000000000a000000467b2267774964223a223037323030323035623465363264323162393964222c226465764964223a223037323030323035623465363264323162393964227d000000000000aa55 +0ms
>   TuyAPI Error event from socket. 10.1.0.10 { Error: write EPIPE
>     at WriteWrap.afterWrite [as oncomplete] (net.js:788:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' } +3ms
> Error: Error: Error from socket
>   TuyAPI Socket closed: 10.1.0.10 +1ms
> Disconnected from device.
>   TuyAPI Connect 10.1.0.10 +1s
>   TuyAPI Socket connected. +6ms
> Connected to device.
>   TuyAPI Payload:  { gwId: 'xxxxxx', devId: 'xxxxxx' } +1ms
>   TuyAPI Send attempt 1 +1ms
>   TuyAPI Sending this data: 000055aa000000000000000a000000467b2267774964223a223037323030323035623465363264323162393964222c226465764964223a223037323030323035623465363264323162393964227d000000000000aa55 +0ms
>   TuyAPI Error event from socket. 10.1.0.10 { Error: read ECONNRESET
>     at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' } +9ms
> Error: Error: Error from socket
>   TuyAPI Socket closed: 10.1.0.10 +2ms
> Disconnected from device.
>   TuyAPI Connect 10.1.0.10 +1s
>   TuyAPI Socket connected. +3ms
> Connected to device.
>   TuyAPI Payload:  { gwId: 'xxxxxx', devId: 'xxxxxx' } +1ms
>   TuyAPI Send attempt 1 +1ms
>   TuyAPI Sending this data: 000055aa000000000000000a000000467b2267774964223a223037323030323035623465363264323162393964222c226465764964223a223037323030323035623465363264323162393964227d000000000000aa55 +1ms
>   TuyAPI Error event from socket. 10.1.0.10 { Error: read ECONNRESET
>     at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' } +4ms
> Error: Error: Error from socket
>   TuyAPI Socket closed: 10.1.0.10 +2ms
> Disconnected from device.
>   TuyAPI Connect 10.1.0.10 +1s
>   TuyAPI Socket connected. +4ms
> Connected to device.
>   TuyAPI Payload:  { gwId: 'xxxxx', devId: 'xxxxx' } +1ms
>   TuyAPI Send attempt 1 +1ms
>   TuyAPI Sending this data: 000055aa000000000000000a000000467b2267774964223a223037323030323035623465363264323162393964222c226465764964223a223037323030323035623465363264323162393964227d000000000000aa55 +1ms
>   TuyAPI Error event from socket. 10.1.0.10 { Error: read ECONNRESET
>     at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' } +6ms
> Error: Error: Error from socket
>   TuyAPI Socket closed: 10.1.0.10 +1ms
> Disconnected from device.
>   TuyAPI Connect 10.1.0.10 +1s
>   TuyAPI Socket connected. +3ms
> Connected to device.
>   TuyAPI Payload:  { gwId: 'xxxxx', devId: 'xxxxx' } +2ms
>   TuyAPI Send attempt 1 +1ms
>   TuyAPI Sending this data: 000055aa000000000000000a000000467b2267774964223a223037323030323035623465363264323162393964222c226465764964223a223037323030323035623465363264323162393964227d000000000000aa55 +0ms
>   TuyAPI Error event from socket. 10.1.0.10 { Error: write EPIPE
>     at WriteWrap.afterWrite [as oncomplete] (net.js:788:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' } +2ms
> Error: Error: Error from socket
>   TuyAPI Socket closed: 10.1.0.10 +2ms
> Disconnected from device.
>   TuyAPI Connect 10.1.0.10 +1s
>   TuyAPI Socket connected. +3ms
> Connected to device.
>   TuyAPI Payload:  { gwId: 'xxxxx', devId: 'xxxxx' } +1ms
>   TuyAPI Send attempt 1 +1ms
>   TuyAPI Sending this data: 000055aa000000000000000a000000467b2267774964223a223037323030323035623465363264323162393964222c226465764964223a223037323030323035623465363264323162393964227d000000000000aa55 +1ms
>   TuyAPI Error event from socket. 10.1.0.10 { Error: read ECONNRESET
>     at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' } +2ms
> Error: Error: Error from socket
>   TuyAPI Socket closed: 10.1.0.10 +2ms
> Disconnected from device.
> ...
> 

OpenHabian 
node v10.14.0

Thanks for any help.

**Comment by codetheweb** [comment]
Hmm.  Well, thanks for the comprehensive debugging data.

Are you absolutely sure that nothing else is trying to control your device?  Maybe there's a duplicate script process running on your Pi or something (also, make sure the app is completely closed and not running in the background on your phone).

**Comment by jodibb** [comment]
I'm not sure now. It works now after restarting both devices, but will see how long.
When it occurs again, I'll check if there are any script running.

**Comment by codetheweb** [comment]
Ok, let me know if any other issues occur.
