### ISSUE TITLE
AnyProxy - Unable to access the internet from mobile devices

### ISSUE THREAD

**Issue by abujji** [codetheweb/tuyapi#118]
Hi,

I have AnyProxy running fine on my desktop and also have the QR code being displayed. But when I capture the QR code from an iPad or Samsung Galaxy, I am unable to download the Crt file because the browser simply hangs. So, I downloaded the Root certificate on my desktop and emailed it so I could manually upload on  my mobile devices. I was able to successfully setup the certs on ipad and Galaxy. I setup the proxy for the Wifi connection with the IP address and port number displayed under the QR code. But after that I am unable to access the internet from my mobile devices and the Tuya smart app doesnt display the "key" "Value" pairs as expected. The Tuya Smart app shows no change in its behavior even after I pull down and refresh the page. Need some help here please...

**Comment by codetheweb** [comment]
Have you trusted the certificate on your devices (different step than installing it)?

If everything is set up correctly, you should be able to access HTTPS sites such as `https://github.com` with the proxy running (as you've pointed out).

**Comment by abujji** [comment]
Thank you. I have setup the proxy and also made sure the device trusted the certificate. In Samsung, when setting up the proxy it gives 2 options - VPN & Apps or WiFi. Which one should I select? My biggest issue is that once I have the proxy up and running on my desktop, I am able to use it successfully from the desktop but the mobile devices are not even able to reach the proxy dashboard at <IP Address>:8002. What am I doing incorrectly?

**Comment by codetheweb** [comment]
I'm not sure how it works on Android as I have an iPhone, but I don't think it would be the VPN option.

Are you able to reach the proxy dashboard at `<computer's ip>:8002` from your phone (make sure you don't use `localhost` for the IP)?  If not, there's an issue with your network setup.

You also may want to check if your computer can ping your phone and vice versa.

**Comment by abujji** [comment]
I am able to run a ping app from my ipad and reach my computer. I am able to RDP into my computer from my ipad using my computer's IP address. The strange thing I noticed is that AnyProxy has picked the IP address of my VMNet adapter to run the proxy server. It is not using the IP address associated with my LAN adapter. Will that be the reason?

**Comment by abujji** [comment]
I found the issue! I was using the VMNet adapter's IP address as that was what was displayed under the QR code on my desktop. Instead of that IP I used the <LAN Adapter's IP>:8002 from my mobile devices and I was able to see the dashboard and when I opened the Tuya Smart app, I was able to get the ID & Key pairs listed! Thanks for your suggestions.

**Comment by codetheweb** [comment]
Glad you figured it out. 👍
