### ISSUE TITLE
Quick question from a noob

### ISSUE THREAD

**Issue by jcklpe** [codetheweb/tuyapi#125]
I'm sorry if this is a stupid basic question but I'm a designer learning to code and so I am still a bit new.

I have some lohas bulbs. How can I check to see if they are compatible with this library? 

It mentions on the Readme that the tuy cloud products use port 6683. Do I just do an Nmap scan on my router public ip in order to check this?

**Comment by codetheweb** [comment]
No problem.

The syntax for scanning ports with Nmap is `nmap -p <ports to check, separated by commas> <local IP>`.  So something like `nmap -p 6683 192.168.x.x`.

In practice, it's probably easier to tell based on whether or not it works with the TuyaSmart app (available for iOS and Android).  I'll add something along those lines to the README.

**Comment by jcklpe** [comment]
Awesome. Thanks it does seem to work!

Only problem is that I don't think these bulbs are quite what I want even if I hack together my own customizations. The warm end of the spectrum on the white lights is not very warm. It looks to me like it's about 3000k not 2700k. That's diapoointing
:( maybe I should get a Philips hue. They're so expensive though. I want every light to be a smart light so I can have the color temperature gradually warm as it gets darker outside.

**Comment by codetheweb** [comment]
Yeah, but you can't expect much from $10 bulbs 😛.

I have noticed the same issue with my bulb, although I'm not sure if every Tuya-enabled bulb uses the same hardware.  Might be able to find higher-quality ones somewhere.
