### ISSUE TITLE
Socket is closed errors due to timing issue

### ISSUE THREAD

**Issue by unparagoned** [codetheweb/tuyapi#142]
When say toggling tuyapi sometimes shows errors writing to a socket or that it's closed. The issue was raised on another thread but it seems quite different to what that's suppose to be about so I thought I'll make another rather than hide stuff away there. Check my reply for a fix of some kind.

https://github.com/codetheweb/tuyapi/issues/103#issuecomment-462074797

### Code
```
const device = new TuyAPI({
    id: '50758014cc5xxxxxxxxx',
    key: 'xxxxxxxxxxxxxxxx',
    ip: '10.3.2.25',
    persistentConnection: false
});

device.get().then(status => {
    console.log('Curtain state is:', status);

    device.set({
        set: '3'
    }).then(result => {
        console.log("Curtain paused result:", result);
    }).catch(err => {
        console.log('Error setting status:', err);
    });

}).catch(err => {
    console.log('Error getting status:', err);
});
```
### Result
```
  TuyAPI Payload:  { gwId: '50758014cc5xxxxxxxxx', devId: '50758014cc5xxxxxxxxx' } +0ms
  TuyAPI Send attempt 1 +8ms
  TuyAPI Sending this data: 000055aa000000000000000a000000467b2267774964223a223530373538303134636335306533316137653839222c226465764964223a223530373538303134636335306533316137653839227d000000000000aa55 +0ms
  TuyAPI Connect 10.3.2.25 +2ms
  TuyAPI Socket connected. +59ms
  TuyAPI Received data back: 10.3.2.25 +6ms
  TuyAPI 000055aa000000000000000a0000003c000000007b226465764964223a223530373538303134636335306533316137653839222c22647073223a7b2231223a2233227d7d1c8960c50000aa55 +0ms
  TuyAPI Data: 10.3.2.25 { devId: '50758014cc5xxxxxxxxx', dps: { '1': '3' } } 10 +1ms
  TuyAPI Disconnect +1ms
Curtain state is: 3
  TuyAPI Payload: 10.3.2.25 +15ms
  TuyAPI { devId: '50758014cc5xxxxxxxxx',
  TuyAPI   gwId: '50758014cc5xxxxxxxxx',
  TuyAPI   uid: '',
  TuyAPI   t: '1549742021',
  TuyAPI   dps: { '1': '3' } } +0ms
  TuyAPI Send attempt 1 +4ms
  TuyAPI Sending this data: 000055aa0000000000000007000000b3332e31346431326363616165373564616431654938434a58335871474a494e354e5a62323845663333752b41324d3151677557435473687445695336507878656c435537673663555a686274384876494d6d6d514243474950577563494362585157686845553333776d3069545677684d44636742463646436c7379706b4a32756672373673556f693850384b39347432637778324235577843544972374b354d717766395a6e74513d3d000000000000aa55 +1ms
  TuyAPI Error event from socket. 10.3.2.25 Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:406:19)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Socket.Writable.write (_stream_writable.js:294:11)
    at connect.then (d:\prj\node\curtain-tuya\node_modules\tuyapi\index.js:414:21)
    at process._tickCallback (internal/process/next_tick.js:68:7) +1ms
  TuyAPI Error event from socket. +1ms
  TuyAPI Socket closed: 10.3.2.25 +0ms
  TuyAPI Send attempt 2 +1s
  TuyAPI Sending this data: 000055aa0000000000000007000000b3332e31346431326363616165373564616431654938434a58335871474a494e354e5a62323845663333752b41324d3151677557435473687445695336507878656c435537673663555a686274384876494d6d6d514243474950577563494362585157686845553333776d3069545677684d44636742463646436c7379706b4a32756672373673556f693850384b39347432637778324235577843544972374b354d717766395a6e74513d3d000000000000aa55 +1ms
  TuyAPI Connect 10.3.2.25 +0ms
  TuyAPI Socket connected. +95ms
  TuyAPI Received data back: 10.3.2.25 +12ms
  TuyAPI 000055aa00000000000000070000000c00000000789370910000aa55 +1ms
  TuyAPI undefined 10.3.2.25 undefined 7 +0ms
  TuyAPI Disconnect +0ms
Curtain paused result: true
  TuyAPI Socket closed: 10.3.2.25 +1ms
```

I get similar sorts of logs, but with closed socket error. So that does explain why toggling takes quite a bit longer than just setting or getting the state. It works but the logs show it might try a few times. I also noticed something similar when I was playing about with the code. I noticed that the promises are resolved when a command is sent, so if you have two lined up you'll start sending another command as soon as the first is done sending the command, but then there is some overlap between the first command receiving the response and the second one sending one, which may contribute to some errors. Also, I'm not sure about this but maybe when you destroy the client it takes some time to close down the socket but if the code treats the socket as being free as soon as it's destroyed it might explain why it's getting an unexpected state. I tried testing out my hunch but the Promises everywhere fired my head.

```
TuyAPI Error event from socket. 192.168.2.xx Error: This socket is closed
    at Socket._writeGeneric (net.js:733:18)
    at Socket._write (net.js:787:8)
    at doWrite (_stream_writable.js:396:12)
    at writeOrBuffer (_stream_writable.js:382:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:711:40)
    at connect.then (/etc/openhab2/scripts/node_modules/tuyapi/index.js:532:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) +1mssocket 
```

**Comment by unparagoned** [comment]
I have managed to fix the issue on my branch of the code, but I've made lots of changes there playing about and trying things out. Also I don't really understand the structure of everything so it feels like it may brake other things and isn't optimal. It might delay or cause issues by resolving at a later point and potentially cause timeout issues. So I won't make any kind of pull request. It's just a few lines of code which are all below.

I basically changed when dataResolver resolved from on data receipt to on close of the socket. It used to be on when it had received data it would issues a disconnect command and then return the promise. But it takes some time to destroy and close the socket, so the client will still be alive and be called when the client has a state of 'destroyed':true. So I changed the disconnect function to take a callback which it then adds as a callback to this.client.on('close'. So in the  _sendUnwrapped function rather than having dataResolver resolving when you get the data you pass the resolve to the disconnect function. 
I don't think that's the best way to do it but was as far as I could get. I think you probably want to resolve the data straight away and do something separate for when the socket has been closed and is free.

```
  _sendUnwrapped(buffer, expectedResponseCommandByte, returnAsEvent) {
    debug('Sending this data:', buffer.toString('hex'));
    return new Promise((resolve, reject) => {
      if (!returnAsEvent) {
        this.dataResolver = (data, commandByte) => { // Delayed resolving of promise
          if (expectedResponseCommandByte !== commandByte) {
            reject(new Error('Returned command byte did not match expected byte.'));
          }

          if (this._sendTimeout) {
            clearTimeout(this._sendTimeout);
          }

          if (!this.device.persistentConnection) {
            **this.disconnect(() => resolve(data, commandByte));** 
          }
          // resolve(data, commandByte);
          return true;
        };
...
....
  disconnect(callback) {
    debug('Disconnect');
    
    this.client.on('close', () => {
      callback();
    });
```

**Comment by codetheweb** [comment]
That makes sense, thanks for looking into this.  Hopefully it resolves some of the open issues.

I've been doing a bit of refactoring / cleaning up the code [here](https://github.com/codetheweb/tuyapi/tree/feature-cleanup); so I'll incorporate your comments into that.

**Comment by unparagoned** [comment]
It looks nice and clean, getting rid all that junk in-front of the class really helps. 

In my branch I kind of went the other way when it came to what to do when checking input. If no ip or id was passed as an option, then it would scan the network for all devices and then return the schema for all of them. It just feels quite nice to be able to do a decent amount without having to go through the hassle of getting the keys. It was just a few changes your find() function, so it just continues and saves each device response until it sees the same ids again. And then another function to gets the schema for each device, that's found. I used to have a python script that I used to find all the devices so it was nice to move get rid of that.

Also since you can get he state without needing a key, my calling script passes a fake key if the user hasn't provided one. Ideally it would only throw an error when trying to use a function that requires a key, but when I looked at it, it didn't seem that easy.

**Comment by codetheweb** [comment]
Thanks.  Still needs testing, but I think everything should work.  Emitting events *and* returning the values in a Promise makes much more sense than just one or the other.

It might make sense to add a separate function for listening to all broadcasts, but I wouldn't want to have one function do both.

Being able to get properties sounds like a cool idea, but in practice devices sometimes (rarely) return an encrypted response that needs to be decrypted with the local key.

**Comment by codetheweb** [comment]
Closing this because it should be fixed in v4, let me know if you're still seeing issues.
