### ISSUE TITLE
Provide Changelog infos, especially for 4.x

### ISSUE THREAD

**Issue by Apollon77** [codetheweb/tuyapi#145]
Hey @codetheweb,

can you describe why it is 4.x? What is breaking for a user of the 3.x version of the lib?

Thank you.

**Comment by codetheweb** [comment]
Thanks for the reminder, I just put some release notes up [here](https://github.com/codetheweb/tuyapi/releases/tag/v4.0.0).  Let me know if you think they should cover anything else.

**Comment by Apollon77** [comment]
Thank you very much!
