### ISSUE TITLE
Set with multiple parameters

### ISSUE THREAD

**Issue by jodibb** [codetheweb/tuyapi#148]
Hi,
I'm trying to optimize my script little bit and because I'm usualy changing multiple parameters at the same time, I would like to use only one Set command.

This is example what I want to use:
```
		device.set({
				  multiple: true,
				  data: {
					'132': true,
					'127': true
				 }}).then(() => console.log('device was changed'))

```
 but It doesn't work for me. There is no error message, but it doesn't change status of device.

**Debug Output**
```
  TuyAPI Payload: 10.1.0.10 +0ms
  TuyAPI { devId: '07200205b4e62d21b99d',
  TuyAPI   uid: '',
  TuyAPI   t: '1550524891',
  TuyAPI   dps: { '1': undefined } } +2ms
  TuyAPI Send attempt 1 +27ms
  TuyAPI Sending this data: 000055aa000000000000000700000087332e31613464393537393261393565643739383476444254423032765a517548547a386d43664a6263797365647937454b36386972316251704d707a69637a6467776a47324f4131416977536461797742594556747052475447524e78473742613474412b316e3646444b71485431425075796438795968684f656d76633d000000000000aa55 +1ms
  TuyAPI Connect 10.1.0.10 +2ms
  TuyAPI Socket connected. +125ms
  TuyAPI Received data back: 10.1.0.10 +122ms
  TuyAPI 000055aa00000000000000070000000c00000000789370910000aa55 +1ms
  TuyAPI undefined 10.1.0.10 undefined 7 +5ms
  TuyAPI Disconnect +2ms
device was changed
  TuyAPI Socket closed: 10.1.0.10 +7ms

```
Any idea what I'm doing wrong?
Thanks

**Comment by unparagoned** [comment]
It looks like there is some sort of issue with the format of your set argument. You should get something like this. 
```TuyAPI SET Payload: +0ms
  TuyAPI { devId: 'xxx',
  TuyAPI   gwId: 'xxx',
  TuyAPI   uid: '',
  TuyAPI   t: '1550524891',
  TuyAPI   dps: { '127': true, '132': true } } +1m
```
But it looks like it can't read the format properly.
If you are using some other script then you may need to format the command slightly differently.

In my script I get the set command from the command line so I usually have more quotes and then run it through JSON.parse first.

 ``` 
setCmd ="{ \"multiple\": true, \"data\": { \"0\": true, \"1\": true} }"
device.set(JSON.parse(setCmd))```
```

**Comment by codetheweb** [comment]
@jodibb it looks like TuyAPI just isn't recognizing the `multiple` option; you may need to update TuyAPI.  Make sure it's >= v4.0.0.

**Comment by jodibb** [comment]
Issue was with version. I was still on some 3.x.x version. Now I'm on 4.0.3 and it works. Thanks guys.

**Comment by codetheweb** [comment]
Glad you got it working.
