### ISSUE TITLE
I receive a timeout error and cant get connected

### ISSUE THREAD

**Issue by Arunbalajik** [codetheweb/tuyapi#152]
socket gets closed and device gets disconnected. 

My sample output is ....

IP and ID are already both resolved.
Connecting to ***.***.***.**
Error: connection timed out
    at Socket.client.setTimeout (C:\Users\ArunMK\Desktop\Pro\tuyapi-master\new.js:334:23)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:410:8)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
Socket closed: ***.***.***.**
Disconnected from device.

plz help me how i can solve this

**Comment by codetheweb** [comment]
Please execute `setx DEBUG *` and run your script again, then post the output.

**Comment by mitzas** [comment]
Hello,
I have followed [this](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md) tutorial. I got the key and the deviceID. I am trying to run the following code with DEBUG=* node app.js
`const TuyAPI = require('tuyapi');

const device = new TuyAPI({
  id: 'xxxxxxx',
  key: 'xxxxx'});

let stateHasChanged = false;
// Find device on network
device.find().then(() => {
  // Connect to device
  device.connect();
});

// Add event listeners
device.on('connected', () => {
  console.log('Connected to device!');
});

device.on('disconnected', () => {
  console.log('Disconnected from device.');
});

device.on('error', error => {
  console.log('Error!', error);
});

device.on('data', data => {
  console.log('Data from device:', data);

  console.log(`Boolean status of default property: ${data.dps['1']}.`);

  // Set default property to opposite
  if (!stateHasChanged) {
    device.set({set: !(data.dps['1'])});

    // Otherwise we'll be stuck in an endless
    // loop of toggling the state.
    stateHasChanged = true;
  }
});

// Disconnect after 10 seconds
setTimeout(() => { device.disconnect(); }, 10000);`

and I got

`TuyAPI Finding missing IP undefined or ID _myDeviceID_ +0ms
  TuyAPI Disconnect +10s
(node:28750) UnhandledPromiseRejectionWarning: Error: find() timed out. Is the device powered on and the ID or IP correct?
    at timeout (/home/mihaio/tuyapi/tuyapi-master/node_modules/tuyapi/index.js:614:13)
    at Timeout.setTimeout [as _onTimeout] (/home/mihaio/tuyapi/tuyapi-master/node_modules/p-timeout/index.js:19:13)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
(node:28750) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28750) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

My node version is v8.10.0.
Can you help me please? It is quite important for me and I would appreciate a lot :) 
Thank you!

**Comment by yoarch** [comment]
Hi, I get the exact same issue.
I have 2 smart outlets and a computer with arch linux. I want to control them locally from my laptop and tried the tuyapi service.
I retrieved the different info such as deviceID, local_key with a package sniffer on my smartphone tuya app.

Then I tried in my laptop terminal:
const TuyAPI = require('tuyapi');
const device = new TuyAPI({
id: 'xxxxxxx',
key: 'xxxxx'});
let stateHasChanged = false;
device.find()

and get:
(node:2401) UnhandledPromiseRejectionWarning: Error: find() timed out. Is the device powered on and the ID or IP correct?
    at timeout (XXX/node_modules/tuyapi/index.js:614:13)
    at Timeout.setTimeout [as _onTimeout] (XXX/p-timeout/index.js:19:13)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
(node:2401) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2401) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I don't know what I am doing wrong. The devices are well listening on port 6668 and working with the tuya app (they are Alexa/Google compatibles). Do I need to add a homebridge plugin? Add a certificate somewhere? Flash a firmware?

Thanks a lot for your help and time, I have been working on that for weeks and am a litle lost right now.

**Comment by kueblc** [comment]
Could you please share what the firmware version and model number of the device is?

**Comment by yoarch** [comment]
Thanks a lot for your answer. So, there are the only info I have on them:
Model: S126 Wifi Socket
One of them have for device name (giving by my modem): ESP_08XXA0
They communicate throught wifi 2.4GHz
They are Google Home / Amazon Alexa Echo compatible and made by FAGORY.
There is a photo of them:
https://www.google.com/search?q=prise+connectée+Wifi+Fagory+Google+home&source=lnms&tbm=isch&sa=X&ved=0ahUKEwipjvyypobhAhU58uAKHbZlBBAQ_AUIECgD&biw=2134&bih=1040#imgrc=I7fxSEMx0jhC9M:

Thanks for your time.

**Comment by kueblc** [comment]
You can check the device firmware version in the app, if they are still connected to it. There was a big change pushed out in firmware recently and we're assessing the damage, so information on what firmware versions are affected for which devices will be very helpful. Thanks for taking the time!

**Comment by yoarch** [comment]
Ok, I found that on the app:
Wi-Fi module:1.0.4
MCU module:1.0.4
Is it an issue with that one?

**Comment by kueblc** [comment]
We do not yet know the extent, but your information will help determine this. Thank you!

**Comment by yoarch** [comment]
Ok. Do you have any advice for me **now** regarding my situation? Flash the firmware should fix my current issue in your opinion? Or should I wait a return from you?
Thanks for your time.

**Comment by kueblc** [comment]
Do you get any output from `nc -u -l -k -p 6666 | strings`?

**Comment by yoarch** [comment]
Downloaded **gnu-netcat** on arch and tried it. *-k* is invalid in my case.
*nc -u -l -p 6666 | strings* and *nc -u -l -p 6668 | strings* have no outputs on my system.
Downloaded **openbsd-netcat** on arch and tried it too.
*nc -u -l -p 6666 | strings* and *nc -u -l -p 6668 | strings* have no outputs neither on my system.
What does that mean?
Thanks for your time.

**Comment by kueblc** [comment]
This should tell us which, if any, devices are broadcasting their existence to your network. They are broadcasted as UDP packets to port 6668. `-u` for UDP, `-l` for listen, `-k` for keep listening, `-p 6668` to set the port. `| strings` isn't strictly necessary but it cleans the output for easier viewing.

If there are devices you can control with TuyAPI, you should see a JSON object appear every few seconds, as long as the device isn't being controlled by something else. If the devices are running the new firmware, the output will be encrypted and thus you will receive ugly garbage instead of JSON.

**Comment by yoarch** [comment]
Thanks for the explanation.

I got nothing. It seems that my devices are not broadcasting any UDP packets.
When using nmap on one of my smart outlet device I get one open port:
PORT     STATE    SERVICE
6668/tcp filtered irc

So it seems that it communicates with my modem with TCP packets.

**Comment by kueblc** [comment]
Oops, I just realized your port is incorrect, it should be `6666` not `6668`

**Comment by yoarch** [comment]
Ok, that's strange. I did not configure anything and my 2 devices are in 6668/tcp filtered irc mode. I guess that is their default conf mode.

**Comment by kueblc** [comment]
I meant for detecting the broadcast UDP packets, you should be listening on 6666. So `nc -u -l -k -p 6666 | strings` not `nc -u -l -k -p 6668 | strings`. It's also worth checking to see if they are broadcasting on `6667`; `nc -u -l -k -p 6667`. Make sure to close the app if you have it so no other device is connected to it locally.

**Comment by yoarch** [comment]
hooo. You are right!
I already tried *nc -u -l -k -p 6666* and got nothing. But just tried *nc -u -l -k -p 6667* and get an UDP packet every sec. Great to make progress, thanks.
However, it's uncrypted..
So, what is next? Is it important to uncrypt them to go forward?

**Comment by kueblc** [comment]
Unfortunately this means that TuyAPI can't (yet) control your devices as they are indeed running the new firmware. I do not know for certain when or if we will be able to reverse engineer the new protocol.

If you can physically open the device you may be able to flash it with a custom firmware over serial. Otherwise we'll just have to wait and see. Sorry I don't have better news for you!

**Comment by yoarch** [comment]
I understand. So, the new firmware broadcasts uncrypted packets, right?
As kueblc said:
>If you can physically open the device you may be able to flash it with a custom firmware over serial.
So, you are saying that I won't be able to flash it with a tool such as **tuya-convert** because of the new firmware?
If it's the case I am going to try over serial. Do you have any firmware suggestion? Is it one that you will recommend for what I want to do (control them from my arch linux os)?
OMT, thanks for your time.

**Comment by kueblc** [comment]
Yes, essentially the major change is the move to encrypted communication, both locally and with the cloud. This was a glaring error in the stock firmware, so in some sense, it's good for the typical consumer, but bad for us who would like to own our devices.

Previously, a MITM attack was trivial (this is how tuya-convert and the like work, so you are correct in that you are no longer able to convert the firmware OTA).

Tuya devices operate on the ESP8266/ESP8285 and there are now plenty of options for these chips. The three most popular firmware projects that I'm familiar with are EspEasy, Sonoff-Tasmota, and Espurna.

I recommend starting with [Sonoff-Tasmota](https://github.com/arendst/Sonoff-Tasmota) as it's a "one size fits all" firmware that you can configure on the device. Once installed, it's easy to change to another firmware as Tasmota has an OTA firmware upload feature.

**Comment by yoarch** [comment]
Thanks a lot for all these informations. I am going to take the time to investigate all of that.
That would not have been possible to get at this point without your help, moreover that fast.
Thanks.

**Comment by kueblc** [comment]
You're welcome! Your help in determining the extent of the new update is also very much appreciated, so thank you. Let's hope we can crack this new firmware soon so we can retain ownership of our devices :)

**Comment by yoarch** [comment]
I tried to open it up but there is no (visible) screws and am a little confuse in front of the device. There are some photos of the devices:
https://www.gearbest.com/smart-socket-plug/pp_1696862.html
If you are used to do that, can you tell me if I have to force it or if I have to cut a piece off?

Then I will have to buy a serial adapter I guess, do you have any recommendation?
I guess most of the new connected devices are going to have a new firmware with uncryption (for security reason) and then it won't be possible to reverse them OTA. So could be good to have a good serial adapter to be able to flash any new connected device (if it's possible). Is my reasonment right?

**Comment by kueblc** [comment]
I use [this one](https://smile.amazon.com/gp/product/B072K3Z3TL/) though as long as it offers 3.3V you should be fine with any USB to TTL serial adapter. We may or may not figure out a way to flash the new firmware OTA, but I'd agree a serial adapter is a good tool to have around.

**Comment by yoarch** [comment]
That's great, thanks.
So you are positive that I should be able to flash this motherboard with an **USB to TTL Serial Converter** with a **Sonoff-Tasmota** firmware? Do you have any tuto recommendation to do it?

**Comment by kueblc** [comment]
[The Sonoff-Tasmota wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) has all the answers you're looking for :smile: I'm not permitted to make any guarantees but to the best of my knowledge you should be fine flashing any Tuya device over serial, regardless of firmware version.

**Comment by yoarch** [comment]
Hey, giving some news. I bought the adapter you adviced me, should receive it next week and figured out that my controler is a **Tuya TYWE3S**. So, should not be a problem to flash it..

**Comment by kueblc** [comment]
Great! If I can ask you to do one big favor when you get it, please backup the stock firmware and share the binary so we can better understand the new update. That would be a huge help!

**Comment by yoarch** [comment]
Copy that.
If I can I will..

**Comment by yoarch** [comment]
Hey, I am back.
So I received the DSD TECH USB to TTL Serial Converter and I read lots of documentation.
So, my controler is a Tuya TYWE3S:
![IMG_20190408_223337](https://user-images.githubusercontent.com/48605580/55756025-e5280700-5a50-11e9-9494-e6a05da00b57.jpg)

I found this doc talking about the TYWE3S wifi controler:
https://docs.tuya.com/en/hardware/WiFi-module/wifi-e3s-module.html

So, I guess now I just have to solder the Rx, Tx, 3.3V and GND to the Serial converter.
Can I do it directly on the wifi controler? There is not lot of space to do it.
Then, I have to bring the module in flash mode as explained here:
https://github.com/arendst/Sonoff-Tasmota/wiki/Hardware-Preparation

Being on linux (archlinux) I can use Esptool.py to backup the existing firmware (and give it to you) and then flash the tasmota firmware folowing this:
https://github.com/arendst/Sonoff-Tasmota/wiki/Flashing

Could you please check the different steps I said before I do it?
Thanks a lot.

**Comment by kueblc** [comment]
Looks like you've got it. The hardest part will be soldering to the TYWE3S without destroying it.

Instead of soldering, you may be able to get away with just touching the wires to the contacts. If you have spring loaded pins (pogo pins) you could try that way, get some tape or a weight, or just have two friends hold the wires in place :stuck_out_tongue:

**Comment by yoarch** [comment]
Ok, I am going to try like this.
I still have a doubt about the broches/pin configuration.
Please, look at:
* the last photo I showed above
* the broches configuration they propose in this doc: 
https://docs.tuya.com/en/hardware/WiFi-module/wifi-e3s-module.html
* and the configuration that reloxx13 proposed in the wiki (that works apparently):
https://github.com/arendst/Sonoff-Tasmota/wiki/TYWE3S

I see two different configurations (pins are inversed). I don't know if I should follow the reloxx13 conf or the tuya doc to plug the cables.
What do you think?

**Comment by yoarch** [comment]
Ok. I tried to do the connexions during 2 hours without soldering. Impossible. So, I bought a solder machine. I should have everything on friday and will do it right away.

Sorry for not being clear.
On the Tuya-TYWE3S doc:
https://docs.tuya.com/en/hardware/WiFi-module/wifi-e3s-module.html
they say that the TXD0 pin is the first one at the **left**. But reloxx13 and didi-home consider that the TXD0 pin is the first one at the **right** on the TYWE3S microcontroller motherboard..
I don't know who I should trust..

**Comment by kueblc** [comment]
You are looking at the back of the board in the Tuya document, so it'll depend on how it is oriented in your device. With the chip on top, the pinout will be mirrored.

**Comment by yoarch** [comment]
I have been trying to solder and flash it for 3 days, with no success. I figured out yesterday that the motherboard is now dead, the lamp (blue/red) doesn't even turn on when I plug it normally on the 220V. I am sorry, I won't be able to give you the firmware, I give up..
I am going to buy a new one that I can flash with the tasmota OTA.
Thanks a lot for your help.

**Comment by kueblc** [comment]
I'm sorry to hear it didn't work out for you, after all this effort. I really appreciate you trying, I have been able to receive firmware from others, so don't worry about me. Good luck!

**Comment by codetheweb** [comment]
Closing this because support for protocol version 3.3 has been merged.
