### ISSUE TITLE
npm i @tuyapi/cli -g permission denied

### ISSUE THREAD

**Issue by MachineGalaxy** [codetheweb/tuyapi#159]
**Describe the bug**
npm i @tuyapi/cli -g Permission denied (publickey) error

root@ProjectQuark:~# npm i @tuyapi/cli -g
(node:632) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm ERR! git clone git@github.com:tuyapi/cli Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-tuyapi-cli-3083bead'...
npm ERR! git clone git@github.com:tuyapi/cli Permission denied (publickey).
npm ERR! git clone git@github.com:tuyapi/cli fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:tuyapi/cli
npm ERR! git clone git@github.com:tuyapi/cli Please make sure you have the correct access rights
npm ERR! git clone git@github.com:tuyapi/cli and the repository exists.
npm ERR! addLocal Could not install tuyapi/cli
npm ERR! Error: ENOENT: no such file or directory, stat 'tuyapi/cli'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.98+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "i" "@tuyapi/cli" "-g"
npm ERR! cwd /root
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! path tuyapi/cli
npm ERR! syscall stat
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0

```

```
**Desktop (please complete the following information):**
 - OS: [e.g. Raspbian]
 - OS Version [2018-11-13]
 - Node Version [v8.11.1]

**Comment by codetheweb** [comment]
Something looks wrong with your NPM configuration as it shouldn't be cloning from Github.

See if anything looks out of place with `npm config edit`.

I'm closing this issue as it's not related to TuyAPI, but feel free to comment if you have more questions.
