### ISSUE TITLE
Input Code For Tuya Device

### ISSUE THREAD

**Issue by mariley2250** [codetheweb/tuyapi#163]
Hi All,

Forgive me for being a massive Noob but i am having issues sending commands to my Tuya device. I can read the status etc but i am trying to inject a command into the device to turn it on/off with no luck. Any tutorials to help?? 

Basic flow.
![image](https://user-images.githubusercontent.com/13849294/53464272-b9068700-3a9d-11e9-8061-f8fefc44e296.png)

Thanks

**Comment by codetheweb** [comment]
Looks like you're using the NODE-RED module, please open an issue [here](https://github.com/hgross/node-red-contrib-tuya-smart/issues) instead.
