### ISSUE TITLE
Overwriting socket data / not waiting for a response

### ISSUE THREAD

**Issue by codetheweb** [codetheweb/tuyapi#176]
Discovered this issue when working on a separate project that depends on TuyAPI.

(I believe this may be the root cause of https://github.com/codetheweb/tuyapi/issues/158 and https://github.com/codetheweb/tuyapi/issues/103.)

I added a condition to the data event handler for the socket that checks if the parsed and returned data is an object; if not it would throw an error.  After adding this, tests started failing.

I discovered that on a fast enough machine (and testing against a local stub) it's possible to overwrite data sent to the socket by calling `.set()` and/or `.get()` quickly after each other.  Data has already been being overwritten in the test suite, but it wasn't caught because I didn't add a check to see if the returned data was an object or not.

For instance, running the test suite generated this beautiful packet:

```
000055aa000000000000000a000000607b226465764964223a223232333235313836646234613232313764633865222c2267774964223a223232333235313836646234613232313764633865222c22647073223a7b2231223a747275652c2232223a747275657d7d000000000000aa55000055aa000000000000000a000000617b226465764964223a223232333235313836646234613232313764633865222c2267774964223a223232333235313836646234613232313764633865222c22647073223a7b2231223a747275652c2232223a66616c73657d7d000000000000aa55000055aa000000000000000a000000617b226465764964223a223232333235313836646234613232313764633865222c2267774964223a223232333235313836646234613232313764633865222c22647073223a7b2231223a747275652c2232223a66616c73657d7d000000000000aa55
```

~~Obviously invalid~~.  I took a stab at implementing a [function queue system](https://github.com/codetheweb/tuyapi/tree/patch-response-bad-data), but it's not working.

Thoughts @tjfontaine @kueblc @unparagoned?

**Comment by kueblc** [comment]
I don't think that beautiful packet is necessarily invalid; I have seen devices send multiple TuyaFrames in a single packet, I've handled it [like so](https://github.com/kueblc/mocktuyacloud/blob/master/lib/lan-frame.js#L33).

**Comment by kueblc** [comment]
I haven't had the chance to do a thorough investigation, forgive me if I'm misunderstanding the issue. Breaking the new firmware has been keeping me quite occupied. I'll circle back.

**Comment by codetheweb** [comment]
No problem.

That's some very elegant code, I like it. :)

I guess it's not necessarily an invalid packet, but adding parsing abilities for that would be a bit complex if we still want to support synchronous-style code.  For instance, a user might have a snippet that looks something like this:

```javascript
device.on('connect', () => {
  device.set(true).then(didWork => console.log);
  device.get().then(status => console.log);
});
```

(Not sure if we should be trying to support these kinds of patterns anyways. 🤷‍♂️)

Because they're not waiting for the first `device.set()` to finish before calling `device.get()`, TuyAPI would generate a packet similar to the one above.  But with the way TuyAPI currently works with Promise-style callbacks (adding a second listener to the 'data' event) just emitting 2 data events when receiving a packet with two responses wouldn't really work.

If we don't want to support the above pattern; I think it would be possible to fix this for the tests just by removing the `await this.get()` that's fired when a socket first connects to a device.  I'm still kind of torn about including it, it's a nice helper but does fire a call that's potentially unnecessary.

**Comment by kueblc** [comment]
What about using `sequence` from `TuyaFrame` to match requests with responses?

**Comment by codetheweb** [comment]
Forgot that packets included a sequence number, I'll look into it.

**Comment by codetheweb** [comment]
Hey @kueblc I [added support for sequence numbers](https://github.com/codetheweb/tuyapi/commit/c2bfe82d2ff5047a84a1fb5cf890965b9b0a66cc), it's a bit hacky at the moment but it'd be great if you could look it over / test it out.

It does simplify `.get()` and `.set()` so that's good.  The main issue I'm seeing is that sending a set payload to a device results in the device ignoring the sequence number and just returning 0.  Is that consistent with your experience?  My code currently accounts for it, but not very well.

**Comment by peterjuras** [comment]
Any update on a fix for this issue? I'm using tuyaapi daily for ~ 5 smart outlets but I keep getting a similar issue to #158 every now and then, which is frustrating because I have to run the command again for the outlets to turn on/off. Or is there any workaround known?

I'm using this code to turn the devices on or off:
```ts
try {
  const device = new TuyAPI(deviceConfig);

  device.on(
    "error",
    (error: Error): void => {
      logger.error(error, "Error occurred in tuya device");
      device.disconnect();
    }
  );

  let firstResult = true;
  device.on(
    "data",
    (data: typeof TuyAPI): void => {
      if (!data) {
        return;
      }

      if (firstResult) {
        firstResult = false;

        const currentStatus = data.dps[1];
        logger.info({ data, currentStatus }, "Received current status");

        if (status === currentStatus) {
          device.disconnect();
        } else {
          device.set({ set: status });
        }
      } else {
        logger.info("Received success status");
        device.disconnect();
      }
    }
  );

  device.connect();
} catch (error) {
  logger.error("An error occurred while setting the tuya outlet status");
}
```

**Comment by codetheweb** [comment]
PR that tentatively fixes it should be merged by the end of the week @peterjuras.

**Comment by peterjuras** [comment]
Thanks for merging the PR. I gave it a go, and while the issue occurs less frequently, every now and then I still receive an error in the device.on('error') handler and the device does not turn on / off:

```
Error: Error from socket
     at Socket.client.on.err (/usr/src/app/node_modules/tuyapi/index.js:362:30)
     at emitOne (events.js:116:13)
     at Socket.emit (events.js:211:7)
     at emitErrorNT (internal/streams/destroy.js:66:8)
     at _combinedTickCallback (internal/process/next_tick.js:139:11)
     at process._tickCallback (internal/process/next_tick.js:181:9)
```

**Comment by codetheweb** [comment]
@peterjuras it's not quite ready yet; had some issues merging it last night and ran out of time to fix it.  I'll ping you when it's published and ready. :)

**Comment by codetheweb** [comment]
Hey @peterjuras, everything should be fixed now.  Update to v5.0.1 for the new code. :)

**Comment by codetheweb** [comment]
Closing this, let me know if you still have issues and I'll reopen it.
