### ISSUE TITLE
choose proxy IP?

### ISSUE THREAD

**Issue by aleqx** [codetheweb/tuyapi#180]
I'm using a wired machine which has many network interfaces, some which belong to vmware installations. When launching anyproxy-ca, it happens to choose a vmware IP address to bind to, rather than an IP on the LAN. Any way to choose the IP to bind to? if not, which file needs hacking?

**Comment by codetheweb** [comment]
Please open an issue [here](https://github.com/TuyaAPI/cli/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) and I'll try to get to it tomorrow.  There's not currently a way, but it shouldn't be too hard to add an option.
