### ISSUE TITLE
SETUP.md - please explain more

### ISSUE THREAD

**Issue by TinajaLabs** [codetheweb/tuyapi#185]
I am sent to this page, SETUP.md, from the node-red module (node-red-contrib-tuya-smart 1.1.1, https://flows.nodered.org/node/node-red-contrib-tuya-smart).

I have 4 of the tantan devices (I assume these are actually tuya).

First, it would be helpful to have a little more context in which to understand why I am going through all these steps just to get some info so I can use them in node-red.

There are 2 apps in my android play store.  Which one should I use?

Why am I installing :
```
npm i @tuyapi/cli -g
npm i anyproxy -g
```

Then run `tuya-cli list-app` to see a QR code?  What is in the QR code?  How is QR code used and how does it display from command line?  The link points to iphone help, I have android.

Why am I configuring a proxy - only shows how to do it on iphone.  How to do it on an android.

Just a little help please.

Thank you,
Chris.

**Comment by codetheweb** [comment]
The whole process is required to get a device's local key, which is used in communication locally and not easily accessible.  Basically, tuya-cli is performing a MITM attack against your phone, so it can intercept Tuya-specific requests and extract the local key from them.

I know it works for sure with the Tuya Smart app, it may or not work with branded versions of said app.

The QR code provides a link to the generated root certificate that you need to install for the proxy to be able to intercept SSL encrypted requests/responses.

I don't have an Android phone to test it with (and I didn't think it was possible on Android devices); but other users have reported that it works.  You'll have to look up instructions on how to install a root certificate and configure a proxy.

**Comment by TinajaLabs** [comment]
Even though I'm a technical person, I see too many unknowns in this process (MITM attack against your phone - does not sound good).  It felt creepy loading their smart app on my phone - now removed.

I appreciate your help, but I think I will abandon the tuya devices for now until I find a more simple and offline approach to hook them to node-red.

Thanks.

**Comment by kueblc** [comment]
@TinajaLabs you might consider flashing custom firmware to the device if you wish to take it out of cloud control completely and permanently

**Comment by TinajaLabs** [comment]
@kueblc seems a good idea.  I've had a fair amount of experience with 8266 devices but this one seems fairly well sealed. I'm guessing I'd tear it apart opening it.  Do you know if there is an OTA method to update firmware for the tuya?

Thanks.

**Comment by kueblc** [comment]
https://github.com/ct-Open-Source/tuya-convert/

Note that a recent update has been rolling out that patches this, so if you want to flash OTA, you may want to do that sooner rather than later, if it's not already too late! We are working on finding a fix
