### ISSUE TITLE
No support for door/window contact sensors

### ISSUE THREAD

**Issue by K4ds3** [codetheweb/tuyapi#187]
**Describe the bug**
Sadly it seems like the library doesn't support Tuya door/window contact sensors.

**To Reproduce**
Copy the library example code and enter the deviceid+key of a tuya contact sensor

**Expected behavior**
It should print out the sensor data

**Debug Output**
```
 TuyAPI IP and ID are already both resolved. +0ms
  TuyAPI Connecting to 10.10.10.19... +3ms
(node:15776) UnhandledPromiseRejectionWarning: Error: connection timed out
    at Socket.client.setTimeout (PATH\node_modules\tuyapi
\index.js:305:18)
    at Object.onceWrapper (events.js:281:20)
    at Socket.emit (events.js:193:13)
    at Socket._onTimeout (net.js:450:8)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)
(node:15776) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
 error originated either by throwing inside of an async function without a catch
 block, or by rejecting a promise which was not handled with .catch(). (rejectio
n id: 1)
(node:15776) [DEP0018] DeprecationWarning: Unhandled promise rejections are depr
ecated. In the future, promise rejections that are not handled will terminate th
e Node.js process with a non-zero exit code.
  TuyAPI Socket closed: 10.10.10.19 +5s
Disconnected from device.
```

**Desktop (please complete the following information):**
 - Node Version v11.13.0

**Comment by kueblc** [comment]
Unfortunately, these devices disconnect as soon as they update their state and only reconnect momentarily to inform of state changes. See https://github.com/ct-Open-Source/tuya-convert/issues/135

With this in mind, communicating with these devices over the LAN protocol is impractical. You could use `dnsmasq` or something similar to redirect MQTT calls to your local MQTT server. It's pretty messy right now but I have the code to set up something like that in [kueblc/mocktuyacloud](https://github.com/kueblc/mocktuyacloud/blob/master/lib/mqtt.js#L41)

**Comment by K4ds3** [comment]
Oh, thank you for the answer! Will look into that :)

**Comment by ramon18** [comment]
Yeah, seems a good option!
I’m using mosquitto on linux server, where I have a custom nodejs app to subscribe mtqq events from a few curtain sensors and keep track of their position whenever someone interacts with physical buttons in the sensor ;)

**Comment by K4ds3** [comment]
@ramon18 Have you flashed the sensor or are you using the stock firmware?

**Comment by ramon18** [comment]
I’m using the original firmware. But the devices does not have access to tuya cloud to prevent silent updates etc.
All I need is local control.

**Comment by codetheweb** [comment]
Closing this because it's outside of the scope of this project.

Feel free to keep using it as a discussion thread if you want.

**Comment by welkinwong** [comment]
Is it feasible if I use a power cord to continue to supply power and keep it connected to the WiFi state?

**Comment by codetheweb** [comment]
No, not really.  You'd have to flash it with new firmware as well so the device would stay awake and connected to WiFi.
