### ISSUE TITLE
Another device unable to convert

### ISSUE THREAD

**Issue by jziolkowski** [codetheweb/tuyapi#193]
Along with Blakadder from Tasmota discord I've bought these: 
https://www.aliexpress.com/item/Tuya-Smart-life-app-Control-WiFi-Light-86-EU-Button-Switch-Support-Alexa-Google-Home/32996551323.html?spm=a2g0s.9042311.0.0.5b4b4c4dkzgJNJ

3-gang and 2-gang versions. While I bricked mine 3-gang version during the convert, Blakadder reports that it undergo the process smoothly. However, I've unsuccessfully tried to tuya-convert the 2-gang version. Three different computers, 3 different systems (including live boot MX). The symptoms are similar to other reported: despite enabling the pairing procedure, the device doesn't connect to the vtrust-flash AP and timeouts. I've not connected this device with their application. Since it's trivial to flash it using standard methods, I don't want to try convert anymore, however I'm attaching the original firmware backup for you to analyze.

**Comment by jziolkowski** [comment]
file:///home/faza/Pobrane/fwbackup_ds102_2relays.bin

**Comment by jziolkowski** [comment]
[fwbackup_ds102_2relays.zip](https://github.com/codetheweb/tuyapi/files/3123316/fwbackup_ds102_2relays.zip)

**Comment by codetheweb** [comment]
Thanks for the report, but I'm not involved in the tuya-convert project at all.  Please open an issue [here](https://github.com/ct-Open-Source/tuya-convert/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).

**Comment by jziolkowski** [comment]
Yes, I did so already.
