### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by towster** [codetheweb/tuyapi#197]
I am trying to install on rapsbian stretch.. I get this error..

root@tuyablue:~# npm install codetheweb/tuyapi
(node:2937) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.79+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "codetheweb/tuyapi"
npm ERR! cwd /root
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0
root@tuyablue:~#

**Comment by Apollon77** [comment]
Please check your network connection to nmjs webpage and try again. This seems to be a temporary network eror when trying to access npmjs package repository. No bug in in this package!

**Comment by codetheweb** [comment]
Looks like you also may have to prefix the command with sudo.

**Comment by towster** [comment]
I still get an error with sudo..


```
pi@tuyablue:~ $ sudo npm install codetheweb/tuyapi
(node:759) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/pi/node_modules/tuyapi/node_modules/p-timeout/node_modules'
npm ERR! error rolling back  tuyapi@4.0.4 { Error: ENOTEMPTY: directory not empty, rmdir '/home/pi/node_modules/tuyapi/node_modules/p-timeout/node_modules'
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/home/pi/node_modules/tuyapi/node_modules/p-timeout/node_modules' }
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.79+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "codetheweb/tuyapi"
npm ERR! cwd /home/pi
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0
pi@tuyablue:~ $ 
```

**Comment by towster** [comment]
Also I dont have any trouble connecting to registry.npmjs.org

```
pi@tuyablue:/tmp $ wget https://registry.npmjs.org/
--2019-05-13 19:52:59--  https://registry.npmjs.org/
Resolving registry.npmjs.org (registry.npmjs.org)... 104.16.20.35, 104.16.19.35, 104.16.18.35, ...
Connecting to registry.npmjs.org (registry.npmjs.org)|104.16.20.35|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: ‘index.html’

index.html                                 [ <=>                                                                      ]     265  --.-KB/s    in 0s      

2019-05-13 19:53:10 (955 KB/s) - ‘index.html’ saved [265]

pi@tuyablue:/tmp $
```

**Comment by towster** [comment]
The default version of NPM installed by raspbian stretch is too low apparently. I upgraded NPM and then the install worked.

**Comment by codetheweb** [comment]
Glad you got it working.
