### ISSUE TITLE
Does the key change if I remove and re-add the device on the TuyaSmart app?

### ISSUE THREAD

**Issue by alexcastillo** [codetheweb/tuyapi#198]
Hi,

Thanks for this project!

I got a light bulb working but when changing wifi networks, I'm forced to remove the device from the TuyaSmart app and add it again. I'm wondering if that generates a new device `key`?

Is there a better way to switch wifi networks?

I initially got the `key` by following the instructions and I really don't want to do that every time I change wifi locations.

Also, `tuya-cli link-wizard` doesn't output anything for me.

Any help is appreciated.

Alex

**Comment by kueblc** [comment]
Yes, the `localKey` does in fact change when you register the device again.

You can use the local API to request the device to switch networks and keep the keys intact. Look at the implementation of `get` in `index.js`. You can construct a packet in much the same way, using the `commandByte` `CHANGE_AP` and payload `ssid` `passwd` and `token` (which can be empty).

Here is an example using another framework but it should translate pretty easily.
https://github.com/kueblc/mocktuyacloud/blob/master/lib/local-control.js

**Comment by alexcastillo** [comment]
This is great to know, thank you so much @kueblc!
