### ISSUE TITLE
Issue getting device id’s

### ISSUE THREAD

**Issue by erikleo** [codetheweb/tuyapi#199]
I have followed the instructions in https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md but i am having trouble connecting.

I have the proxy running, I am able to download the certificate and I was able to trust it.  However, after I change the proxy setting in IOS to the proxy server at port 8001, and refresh my app the id’s do not show up in the proxy server terminal and on my phone I get the error “Network connection error Please check the network.  I also cannot browse the web from the phone.  If I go to the page on port 8002 from my computer I do see some connection logs but the actual web pages don’t show up when browsing from the phone.

Does any one know what might be wrong?  I have tried running the server on windows and Linux.  I have tried 2 ios devices and some android, but I am unable to get any phone to get outside data via the proxy server.  I did try changing my computer web browser to point to the proxy server and this seemed to work but never on the phones/tablets.

Node: v10.15.2
Ios: 10.3.3 and 12.2

Any help would be appreciated.  Thanks.

**Comment by codetheweb** [comment]
It sounds like you haven't [trusted the certificate on your phone](https://support.apple.com/en-us/HT204477).

If [this site](http://www.httpvshttps.com/) currently loads without issues, then the problem lies with the certificate somewhere.

**Comment by erikleo** [comment]
I have trusted the certificate on the phone.  When i try to go to HttpvsHttps.com it does not load, it just hangs in the safari browser.  (however i do see a lot of activity in the log from server page on port 8002, when viewed from another computer, just nothing ever loads on the phone)  So neither http nor https will load on the phone.  Do i need to do any trusting of the certificate on the server?

**Comment by codetheweb** [comment]
Hmm, you shouldn't have to.

Does the proxy server page that shows requests make it look like the requests are working or failing?

**Comment by erikleo** [comment]
this is what i get while the page is hanging:
![screenshot](https://user-images.githubusercontent.com/17444748/58327944-e5147880-7dfe-11e9-8f17-a5a1b0a81247.PNG)

then after some time i finally do get some 200's
![screenshot2](https://user-images.githubusercontent.com/17444748/58328200-86033380-7dff-11e9-9602-08e89f767f1f.PNG)

**Comment by codetheweb** [comment]
Try downloading an app that allows you to ping hostnames/IPs and attempt to ping `1.1.1.1` or similar when connected to the proxy.  If it works, it might be a DNS issue.

**Comment by erikleo** [comment]
I am able to ping 1.1.1.1 in my phone when connected to the proxy. I already had 1.1.1.1 and the ip of my router as DNS addresses.  I tried deleting the router address and leaving only the 1.1.1.1 address but i am still not able to connect to web pages.

**Comment by codetheweb** [comment]
This probably isn't it, but sometimes when I'm using the proxy I have to force quit the app and relaunch before it triggers the network request.

**Comment by erikleo** [comment]
I have an update on this.  I found an old macbook in the closet and decided to give it a try and it worked.  It was failing on a laptop pc, desktop pc and linx vm with a pc host.  Is this supposed to work on platforms other than mac?  Once I got the id/key from the mac i was able to use the api without a problem on the pc.

**Comment by codetheweb** [comment]
It should, although I haven't actually tried it.

Glad you got it working.
