### ISSUE TITLE
having some problems

### ISSUE THREAD

**Issue by jjr3211** [codetheweb/tuyapi#200]
when I try to scan the qr code I can not get it to down load the certificate? Any help would be great.

**Comment by Apollon77** [comment]
Can your mobile phone reach the server the proxy is running on? What error do you get?

**Comment by jjr3211** [comment]
It gives the IP address and then it says cannot connect to the server

**Comment by divyaran7an** [comment]
Did you trust anyproxy from your phone settings? It won't connect otherwise.

**Comment by codetheweb** [comment]
Are you able to connect to the proxy from machine it's running on?

**Comment by jjr3211** [comment]
I finally got it I just rebooted my Mac and all is good now

**Comment by codetheweb** [comment]
👍
