### ISSUE TITLE
Sample async code no longer functions completely with 5.0.1/2

### ISSUE THREAD

**Issue by tomporter518** [codetheweb/tuyapi#207]
**Describe the bug**
After a set operation, the on 'data' callback is executed 2 times. The first time the data returned is only a Boolean, the second time containing the expected data object. Wrapping the on 'data' body with something like if (data) { ... } will prevent the error and allow full execution.

**To Reproduce**
1. Copy/save, configure and run the asynchronous example from the README.md
2. See error

**Expected behavior**
This 'might' be the expected behavior for the new 5.x release and the aysnc example should be fixed up to account for that OR the spurious on 'data' callback should be suppressed/avoided.

**Debug Output**
[output.txt](https://github.com/codetheweb/tuyapi/files/3262563/output.txt)

**Desktop (please complete the following information):**
 - OS: Fedora
 - OS Version: 30
 - Node Version: v10.15.3

**Comment by codetheweb** [comment]
Good catch, I'll take a look.

**Comment by codetheweb** [comment]
Sorry for the wait.

Should be fixed in v5.0.3, let me know if it works.

**Comment by tomporter518** [comment]
I have updated to 5.0.3 and tested. Everything is working well. Thanks for tracking down the cause.
