### ISSUE TITLE
Keep getting this error...

### ISSUE THREAD

**Issue by Torac2** [codetheweb/tuyapi#209]
I keep getting this error:
(node:21700) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: find() timed out. Is the device powered on and the ID or IP correct?
(node:21700) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code

Where do i even set the ip? 
Anyone know what to do? @codetheweb 

Firmware version: 1.0.5

**Comment by codetheweb** [comment]
Please stop opening multiple issues @Torac2.

Replying to original issue: https://github.com/TuyaAPI/cli/issues/16.
