### ISSUE TITLE
Common/Consistent API behaviour

### ISSUE THREAD

**Issue by unparagoned** [codetheweb/tuyapi#21]
Issue: It seems like every update not just the major 2.0 breaks my wrapper. Rather than just bitching I was wondering if it's worth considering a more elegant solution.

Is there an API or generic setup so heating functions have universal names and behaviour. I'm not sure if NEST/HIVE have a nice API.

How easy is it to switch between the various ports?
https://github.com/codetheweb/tuyapi
python-tuya a Python port by clach04 https://github.com/clach04/python-tuya
m4rcus.TuyaCore a .NET port by Marcus-L https://github.com/Marcus-L/m4rcus.TuyaCore

It would be quite nice if there was a way to easily switch the backend system between the various ports.  This might not be an issues as such so maybe you guys just need to give me a reading list and close this ticket.

**Comment by codetheweb** [comment]
I realize that and I'm sorry.  From 0.x to 2.0, I wasn't really thinking about backwards compatibility at all as it was under heavy development and very unstable.  But from now on there should be no breaking changes unless the major version number changes (2.x -> 3.x).  Even then, I'll try to build in as much backwards compatibility as is realistic.

I'm not really sure why you would want to switch between ports as they all boil down to pretty much the same thing.  Being able to easily switch between them would entail adding a lot of code to your application.
