### ISSUE TITLE
Version 3.3

### ISSUE THREAD

**Issue by bcaro** [codetheweb/tuyapi#210]
Hi!
I have a new plug. Tuya app send to it a different sequence numbers (all are in hex) :
0 0 55 aa 0 0 0 6 0 0 0 7 0 0 0 77 33 2e 33 0 0 0 0 0 0 0 18 0 1 f6 45 4d 72 f8 7b 9b ba a8 d 65 c3 d5 61 5c 63 86 32 52 6a 48 6 d0 72 58 24 fd 97 fc 23 56 6 6e d0 41 7a fa 1c b9 fe 54 5f 95 a8 5c 68 a9 f4 0 8b 2c da f9 81 c1 8e 38 6 e de a0 72 ff f6 7a c c9 f8 73 e9 77 14 d4 72 d6 df 1 ab 53 32 d9 21 26 6a 8c 8d 70 42 63 c b3 8 e9 64 a0 82 83 e4 53 e6 fa 4a 0 0 aa 55.
the key is "469c2bdefd481c25"
I have analysed this sequence numbers :
                // new frame in the case of 3.3 version:
		// case where cmd = 0x7 from app to device
		//                size in bytes   -    (bytes total) 
		// prefix :      4by		 (4) -> same as in v3.1
		// counter    4by		 (8) -> count the commands sent to the device
		// 0 0 0	   3by        	 (11) -> always
		// cmd type 1by                (12) -> 7 
		// size          4by	        (16)  as in v3.1
		// version    3by		(19) -> 3.3
		// 0 0 0 0	   4by		(23) ->always
		// counter   4by		(27) -> count the commands received from the device ?
		// 0 1 	  2by		(29) -> always
		// f6 45      2by	        (31) -> ???? always the same for each control
		// encoded data without base64_encode
		// CRC ?	4by            -> crc32 of the whole previous data
		// suffix 	4by -> as in v3.1 version
		// size = from 3 bytes version (pos = 16) -> end of frame

Encoded data is the same than in the case of 3.1 version but without base64_encoded. The result after decrypt using the above key is : 
{devId:836742153c71bf3f7e1f,dps:{1:false},t:1559630865,uid:eu1558566724167h8kfR} (quotes have been removed)
If I include bytes at pos 29-30 the data is not decrypted. So, I don't know the meaning of these bytes and this 2 bytes are always the same for other controls (but the beginning of each control is the same).
And I'm not shure about CRC

So there is some lack of information in order to sent a command to this device

**Comment by Torac2** [comment]
Do you have bulbs from tuya to?

**Comment by bcaro** [comment]
Yes I have a white bulb in 3.1 version.
I have written a plugin for Jeedom home automation.
It works for  : humidifier, multi plugs + USB +energy  consumption, thermostat, color bulbs.
But this plug (I do not own one, the owner sent me the above informations) uses a different protocol.

**Comment by codetheweb** [comment]
Please follow [this issue](https://github.com/codetheweb/tuyapi/issues/175#issuecomment-500485971) for updates on implementing the new version.

If either of you feel comfortable doing so, you're also welcome to make the necessary changes and open a PR.
