### ISSUE TITLE
Memory consumption increasing ...

### ISSUE THREAD

**Issue by Apollon77** [codetheweb/tuyapi#220]
I use the 5.1.1 of tuyapi in my ioBroker adapter and updated fom 2.x. (code available https://github.com/Apollon77/ioBroker.tuya/blob/master/main.js). I only added the discovery logic for encrypted devices to initialize them. Nothing really more changed regarding former version.

Now users report about increased memory usage (https://forum.iobroker.net/post/277732). We are currently running a comparism test for the "old" version to see how this version behaved regarding memory.

Do you have any idea if ther eis a memory leas or such in the library? I will also look at the code latser ... or do other saw also such problems?

**Comment by kueblc** [comment]
Thanks for reporting. I can't think of anything obvious that would be causing this, but I can take a look. Please keep this issue updated with any findings.

**Comment by codetheweb** [comment]
@Apollon77 are they seeing an actual memory leak or just increased memory usage?

As a baseline, my Homebridge container has 5+ plugins (including one with a TuyAPI dependency), and after running for over 2 months is currently at ~180 MB of memory consumed.

**Comment by Apollon77** [comment]
I have only reports of some users ... some have using 60-70MB RAM for the ioBroker Adapter process, some 130-160MB :-(

**Comment by kueblc** [comment]
Any news on this?

**Comment by Apollon77** [comment]
No feedback anymore ... hm ..,

**Comment by codetheweb** [comment]
Closing this, feel free to reopen if you hear more reports @Apollon77.

**Comment by Apollon77** [comment]
Sure
