### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by chriswalker01** [codetheweb/tuyapi#221]
Hi,
Thanks for your work on this. I'm looking forward to getting it working.

I'm using Ubuntu 18.04 and I have dependency issues with react.

Does anyone know how to overcome this?

root@plug:~$ npm i @tuyapi/cli -g
npm WARN deprecated clipboard-js@0.3.6: Please migrate to https://github.com/lgarron/clipboard-polyfill
/usr/local/bin/tuya-cli -> /usr/local/lib/node_modules/@tuyapi/cli/cli.js
/usr/local/lib
└── @tuyapi/cli@1.6.1

npm WARN svg-inline-react@1.0.3 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.

**Comment by Apollon77** [comment]
In fact simply ignore that message.

**Comment by codetheweb** [comment]
@Apollon77 is correct, those are just warnings.

In the future, please open issues dealing with the CLI tool [here](https://www.npmjs.com/package/@tuyapi/cli).
