### ISSUE TITLE
Tuya Zigbee Gateway Comunication

### ISSUE THREAD

**Issue by RomSand** [codetheweb/tuyapi#227]
Hi, does the API work on Tuya zigbee gateway ? Thanks.

**Comment by codetheweb** [comment]
I would guess that it does, although I don't have a zigbee gateway to test.

If you currently have the gateway, I would just try using TuyAPI and see if it works.

**Comment by tasict** [comment]
Hi @codetheweb, i have one Zigbee Gateway and i test it with TuyAPI. The device can respond request but payload return nulls.

https://github.com/codetheweb/tuyapi/issues/338#issuecomment-678965007
