### ISSUE TITLE
Quick Connect mode- which Wifi technology?

### ISSUE THREAD

**Issue by aymanhendawy** [codetheweb/tuyapi#239]
Hi,
Kindly I was just wondering which WIFI technology used for Tuya quick connect mode? WIFI Easy Connect or Wifi direct or what? just in case I want to integrate my own custom hardware with their app or their whole ecosystem.

Thanks

**Comment by codetheweb** [comment]
I don't know of a specific name for it.  You'll get better help if you ask Tuya, as we aren't affiliated with them.

Closing as a non-issue.
