### ISSUE TITLE
npm WARN enoent ENOENT: no such file or directory 'package.json'

### ISSUE THREAD

**Issue by renegade2k** [codetheweb/tuyapi#24]
#17 Hey guys.
I'm trying to install the package as mentioned in the FAQ:
`npm install codetheweb/tuyapi`
Which returns

> npm WARN enoent ENOENT: no such file or directory, open '/home/openhabian/package.json’
npm WARN openhabian No description
npm WARN openhabian No repository field.
npm WARN openhabian No README data
npm WARN openhabian No license field.

I don't know how to resolve this

**Comment by codetheweb** [comment]
This is not a problem with TuyAPI.  NPM is just warning you that you don't have a `package.json` file in your current directory.  Unless there are further errors that you didn't paste here, TuyAPI was installed correctly.
