### ISSUE TITLE
error key too small plug tuya

### ISSUE THREAD

**Issue by etttoutoi** [codetheweb/tuyapi#241]
Hello,

it's the first time i use a plug in domoticz. So i would to install the tuyapi, to add my plugs.

I follow the steps describes in steup.md . it's ok, but when i try to install 

sudo anyproxy-ca

it return me this error: 

 sudo anyproxy-ca
detecting CA status...
Error: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small
    at Object.createSecureContext (_tls_common.js:136:17)
    at Server (_tls_wrap.js:870:27)
    at new Server (https.js:62:14)
    at Object.createServer (https.js:85:10)
    at /usr/local/lib/node_modules/anyproxy/node_modules/node-easy-cert/dist/ind                                                                             ex.js:189:30
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

I'm a nood and i don't know how solved it. 

Thanks for your help!!

**Comment by Apollon77** [comment]
I know this error from nodejs 10.16+ when an ssl key is only 1024bit or less. Because this is forbidden starting nodejs 10.16 ... what certificate you Use?

**Comment by etttoutoi** [comment]
I don't know. I only install domoticz and try to install plug in tuya with the tuto.

But I don't know all the rest. 

I would be help step by step to resolve my problem.

**Comment by codetheweb** [comment]
@etttoutoi currently the AnyProxy method does not work with recent versions of Tuya apps, please take a look at [these instructions](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP_DEPRECATED.md) instead.

**Comment by etttoutoi** [comment]
@codetheweb Thanks for your answer.

I'm actually on holidays, so i will test your method when i back.

Thank you

**Comment by etttoutoi** [comment]
I

> @etttoutoi currently the AnyProxy method does not work with recent versions of Tuya apps, please take a look at [these instructions](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP_DEPRECATED.md) instead.

Thank you very much for your help, it works perfectly !!!

**Comment by codetheweb** [comment]
Glad to hear it.

**Comment by Apollon77** [comment]
I had one report that (seems at least on Android where also more problems happen in the meantime) the „tuya app“ was working (while smartlife app was not)
