### ISSUE TITLE
Tuya smart valve don't answer

### ISSUE THREAD

**Issue by Saniksanik** [codetheweb/tuyapi#243]
Have anyone use Smart Valve for Tuya? It use esp8266, but i cannot connect to it. Smart plug work normally, but valve not connect. Connection was time outed without error messages with set or get.
Description of device is here https://eachen.cc/product/eachen-wifi-switch-for-gas-water-valve-controller-gw-ty-tuya-smart-life/
Maybe i can save any debug lig?

**Comment by kueblc** [comment]
We can't help you without more information. Please fill out the entire form when you open an issue. Feel free to reopen once you have all the information.

**Comment by Saniksanik** [comment]
What info must i send?

**Comment by kueblc** [comment]
When you open a new issue there is already a template in the form

**Comment by Saniksanik** [comment]
I give link to device
I know that device use Tuya or Smart Life app
I know that device based at esp8266
I give ID and key, but Tuyaapi cli app frozen when i try set or get with right credentials

**Comment by Saniksanik** [comment]
What about any way give debug log from tuyaapi for more info?

**Comment by Apollon77** [comment]
Is this an battery powered device only? Then it may be only connection to tuya cloud to send or get data and offline else ?!

**Comment by Saniksanik** [comment]
No. This device is powered by 12V power adapter and is online all time, that powered. Have two status - enable (valve is open), and disable (valve is closed).
[https://d1y6jrbzotnyjg.cloudfront.net/UGCPR/da24d3aba98f4681b96544a3ca47cb43/V1/2b039cf9ef9f4b5f907137171b4ff19d/ShortForm-Generic-480p-16-9-1409173089793-rpcbe5.mp4?Expires=1567016834&Signature=Tw1Xt5mz6iJ-itLBm0Npu82eZLCb~jzzDr-pQYfiGSGReBVEDNpouNl4FaZE66jtjnOi70-DaBNGNuKzF6C8~bsQlmMnTAZPWYvrf~94x1eXT6iTW27BKkyGxUzge3IWOEibv3W0IKCdazfGMPE~ZEujESjr~ZxjJ4we5rWRbac_&Key-Pair-Id=APKAJ62XWKZ35EOVO4XA](url) - here is link to video about this valve
