### ISSUE TITLE
Write EPIPE / Ping Pong

### ISSUE THREAD

**Issue by andy0172** [codetheweb/tuyapi#245]
Hi and thanks for all this work. It was all fine until I clicked on update firmware for my tuya sockets :-(

Now I have updated to the latest version, but still get the same error like in the initial post:
TuyAPI IP and ID are already both resolved. +0ms
TuyAPI Connecting to 192.168.178.74... +16ms
TuyAPI Socket connected. +27ms
TuyAPI GET Payload: +5ms
TuyAPI { gwId: '18122702600194bff1eb', devId: '18122702600194bff1eb' } +1ms
TuyAPI Error event from socket. 192.168.178.74 { Error: write EPIPE
at WriteWrap.afterWrite [as oncomplete] (net.js:868:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' } +22ms
events.js:183
throw er; // Unhandled 'error' event
^

Error: Error from socket
at Socket.client.on.err (/usr/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/index.js:323:30)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at onwriteError (_stream_writable.js:417:12)
at onwrite (_stream_writable.js:439:5)
at _destroy (internal/streams/destroy.js:39:7)
at Socket._destroy (net.js:568:3)
at Socket.destroy (internal/streams/destroy.js:32:8)
at WriteWrap.afterWrite [as oncomplete] (net.js:870:10)

Details of tuya socket:
MCU Modul 1.0.7
Wi-Fi Modul 1.0.7

Strange behavior, with the same installation I can turn on and off a tuya light with this details:
MCU Modul 1.1.1
Wi-Fi Modul 1.1.1

**Comment by andy0172** [comment]
I think I'm pretty close again, but when trying to debug the set command it will always ping pong:
 DEBUG=* tuya-cli set --ip '192.168.178.75' --id '68282475600194c05b0a' --key 'xxxxxxx' --dps 1 --set 'true'
 TuyAPI IP and ID are already both resolved. +0ms
  TuyAPI Connecting to 192.168.178.75... +13ms
  TuyAPI Socket connected. +119ms
  TuyAPI GET Payload: +4ms
  TuyAPI { gwId: '68282475600194c05b0a', devId: '68282475600194c05b0a' } +0ms
  TuyAPI Pinging 192.168.178.75 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +34ms
  TuyAPI Parsed: +9ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +1ms
  TuyAPI Pong from 192.168.178.75 +4ms
  TuyAPI Pinging 192.168.178.75 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +58ms
  TuyAPI Parsed: +2ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +0ms
  TuyAPI Pong from 192.168.178.75 +1ms
  TuyAPI Pinging 192.168.178.75 +10s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +14ms
  TuyAPI Parsed: +1ms

Without the debug it will just stay there and nothing happens. Any comments?

**Comment by andy0172** [comment]
I managed to get it working with added this to the command:
 --protocol-version 3.3

**Comment by codetheweb** [comment]
Glad you got it working, sorry for the late response.
