### ISSUE TITLE
cant load the api

### ISSUE THREAD

**Issue by NFLD99** [codetheweb/tuyapi#249]
https://i.imgur.com/JHRedqF.png <- i get this error all the time, npm is installed and global is installed aswell

C:\Users\Dawso\AppData\Roaming\npm\node_modules\@tuyapi\cli\lib>tuya-cli list-app
'tuya-cli' is not recognized as an internal or external command,
operable program or batch file.

**Comment by codetheweb** [comment]
@NFLD99 what config file are you trying to find?

**Comment by NFLD99** [comment]
> @NFLD99 what config file are you trying to find?

the one where id put https://github.com/codetheweb/tuyapi#asynchronous-event-based-recommended (in the end the plan/hope is to have it linked to csgos gsi)

**Comment by codetheweb** [comment]
The CLI tool should output found IDs and keys to the terminal, the `list-app` command doesn't save anything anywhere.

**Comment by NFLD99** [comment]
ohhh i was under the impression that this could be used to control the lights from a pc like some other lights can [example](https://github.com/doobix/csgo-c4-hue-node)

**Comment by kueblc** [comment]
> ohhh i was under the impression that this could be used to control the lights from a pc

Yes, that's the whole point

**Comment by codetheweb** [comment]
The CLI does support controlling devices; although I'm guessing that it won't be as simple to control lights as you may be thinking since the format's a little complicated.

Try running `tuya-cli set --help` to see the options.

Closing for now, feel free to reopen if you find an issue with the CLI tool or TuyAPI.
