### ISSUE TITLE
tuya-cli list-app doesn't show devices anymore when sensors are added

### ISSUE THREAD

**Issue by Janghou** [codetheweb/tuyapi#250]
**Describe the bug**
tuya-cli list-app shows my devices (id,key) for several bulbs. Once I started adding a sensor, tuya-cli list-app stopped working. 
Brand: LSC-Smart Connect. Smart Life 3.9.1 app.

**To Reproduce**
1. Add several bulbs first
2. tuya-cli is showing devices
3. Add one sensor or plug
4. tuya-cli is not showing any devices
5. after removing the sensor or plug, tuya-cli is showing devices again

**Expected behavior**
Show all devices including sensors, and plugs

**Desktop (please complete the following information):**
 - OS: Kubuntu 18.04 LTS
  - Node Version: v8.10.0

**Comment by codetheweb** [comment]
Do you have the ability to manually sniff the HTTP traffic from your phone and see the requests being sent?  My guess is that the API formats the response differently when certain types of devices are present, but I can't really test that theory as tuya-cli works with all of my devices.

Probably related to [this issue](https://github.com/TuyaAPI/cli/issues/26).

**Comment by Apollon77** [comment]
It junk I might have a solution. Tuyacli is currently only reading one chunk but data may be longer. You need to read all data. 

In fact adopt coke like in https://github.com/Apollon77/ioBroker.tuya/commit/17796cec695400adfd26d63c7e8d01595edfe8b6

And maybe also add https://github.com/Apollon77/ioBroker.tuya/commit/83c4a50a939139831b8c2a8392f75cf8f07afa83

Both changes made it working for currently all users so far. 

I can try to prepare a PR the next days but cannot promise ...

**Comment by codetheweb** [comment]
Got it, that makes sense.  Thanks for tracking down the issue.

I'll prepare a patch if I have time.

**Comment by codetheweb** [comment]
@Janghou can you update to v1.8.4 and try again please?  Just shipped a patch that should fix this issue.

**Comment by Janghou** [comment]
Tried 1.8.4, and I see all devices now, including sensors. ;)

Thx all.

**Comment by codetheweb** [comment]
Glad to hear it's working.

**Comment by Apollon77** [comment]
Sorry that I did not found the time to prepare an PR :-(

**Comment by codetheweb** [comment]
No problem, it was just a few lines. 😛 

@Apollon77
