### ISSUE TITLE
tuya-cli cannot accept strings that look like numbers as dpi values

### ISSUE THREAD

**Issue by jezzaaa** [codetheweb/tuyapi#254]
I have a smart kettle that accepts a "keep temp at X" parameter in Celcius, but rather than a numeric, it requires a string, because one of the possible options is "setcurrenttemp". The possible values are "40", "50", "60", "80", "90" and "setcurrenttemp".

If I use tuya-cli with ```--set 80``` it is presented to the device as a numeric, which is invalid. If I use ```--set \"80\"``` it is presented to the device as a string with the extra quotes, which is also invalid. I can't find a way to send a plain string consisting of only digits.

If I create a program using tuya-api, it creates the correct string type and with no quotes, and the payload is accepted by the device.

**To Reproduce**

1. execute:
```
$ DEBUG="*" tuya-cli set --id 4215100384f3ebedb86a --ip 192.168.1.95 --key 46656a716c58f29b --protocol-version 3.3 --dps 102 --set \'80\' 2>&1 |grep 102
  dps: { '102': "'80'" } }
```
2. note that the value of the dps 102 has extra single quotes.
3. execute:
```
$ DEBUG="*" tuya-cli set --id 4215100384f3ebedb86a --ip 192.168.1.95 --key 46656a716c58f29b --protocol-version 3.3 --dps 102 --set \"80\" 2>&1 |grep 102
  dps: { '102': '"80"' } }
```
4. note that the value of dps 102 has extra double quotes

**Expected behavior**
I expect that tuya-cli would recognise a single-quoted string and remove the quotes but keep the type as string.

**Desktop (please complete the following information):**
 - OS: Raspbian GNU/Linux 9 (stretch)
 - Node Version v11.6.0

**Comment by codetheweb** [comment]
Just added a flag that should help in v1.9.0, please upgrade and try adding `--raw-value` to your arguments.

**Comment by jezzaaa** [comment]
You champion! Works a treat!!! Thanks mate.

**Comment by codetheweb** [comment]
👍 glad it's working.
