### ISSUE TITLE
Docker not able to connect to smart plug

### ISSUE THREAD

**Issue by limpygnome** [codetheweb/tuyapi#256]
**Describe the bug**
Unable to connect to a smart plug whilst running within a docker container, using either the id or ip. Container is able to curl to the smart plug via ip on port 6668.

**To Reproduce**
Steps to reproduce the behavior.

Dockerfile:
````
FROM node:10

# Set working directory
WORKDIR /usr/src/app

# Copy dependencies
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy source files
COPY . .

# Run it!
CMD [ "node", "index.js" ]

````

index.js:
````
const TuyAPI = require('tuyapi');
(async () => {
            var device = new TuyAPI({
                ip: "xxx",
                key: "xxx"
            });
            await device.find();
            var result = await device.connect();
            var status = await device.get({"schema" : true});
        console.log(status);
})();
````

Build and run locally:
- npm init
- npm install codetheweb/tuyapi --save
- node index.js

Now run it with docker:
- docker build -t limpygnome/test .
- docker run limpygnome/test:latest

Observe container unable to connect.

**Desktop (please complete the following information):**
 - OS: macOS
 - Node Version v9.3.0

**Comment by limpygnome** [comment]
**Solved!**

Can be closed, but for anyone else...

## Docker
Realised a local listener is setup on port 6666 for UDP, thus the following works:
````
docker run -p 6666:6666/udp  limpygnome/test:latest
````

Looks like port 6667 may be required in some cases (encrypted messages from reading the module?), but wasn't needed in my case.

## Kubernetes
Include the following in your deployment config:
````
hostNetwork: true
````

Although be warned, this will directly expose the container on a node, and bind on the node's network adapter. Thus you may get port conflicts, and cannot schedule a pod on a node where 6666 or/and 6667 is already in use (including another replica).

**Comment by codetheweb** [comment]
Glad you got it working.
