### ISSUE TITLE
Payload encrypted/gibberish string

### ISSUE THREAD

**Issue by xero08** [codetheweb/tuyapi#260]
**Describe the bug**
Hi. I'm trying to setup an RGB light bulb with the API. I'm able to connect to the device, but the payload output seems to be a gibberish/encrypted string rather than a JSON object.

**To Reproduce**
Ran the sample code in readme (sync) in debug mode

**Expected behavior**
The payload should be a JSON

**Debug Output**
```
TuyAPI IP and ID are already both resolved. +0ms
  TuyAPI Connecting to 192.168.0.100... +3ms
  TuyAPI Socket connected. +105ms
  TuyAPI GET Payload: +0ms
  TuyAPI { gwId: '748041822cf432bc6720', devId: '748041822cf432bc6720' } +0ms
  TuyAPI Received data: 000055aa000000010000000a0000002c000000018e798fa4c88dca37d6b9bfc027ee26e4f616088546331d918358897d6fa5c9220bb845ff0000aa55 +23ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: '�y��ȍ�7ֹ��\'�&��\u0016\b�F3\u001d��X�}o��"',
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 10,
  TuyAPI   sequenceN: 1 } +0ms
  TuyAPI GET Payload: +0ms
  TuyAPI { gwId: '748041822cf432bc6720', devId: '748041822cf432bc6720' } +0ms
  TuyAPI Received data: 000055aa000000020000000a0000002c000000018e798fa4c88dca37d6b9bfc027ee26e4f616088546331d918358897d6fa5c92234733b6a0000aa55 +19ms
  TuyAPI Parsed: +0ms
  TuyAPI { payload: '�y��ȍ�7ֹ��\'�&��\u0016\b�F3\u001d��X�}o��"',
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 10,
  TuyAPI   sequenceN: 2 } +0ms
Current status: �y��ȍ�7ֹ��'�&��F3��X�}o��"
  TuyAPI GET Payload: +1ms
  TuyAPI { gwId: '748041822cf432bc6720', devId: '748041822cf432bc6720' } +0ms
  TuyAPI Received data: 000055aa000000030000000a0000002c000000018e798fa4c88dca37d6b9bfc027ee26e4f616088546331d918358897d6fa5c92297e513260000aa55 +19ms
  TuyAPI Parsed: +0ms
  TuyAPI { payload: '�y��ȍ�7ֹ��\'�&��\u0016\b�F3\u001d��X�}o��"',
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 10,
  TuyAPI   sequenceN: 3 } +0ms
New status: �y��ȍ�7ֹ��'�&��F3��X�}o��".
  TuyAPI Disconnect +1ms
  TuyAPI Socket closed: 192.168.0.100 +0ms
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - OS Version : 19.10
 - Node Version : v10.15.2

**Additional context**
This is a smart bulb from Wipro (IN). Firmware version is 3.3 (Got this from the Firmware Upgrade - 3.3.16), and I'm using the same in the options object to the constructor.

**Comment by bentona** [comment]
I was experiencing the issue in #246, but after updating the library, I'm getting this error as well.

OS: OSX 
OS Version: 10.14.3
Node Version: v10.13.0

After some digging, I believe it's happening in this block:

https://github.com/codetheweb/tuyapi/blob/master/lib/cipher.js#L70

After adding some logging, the root error appears to be:
```
 error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
```
I have no idea what I'm doing here, but I found https://github.com/nodejs/node/issues/2794, so I tried adding 
```decipher.setAutoPadding(false);```
which seemed to resolve the error.

The result apparently still isn't valid JSON(`Unexpected token � in JSON at position 0`), but here it is in `hex` (only way I knew how to get it readable).

```
b9bfb847dd210d381c7eee64bdde19378fc245d6040290eacb9b894ae46aeaf497c052106a047ea20bb253ac9fad1529e6fb62a3a344ab008bb4c2844d223d45dd61c9d2c4e92b64468750a7a85eb154fce19a0c5ec3616226ec99a0aa28920b4d386810be912a30078b1788404d375e7f4bc2f5985534f251bf65eb547fa6a68b2ec26387fcb876f75f7ef5bb7d777d
```

**Comment by kueblc** [comment]
A likely culprit for an error like this is a wrong key. Double check you've got the `localKey` correct.

**Comment by bentona** [comment]
@kueblc I suspected that, but if I change the key to any other value, I immediately get a `TypeError: Key is missing or incorrect.`

**Comment by kueblc** [comment]
This error is thrown [if the key is not a 16 character string](https://github.com/codetheweb/tuyapi/blob/43247e2f1e13a81869320c7bef5cf5e1436a3605/index.js#L46)

**Comment by bentona** [comment]
Wow you're totally right, I re-sniffed my key and now I'm back to `Data from device: json obj data unvalid` from #246 :/

**Comment by xero08** [comment]
This seems legit. I'll try this soon and get back.

**Comment by xero08** [comment]
Thanks. This resolved it. I had generated the `key` with a different account. I logged in with the new account and got the new key and it started working fine.

Cheers!
