### ISSUE TITLE
Just wondering what else can be done with this node module

### ISSUE THREAD

**Issue by aolin480** [codetheweb/tuyapi#261]
I was so excited just to see the key and ID pairs in terminal, but one questtion I have is. What can I do with this module, now that I have the keys and ids. I would like to control the devices how I want (ex: make the lights flicker if X, slowly fade in and out each light, etc). Was wondering if there are still some unknowns I need to figure out on how to achieve this.

Thanks for all your work on this API thus far. I am new to home automation, and I lucked out and have some tuya cloud type bulbs (Smart Life). Since I am a developer, just seeing how I can bend these to my will 😁

Kind regards!

**Comment by codetheweb** [comment]
There are a few different effects available through the app that you should be able to replicate.

I think someone may have posted a breakdown of what different DPS values do for light bulbs in the general discussion at some point: https://github.com/codetheweb/tuyapi/issues/5.

I'd try sniffing your phone's traffic when toggling different effects and see what values change.

**Comment by aolin480** [comment]
> There are a few different effects available through the app that you should be able to replicate.
> 
> I think someone may have posted a breakdown of what different DPS values do for light bulbs in the general discussion at some point: #5.
> 
> I'd try sniffing your phone's traffic when toggling different effects and see what values change.

Awesome. Thanks for the lead! Yeah, I was reading how people were using wire shark, and other network analyzers to possibly see what their devices are doing. I'll definitely check out the DPS values. This API definitely got me closer, so I appreciate the help again.

**Comment by kueblc** [comment]
Worth looking into:
- https://github.com/clach04/python-tuya/wiki/DeviceSchemas
- https://github.com/codetheweb/tuyapi/issues/5#issuecomment-412120638

**Comment by codetheweb** [comment]
Closing this for now, feel free to reopen @aolin480 if you have more questions.
