### ISSUE TITLE
Able to produce QR code but nothing happens after scanning

### ISSUE THREAD

**Issue by EmielCapelle** [codetheweb/tuyapi#263]
Hi, to start with a disclaimer; i'm not a programmer so sorry for asking these kind of questions. And also a compliment: Thanks for all the great work!
I followed the setup steps, well at least step 1 and 2 :) but when I generete the QR code in step 3, i get the QR code, scan it with a phone nothing happens (tried both android and ios iphone) . The QR code says i need to go to <internal address>:8002/ca.pem but the line below the QR code mentions a different port (being 8001). If I amend the <internal address>:8002/ca.pem to 8001/ca.pem i got the same result > nothing. Server (in Dutch) Safari kan de pagina niet openen omdat de server niet meer reageert > hence 'Server not responding'). 

I've used Ubuntu 18:10, Ubuntu and Debian on a Windows 10 machine. 

FYI: I updated and upgraded the aforementioned CLI's, installed NPM, used sudo (necessary because of the error/issues when installing npm and tuya). 
`netstat` in CMD doesn't reveal/show the 8001/8002 port. 

What am i missing here?

**Comment by codetheweb** [comment]
There are two different ports: one for the proxy server (8001) and one for the web server that you download the certificate from (8002).

I'm not sure how it works on Android, but if you scan the QR code in the Camera app on a recent version of iOS it prompts you to open the webpage.

You can also try entering the URL manually, it should be `http://IP_OF_COMPUTER:8002/ca.pem`.

**Comment by EmielCapelle** [comment]
Thanks for your fast reply. Don't know what i'm missing. I have three ios devices. Neither of them are responsive once the QR code is scanned. In other words, nothing happens. No cert. downloaded/promted. The CLI keeps showing 'waiting for request'. Do i have to activate something. I did a ipconfig /release and /renew. Thought this perhaps might help, but same result. I have fixed the new internal IP. Any other tips?

**Comment by codetheweb** [comment]
No, it should be working.  The QR code doesn't do anything magic, I would try entering the URL (`http://IP_OF_COMPUTER:8002/ca.pem`) manually in Safari.  For `IP_OF_COMPUTER`, use the IP listed in the console below the QR code.

**Comment by EmielCapelle** [comment]
Fixed it. Had to open the firewall on my computer. It was blocking incoming traffic. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codetheweb** [comment]
Glad you figured it out.
