### ISSUE TITLE
new Protocol v3.3

### ISSUE THREAD

**Issue by harryzz** [codetheweb/tuyapi#268]
{ name: 'k1', id: '70020004bcddc29eaf42', key: 'ac20ed1174ee90ae' }

ON:
000055aa00000000000000080000006b00000000332e33000000000000000b000000010637936616a6d80bde64ba85db4603b20e69b2e32b65d5281010b6d2cb139070fa75f8293fdb7e91e0ae05b1646f90ad50c41eae3c9b0e79d13e09ec411a6b9040b60f2c772e0c3dbd3009d59c56a43d8930a24f0000aa55

OFF:
000055aa00000000000000080000006b00000000332e33000000000000000c000000010637936616a6d80bde64ba85db4603b20e69b2e32b65d5281010b6d2cb1390709390c4fc84c0ea549295c339eb6969ed51cc78d5f6c919347276ea0bbaec3f548dcb0c26d33a3c332bb7bfd813f810cd668d98740000aa55

if need more data just tell me.

br
Zahari

**Comment by Apollon77** [comment]
Protocol 3.3 is already working. What is the topic here?

**Comment by harryzz** [comment]
May be my mistake i have tested with tuya-mqtt and there is no success.
I will investigate what is the problem. Sorry for disturb.

br
Zahari

**Comment by codetheweb** [comment]
I'm closing this for now @harryzz, feel free to reopen it if you have a specific issue.
