### ISSUE TITLE
DPS information is not updated

### ISSUE THREAD

**Issue by moryoav** [codetheweb/tuyapi#272]
I tried both tuya-cli and tuyapi itself, problem is the same (running on Windows 10, latest build, not sure it matters). Trying to get power consumption information from a smart plug.
 
The problem is this --  I'm able to get the DPS data, but the data is not updated. Only if I open the Smart Life app, I go to the energy tab for this device, I see updated information, I then close the app and query the plug with Tuyapi - I'll get a correct reading. But only once. The reading will remain the same, the DPS data will not change until I reopen the app. It's like the plug only reports correct information when the app queries it, otherwise it perhaps just repeats the last known information? Any solution for this?

For the record - this is one of the things I tried:
tuya-cli get --id [myid] --key [mykey] --dps 19 --ip 192.168.1.170 --protocol-version 3.3

**Comment by kueblc** [comment]
Can you perform a network capture between the app and the device so we can see what the app does? You may need to do this with both devices disconnected from the internet and only on local wifi so that the app uses the local control protocol.

**Comment by moryoav** [comment]
Could you explain briefly how to do that?

**Comment by kueblc** [comment]
There are many different ways depending on your set up. Since you're using Windows, maybe you can use that to set up a hotspot, and then run WireShark to record traffic over that hotspot. You'd need to connect your phone to the hotspot and re-register the device. Then disconnect your computer from the outside internet and perform some actions via the app while recording.

**Comment by moryoav** [comment]
I didn't end up recording the traffic, this just started working fine. I'm not sure yet, but I guess the thing is that this cannot run when the app is open on the phone, and I think I had to force close it and resist the temptation to open it to verify the results. So for now this seems to be working. Thank you!

**Comment by kueblc** [comment]
Glad its working!
