### ISSUE TITLE
Device refresh doesn't work

### ISSUE THREAD

**Issue by irek74** [codetheweb/tuyapi#273]
Hi,
I've done everything according to your manual. Profile has been installed on my iPad. Proxy IP and port is set. I've network access because I can open any web page using Safari. It works extremally slow, but it works. The issue is with TuyaSmart app: when I try to refresh devices list by scrolling down, I receive message: no network connection, check yor network.
On terminal connected to raspberry (on another computer) I can see message: "Waiting for request...".
One more thing: I can controll my switch from TuyaSmart app - I've only one device.
I'm not able to get list of ID and key pairs.
What am I doing wrong?
Irek

**Comment by codetheweb** [comment]
That message is expected, but at that point the terminal process should quit and give you your ID/key pairs.

Sometime I have to force-quit the TuyaSmart app from the background and open it again before it sends the correct request that's intercepted.

**Comment by costispavlou** [comment]
doesn't work for me either. 
installed the profile
refreshed the app, closed, reopened.
stuck at waiting for request.

**Comment by codetheweb** [comment]
You could also try logging out and logging back into the app.  Just to make sure, you're using the TuyaSmart app and not a whitelabeled version?

**Comment by costispavlou** [comment]
i've done everything as you can see in the issue i've opened [here](https://github.com/AMoo-Miki/homebridge-tuya-lan/issues/132). 
i gave up and installed tuya-web that worked well, with the downside that the shutters show up as lights.
if anyone is willing to help me set them again, I can give my full json or teamviewer whatever.

**Comment by cladmonitor** [comment]
I came here to point out I had the same issue becuase after getting several errors in the app saying there was no connection I figured it wasn't working. Fortunately by the time I had read all of this, I looked at the console and the devices were listed. Maybe some retry interval is the problem and you have to be very patient (like 3-5min).

**Comment by blckshdw** [comment]
I was having the same issues.  I logged out of the app and restarted my phone and that seemed to have made the difference

**Comment by dutch2005** [comment]
Not working here eighter...

Incorrect local timer - please correct it 50502

**Comment by codetheweb** [comment]
https://github.com/codetheweb/tuyapi/issues/280

**Comment by codetheweb** [comment]
#280 has been resolved.
