### ISSUE TITLE
V3.1 protocol without effect and V3.3 crash

### ISSUE THREAD

**Issue by algry13** [codetheweb/tuyapi#276]
Hello,
I am French and my English is very bad.
I use this material with Tuyapi:
[link to Amazon French!](https://www.amazon.fr/gp/product/B07NKNCNJV/ref=ppx_od_dt_b_asin_title_s00?ie=UTF8&psc=1)
Corresponds to TEEKAR WF-CS01

- Tuyapi encryption version 3.1 without effect on Curtain Switch
- Tuyapi encryption version 3.3 crash

Attached the source and result in version 3.1 and 3.3
Thanks for your help
___________________________________________________________________________________
Source:
const TuyAPI = require('tuyapi');

const device = new TuyAPI({
	id: '62268408bcddc2a32541',
	key: '5cxxxxxxxxxxe59',
	ip: '192.168.0.114',
	version: 3.3
});

let stateHasChanged = false;

// Find device on network
device.find().then(() => {
  // Connect to device
  device.connect();
});

// Add event listeners
device.on('connected', () => {
  console.log('Connected to device!');
});

device.on('disconnected', () => {
  console.log('Disconnected from device.');
});

device.on('error', error => {
  console.log('Error!', error);
});

device.on('data', data => {
  console.log('Data from device:', data);

  console.log(`Boolean status of default property: ${data.dps['1']}.`);
  

  // Set default property to opposite
  if (!stateHasChanged) {
	console.log('stateHasChanged')
	device.set({dps: "1", set: "2"}).then(() => console.log('device was turned off'))
    // Otherwise we'll be stuck in an endless
    // loop of toggling the state.
    stateHasChanged = true;
  }
});

// Disconnect after 10 seconds
setTimeout(() => { device.disconnect(); }, 10000);
___________________________________________________________________________________
Result version: 3.3 : crash
  TuyAPI IP and ID are already both resolved. +0ms
  TuyAPI Connecting to 192.168.0.114... +18ms
  TuyAPI Socket connected. +20ms
Connected to device!
  TuyAPI GET Payload: +6ms
  TuyAPI { gwId: '62268408bcddc2a32541', devId: '62268408bcddc2a32541' } +1ms
  TuyAPI Received data: 000055aa000000010000000a0000001d000000016461746120666f726d6174206572726f7271bf61a40000aa55 +34ms
  TuyAPI Parsed: +7ms
  TuyAPI { payload: 'data format error',
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 10,
  TuyAPI   sequenceN: 1 } +1ms
Data from device: data format error
/home/pi/test/test.js:37
  console.log(`Boolean status of default property: ${data.dps['1']}.`);
                                                             ^

TypeError: Cannot read property '1' of undefined
    at TuyaDevice.device.on.data (/home/pi/test/test.js:37:62)
    at emitThree (events.js:136:13)
    at TuyaDevice.emit (events.js:217:7)
    at TuyaDevice._packetHandler (/home/pi/node_modules/tuyapi/index.js:411:10)
    at packets.forEach.packet (/home/pi/node_modules/tuyapi/index.js:315:43)
    at Array.forEach (<anonymous>)
    at Socket.client.on.data (/home/pi/node_modules/tuyapi/index.js:311:19)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
___________________________________________________________________________________
Result version: 3.1 : without effect
  TuyAPI IP and ID are already both resolved. +0ms
  TuyAPI Connecting to 192.168.0.114... +21ms
  TuyAPI Socket connected. +28ms
Connected to device!
  TuyAPI GET Payload: +7ms
  TuyAPI { gwId: '62268408bcddc2a32541', devId: '62268408bcddc2a32541' } +1ms
  TuyAPI Received data: 000055aa000000010000000a0000003c000000007b226465764964223a223632323638343038626364646332613332353431222c22647073223a7b2231223a2231227d7dcec333490000aa55 +39ms
  TuyAPI Parsed: +11ms
  TuyAPI { payload: { devId: '62268408bcddc2a32541', dps: { '1': '1' } },
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 10,
  TuyAPI   sequenceN: 1 } +1ms
Data from device: { devId: '62268408bcddc2a32541', dps: { '1': '1' } }
Boolean status of default property: 1.
stateHasChanged
  TuyAPI SET Payload: +10ms
  TuyAPI { devId: '62268408bcddc2a32541',
  TuyAPI   gwId: '62268408bcddc2a32541',
  TuyAPI   uid: '',
  TuyAPI   t: 1576740905,
  TuyAPI   dps: { '1': '2' } } +1ms
  TuyAPI Disconnect +10s
  TuyAPI Socket closed: 192.168.0.114 +3ms
Disconnected from device.
___________________________________________________________________________________

**Comment by algry13** [comment]
Hi all
The problem comes from me, the version is really 3.1
In fact, I had reconfigured the device via Smart Life and had not recovered the new key.
Reading the different posts I realized my stupidity.
Sorry for the inconvenience, subject closed.
Please note: great project and great achievement, thank you to the team.

**Comment by codetheweb** [comment]
Glad you got it figured out. 👍

**Comment by codetheweb** [comment]
I added a note about this behavior to the README since it seems there's been quite a few users with the same issue.
