### ISSUE TITLE
Curtain Wifi Switch *2 and Wifi Switch

### ISSUE THREAD

**Issue by costispavlou** [codetheweb/tuyapi#277]
can you help me setup my 3 tuya devices ? 
I've got a wifi switch and two curtain wifi switches..
I'm using hoobs
Installed the plugin successfully but nothing works.
My config is just showing:
{
    "platform": "TuyaPlatform"
}
Profile also installed but not updating.
I've installed both smart life app and tuya smart app on my iPhone.
Any help will be appreciated.. thanks

**Comment by kueblc** [comment]
Hi @costispavlou 

I'm not quite sure what you're asking. It doesn't sound like you are asking about tuyapi, so this might not be the best place to find answers.

This repo is dedicated to tuyapi only, a library for integrating Tuya devices into your software project. If you're not writing any software, this is probably of no use to you.

Try seeking support from the project you are using directly.

**Comment by costispavlou** [comment]
apologies, I thought this was the dedicated page for the npm tuya for homebridge.
