### ISSUE TITLE
Problem with tuya-cli proxy

### ISSUE THREAD

**Issue by DieserMerlin** [codetheweb/tuyapi#282]
Hey,

I can't get "tuya-cli list-app" working...

When I refresh the devices list inside of the App I get this error:
"Incorrect local timer, please correct it. 50502"

I installed the required certificate, restarted my Android Phone (Huawei Mate 20 Pro running EMUI 9.1 -> Android 9) and connected it to the wifi proxy. This happens on Windows (I allowed port 8001 and 8002 in the Windows Firewall) and on Linux (Elementary OS).

The certificate shows up under "trusted certificates" in my system settings.

What am I doing wrong?

**Comment by codetheweb** [comment]
https://github.com/codetheweb/tuyapi/issues/280#issuecomment-572233770

**Comment by DieserMerlin** [comment]
I'll try that, thank you!
