### ISSUE TITLE
Api and thermostat!

### ISSUE THREAD

**Issue by earlywaff** [codetheweb/tuyapi#283]
Tell me, is it possible to add a thermostat? It seems that soon the thuja will close the opportunity to sniff traffic and you will be the only salvation!
Sorry for my English, maybe there will be some mistakes)

**Comment by codetheweb** [comment]
We need more details to help.  Are you trying to control it through Tuya's cloud API or locally?

TuyAPI supports all WiFi Tuya devices, thermostats included.

**Comment by earlywaff** [comment]
How can I add my device to homebridge?

**Comment by codetheweb** [comment]
This is a popular Homebridge plugin: https://www.npmjs.com/package/homebridge-tuya-lan.
