### ISSUE TITLE
Step 5 of documentation

### ISSUE THREAD

**Issue by Jimud1** [codetheweb/tuyapi#286]
First off I'd like to thank you for your amazing work!

In regards to step 5
"On the command line, run something similar to node cli.js link --api-key <your api key> --api-secret <your api secret> --schema <your-schema/channel ID> --ssid <your WiFi name> --password <your WiFi password>."

I don't have the cli.js within my project, should I run npx @tuyapi/cli cli.js followed by the parameters?

**Comment by codetheweb** [comment]
Oops, thanks for the correction.  I just copy-pasted the command when writing the docs and forgot to change that part.  It's now updated.

The correct command is `tuya-cli link --api-key <your api key> --api-secret <your api secret> --schema <your-schema/channel ID> --ssid <your WiFi name> --password <your WiFi password>`.
