### ISSUE TITLE
Help with registering a device

### ISSUE THREAD

**Issue by mzdial** [codetheweb/tuyapi#294]
I'm new to all of this, but I'm getting stumped on this issue. I've followed the directions on how to "Linking a Tuya device with Smart Link"

➜  ~ tuya-cli link --ssid XXXXXX --password XXXXXX --api-key XXXXXX --api-secret XXXXXX --schema mzd_home -t America/Indiana/Indianapolis -r us --saveAPI -s -n
✖ Device(s) failed to be registered!
Error: sign invalid
    at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:68:31)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

I have both the bulb device RESET (flashing) and my laptop on the same network I'm trying to place it on in the command line string. Any ideas of what I'm doing wrong?

Thanks!
Matt

**Comment by codetheweb** [comment]
The sign invalid error is returned from Tuya's API and it most likely means that one of the API key/secret/schema is incorrect.

**Comment by mzdial** [comment]
Hmmm... I've cut/pasted them from the site. Just tested it again. I just created another development solution and left out the underscore from the schema (mzdhome2) and copied the iOS Appkey and the AppSecret. The schema should be the channel ID, correct? I've tried the package name as well -- and it errors the same. I'm stumped as I know the appkey/secret are correct, as well the schema!

Thanks!

**Comment by codetheweb** [comment]
Just to confirm, you copied the Cloud API auth information, **not** the iOS stuff the first time?

This is where you should be getting the API keys from:
![Screen Shot 2020-02-23 at 3 05 02 PM](https://user-images.githubusercontent.com/7410405/75119107-f8829780-564d-11ea-8a79-435f94c54ebd.png)

**Comment by mzdial** [comment]
Man.. I feel stupid.. :-)

You are correct.. I was pulling it from the App SDK, and not the Cloud API auth information. Thank you so much for straightening me out. Sheesh. Hopefully this helps someone else in the future from the bone-headed error!

Awesome.. Going to try this now (it appears to be waiting for me to link a device.)

**Comment by mzdial** [comment]
Cool! Just got my first device to register. Progress finally! :-)

**Comment by codetheweb** [comment]
👍
