### ISSUE TITLE
Add support for "sub devices"

### ISSUE THREAD

**Issue by Apollon77** [codetheweb/tuyapi#296]
One of my users now discióvered a device that seems to have sub devices ...
https://amzn.to/2Q1KeFD

This device allows to add IR controls. In fact the "IR sender" is then reported as one device. Each added IR control is afte rthat added as additional devices. These additional devices have set  the field "meshId" to the main device and do not have a localKey.

I still have no idea on how to control these exactly but I assume that you have one local TCP  connection to the main device and then send messages for all defined devioces over that connection. This would mean we need an enhancement for "send" method to allow sending for an other gwId then the one the connection has been created for ...

Is anyone knowing these devices already?

Details and logs: https://github.com/Apollon77/ioBroker.tuya/issues/139

**Comment by codetheweb** [comment]
I believe someone else has seen this type of thing before, although I can't remember what issue it was in.

TuyAPI will already let you control multiple devices as long as the method is consistent with what I've seen in the past.  The only config difference is that the `gwId` references the physical device's ID (the 'gateway' id) and the `devId` references the virtual device's ID.

**Comment by Apollon77** [comment]
Aahahh i see ... let me try it

**Comment by Apollon77** [comment]
Hm ... But one tuyaapi intance gets initialized with gwId and devId and IP and then opens a persistent connection to the device. All those devices only allow one connection. This means that I can only control one of those "sub-"devices at once. It might work well for the events because in the payload the data are seoarated clearly, but for set the method do not allow me to specify the devId for this command because it always uses the devId from the instance... 

https://github.com/codetheweb/tuyapi/blob/master/index.js#L131

Or do I oversee something?

**Comment by codetheweb** [comment]
You're correct.

Unfortunately, this is just a limitation of this library and can't really be fixed without an overhaul of the way it works.  I (foolishly) didn't design for the possibility of multiple virtual devices when first implementing it.

These are the kind of edge cases that I started [@tuyapi/driver](https://github.com/TuyaAPI/driver) to try and fix, although work on that has stalled because TuyAPI has seemed to be fairly stable and reliable for most use cases.

**Comment by codetheweb** [comment]
If I do get around to working on TuyAPI again, the next 'major version' (i.e. complete from-scratch rewrite) will probably be published under @tuyapi/driver, so marking this as wontfix for now.

**Comment by Apollon77** [comment]
:-( I could see a fast change: just add a parameter into the object from set Method to overwrite the devId which is sent? So allowing this in that version of the lib would be a fast thing ... but ok :-(

**Comment by codetheweb** [comment]
That's true I guess, just feels like a clunky interface.

I'm happy to accept a PR for it but I don't plan to add it ATM.

**Comment by Apollon77** [comment]
Will look into it (and yes it's a hack) the next days

**Comment by Apollon77** [comment]
@codetheweb Please see https://github.com/codetheweb/tuyapi/pull/298 ... you mean it that way?

**Comment by Apollon77** [comment]
@codetheweb I will hopefully get feedback if it works ... if then I would add a second PR to do the same for "get" :-( Sorry I missed that completely :-(

**Comment by Apollon77** [comment]
Hm ... it do not seem to work with the "set". The promise is not returning ... this would mean that the "_setResolver" is never called which means that no data is returned for that

**Comment by Apollon77** [comment]
Hm ... basically looks okish:

```
  TuyAPI SET Payload: +7s
  TuyAPI { devId: 'bf307c6bd128b74b15wij4',
  TuyAPI   gwId: '04314116ecfabc268901',
  TuyAPI   uid: '',
  TuyAPI   t: 1584710012,
  TuyAPI   dps: { '101': false } } +0ms
  TuyAPI Received data: 000055aa00000002000000070000000c0000000018cfc5da0000aa55 +38ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 7, sequenceN: 2 } +1ms
  TuyAPI Got SET ack. +1ms
  TuyAPI Pinging 192.168.2.106 +3s
  TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +31ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +0ms
  TuyAPI Pong from 192.168.2.106 +1ms```

so no "status" message is delivered after the change ... only the "ack"

**Comment by Apollon77** [comment]
any ideas? @kueblc @codetheweb

**Comment by kueblc** [comment]
Are you sure about the `dps`? Giving bad values for `dps` will still send `ack` but no change will be applied

**Comment by kueblc** [comment]
I don't have any device with sub devices so I can't test here. Have you added sub device functionality to `get` on your local instance? Can you shared the `schema` returned?

**Comment by Apollon77** [comment]
Schema see https://github.com/Apollon77/ioBroker.tuya/files/4359432/iobroker.2020-03-20.log ... no get was not changed so far ... just wanted to check "set" ;-) I also do not have that device with me ... its with one user :-(
I asked him if we couldf get it in an own tuya account to get access
