### ISSUE TITLE
Unreadable data returned  

### ISSUE THREAD

**Issue by louisvangeldrop** [codetheweb/tuyapi#297]
device = new TuyAPI({ id: 'bfd008ca31be4f556d3nbb', key: '************* })

device.on('data', (data) => console.log(deviceData = data))
    await device.find()
    await device.connect()
    deviceStatus = await device.get();

The data in deviceData contains:

3.3�;�������{���a��K�h����lܳG��x{	���S^m`X�

It is unreadable and I do not know how to handle it

**Comment by kueblc** [comment]
You need to set the version to 3.3

**Comment by louisvangeldrop** [comment]
I changed the code to: 
device = new TuyAPI({ id: 'bfd008ca31be4f556d3nbb', key: '****************', version: 3.3 })

Still the same result.

**Comment by kueblc** [comment]
Your key may be wrong then, can you confirm your `localKey`?

**Comment by louisvangeldrop** [comment]
I believe that the connection is ok.

![image](https://user-images.githubusercontent.com/10716245/76647177-90dcaf80-655c-11ea-974c-eeb97183f591.png)

**Comment by kueblc** [comment]
You can be connected and still have the wrong key, you should verify your `localKey`

**Comment by louisvangeldrop** [comment]
localkey is valid now ( used tuya-cli link output values), but now I get the message: json obj data unvalid

**Comment by codetheweb** [comment]
Probably related to https://github.com/codetheweb/tuyapi/issues/246.

If you're able @louisvangeldrop could you please try the Python implementation linked near the bottom of that thread?  If that works, then I might be able to fix TuyAPI by comparing our implementations.

**Comment by louisvangeldrop** [comment]
I am trying to get mqtt-script running. However something is going wrong. I am publishing the tuya/... topic, but the python-script doesn't show any output.

**Comment by codetheweb** [comment]
Try opening an issue at that repo if you're having problems with MQTT; I don't have any experience with it.

**Comment by louisvangeldrop** [comment]
This is what I receive from the python script ./tuya/__init__.py:
replies
['{"dps":{"3":255,"2"...85684597}']

**Comment by louisvangeldrop** [comment]
Scrreen picture:
![image](https://user-images.githubusercontent.com/10716245/78070045-6a5fa680-739b-11ea-86d8-854f727bc9d6.png)

**Comment by louisvangeldrop** [comment]
cmd:10 fails:

![image](https://user-images.githubusercontent.com/10716245/78070268-c9bdb680-739b-11ea-8055-16f4d62bd7fd.png)

**Comment by codetheweb** [comment]
I'm sorry, but since the Python version doesn't seem to be working as well there's not much else I can think to try at the moment. Please follow https://github.com/codetheweb/tuyapi/issues/246 for updates, as I'm pretty sure you're having the same issue.

What brand is this device?

**Comment by louisvangeldrop** [comment]
It is from the Action. Brandname is LSC Led Lamp. It is cheap (7,95 euro) and works very well.
