### ISSUE TITLE
Unable to get parameters with Chales

### ISSUE THREAD

**Issue by lollo0296** [codetheweb/tuyapi#3]
Hi together, 

I have a tuya smart plug and i am totally excited to integrate it in my homebridge configuration.

@codetheweb I have followed your SETUP.md but i can not get this POST request you are actually getting.

In my Charles after re-adding the device to my app i can see just this:
[https://imgur.com/a/F904M](url)
[https://imgur.com/a/jfJXa](url)

Can someone help me? 

Lorenzo.
(For reference you should invert point 4 and 5 of your guide)

**Comment by codetheweb** [comment]
@lollo0296 did you setup the SSL certificate on your phone?  Without adding it, Charles cannot decrypt the encrypted traffic between your phone and device.

**Comment by lollo0296** [comment]
@codetheweb thank you gor getting back so quickly.

Yes i did, you can take a look here https://imgur.com/a/Hm8Mz

Don’t know what is going on!
As I mentioned in the issue I wasn’t able to install the certificate before configuring the proxy on my iPhone, Charles website was having such an internal 404. 
I first configured the proxy, then I could install the certificate. That’s the reason for my suggestion to flip the order of point 4 and 5 on Setup.md.

**Comment by lollo0296** [comment]
Up! No one knows what the problem could be?

@codetheweb no ideas?

**Comment by codetheweb** [comment]
Sorry for not responding, I might have forgot about this 😛 .

Unfortunately, I don't really have any ideas.  I know you installed the certificate, but did you also [trust it](https://stackoverflow.com/a/43849537)?

**Comment by lollo0296** [comment]
That can happen everyone 😂

No, I actually didn’t!! I will give it a shot and let you know :)

**Comment by pierbiag** [comment]
FYI, apparently you now need to enable the proxying on each website for it to decrypt properly.
https://www.charlesproxy.com/documentation/faqs/ssl-changes/

**Comment by codetheweb** [comment]
@pierbiag I'll hopefully update the docs soon to include this.  Did you get your plug working?

**Comment by pierbiag** [comment]
I got the logger working but not the plug. In the end (without trying too much) I opened it up and reflashed the ESP8266 to use it with HomeAssistant.

**Comment by codetheweb** [comment]
Nice.  It's good to know at least that these can be easily reflashed.

**Comment by pierbiag** [comment]
yeah, they practically all use the same ESP board from Tuya. I found really good instructions on http://projects.nesrada.de/sm-pw701e/index.html and the official pinout from here: https://docs.tuya.com/en/hardware/WiFi-module/wifi-e3s-module.html
