### ISSUE TITLE
Cloud API Authorization has been upgraded to SaaS Development Platform

### ISSUE THREAD

**Issue by eslindsey** [codetheweb/tuyapi#303]
**Describe the bug**
Trying to follow the setup instructions, I get a message "Cloud API Authorization has been upgraded to SaaS Development Platform"

**To Reproduce**
1. Try to follow step 1 [here](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md#linking-a-tuya-device-with-smart-link)

**Expected behavior**
A few days ago, I did this, everything worked fine, and my request said it was pending.

**Debug Output**
Now, I get the message below:

**Screenshots**
![Screenshot](https://i.imgur.com/n9Y6IRv.png "Screenshot")

Is this going to affect my ability to use TuyAPI?

**Comment by Apollon77** [comment]
It at least sounds in  a directly that it could be over with "free developer accounts" :-( @kueblc @codetheweb

**Comment by vitramir** [comment]
This is the answer from their technical support

> Hi dear,after checking we found that you can apply for the OpenAPI directly.You can refer to the attached photo to create.

![f13aba41d1a9968e](https://user-images.githubusercontent.com/2134784/78144628-849b9200-7438-11ea-8d2d-6c41f32fa63b.png)


But I got Internal Server Error instead of SaaS Development page. What about you?

**Comment by eslindsey** [comment]
@vitramir I was able to create an application:

![Screenshot](https://i.imgur.com/zuMFEiP.png "Screenshot")

**Comment by codetheweb** [comment]
Just took a look and I don't think this should impact our ability to link devices.  I'll update the setup guide at some point within the next few days.

**Comment by vitramir** [comment]
@eslindsey You need SaaS Development section only to get credentials. SDK is in another tab.

**Comment by liuyigh** [comment]
So an enterprise certificate is required to get "SaaS development"? Is there any guidelines to get that "enterprise certificate"? or just simply apply?

**Comment by vitramir** [comment]
@liuyigh you don't need certificate to use OpenAPI. But I haven't try to make API calls yet :)

**Comment by liuyigh** [comment]
> @liuyigh you don't need certificate to use OpenAPI. But I haven't try to make API calls yet :)

Thanks for the encouragement. When I click SaaS Development, a popup box askes me to "upgrade my account". And there is no X button on that popup. I thought an upgrade is required. That's why I was asking.

It turns out that I just need to press `Esc` on my keybaord to close that pop up, LOL

Thanks!

**Comment by codetheweb** [comment]
Just updated setup instructions.
