### ISSUE TITLE
tuya-cli link times out at "Registering device(s).

### ISSUE THREAD

**Issue by celeritas0725** [codetheweb/tuyapi#308]
Still encountering the same error [here.](https://github.com/codetheweb/tuyapi/issues/287).
Tried connecting the LAN cable directly to router but to no avail. Any solutions?

I don't know what these mean but I have installed my sockets in SmartLife 

> This process is specific to each type of device, find instructions in the Tuya Smart app. Usually this consists of turning it on and off several times or holding down a button.

Note: I just removed the pertinent details, hence, seen with many blank spaces.

![Tuya1](https://user-images.githubusercontent.com/56512303/78895530-9b2d9300-7aa1-11ea-8169-9b9c46a5770c.png)
![Tuya2](https://user-images.githubusercontent.com/56512303/78895544-9e288380-7aa1-11ea-8ab0-4781167e1c2e.png)

**Comment by kueblc** [comment]
> I don't know what these mean but I have installed my sockets in SmartLife

`tuya-cli link` registers the device, you can't have it already registered in the app. You need to put the device back into pairing mode, which will remove them from SmartLife.

**Comment by celeritas0725** [comment]
> `tuya-cli link registers the device, you can't have it already registered in the app. You need to put the device back into pairing mode, which will remove them from SmartLife.

I have tested below scenarios but to no avail:
- execute the syntax and let it discover the SmartLife enrolled devices - failed
- execute the syntax after I have unenrolled the device in SmartLife
- execute the syntax after I have re-enrolled the unenrolled device in SmartLife
- execute the syntax after I have unenrolled the device in SmartLife and re-enrolled it by letting the server discover it

syntaxes used: SSID/PW has no '' and SSID/PW with ''
I have created a new SAAS but to no avail.

> This needs to be performed over WiFi, the smart sockets are WiFi only

I mean the laptop that I was using was directly connected to the modem. I have also tried that the laptop wherein I typed the syntax are connected via Wi-Fi. Smart Sockets were connected thru Wi-Fi

**Comment by codetheweb** [comment]
To be clear, have you run the command while your plugs are in pairing mode (main light is flashing) and your laptop is only connected to your network via WiFi?

**Comment by celeritas0725** [comment]
> To be clear, have you run the command while your plugs are in pairing mode (main light is flashing) and your laptop is only connected to your network via WiFi?

Yes, I have teied running the command while on pairing mode. That is scenario number 4. Term would have been "re-enrolling it by letting the server discover it"

For the next step in installation that I have posted, I am also using that method but to no avail

**Comment by dermodmaster** [comment]
same issue here running this on raspberry pi zero w

**Comment by codetheweb** [comment]
What brand are your devices? People have had issues in the past with Teckin devices, there may be similar issues with other brands as well.

**Comment by celeritas0725** [comment]
Mine doesn't have a brand but compatible with Smartlife and Tuya app

**Comment by vsaintloup** [comment]
Interesting, same problem here (Timed out waiting for devices to connect) with a Teckin bulb… spent all day trying ways to find the IDs and Keys of all my products… even moving my wired Raspberry on the same 2.4 GHz network and didn't help :(

**Comment by kalety** [comment]
Same here, I can't register devices through this method... :((

**Comment by kalety** [comment]
Yes!!! through a RPI no problems!! ThankS!!!

**Comment by vsaintloup** [comment]
I finally got it to work by changing my 2.4 GHz WiFi’s SSID for only one word (only letters), and same for the password! So no more nice and fancy Wifi network names for now ;)

**Comment by boby360** [comment]
I am also having issues. This is done in a local VM. SSID is one word. only letters. Device is in pairing mode. Connects fine to apps. Password is 14 characters so i hope thats not an issue. Network is a mixed 2.4ghz/5ghz although the device would only see 2.4ghz so that shouldn't be an issue.

Im assuming the only logical answer is the VM is at fault?

**Comment by codetheweb** [comment]
@boby360 you could try sniffing your WiFi network with a different device to make sure the packets are being broadcasted. I suspect a VM will only work if it has direct access to a physical WiFi adapter.

**Comment by iRayanKhan** [comment]
I too am having this issue. I have generic candle bulbs by "ChangM".

```
✖ Device(s) failed to be registered!
Error: sign invalid
    at OpenAPI._client.got_1.default.extend.hooks.afterResponse.response (/usr/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/link/node_modules/@tuyapi/openapi/dist/api.js:68:31)
    at EventEmitter.emitter.on (/usr/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Notes:
* Region is set to US
* Connected to Wi-Fi
* Only using 2.4Ghz Band
* In Pairing Mode
* Not connected to other apps

**Comment by Fintasys** [comment]
Having the same  issue
```
✖ Device(s) failed to be registered!
Error: Timed out waiting for devices to connect.
```
* Region is set to US
* Connected to Wi-Fi (2.4ghz)
* In Pairing Mode
* Not connected to other Apps

**Comment by codetheweb** [comment]
The sign invalid error is not related to this issue.  It just means that one of your API keys is wrong.  Please open a new issue @iRayanKhan if you continue to have problems.

**Comment by Sheryars** [comment]
`✖ Device(s) failed to be registered!
Error: Timed out waiting for devices to connect.
    at TuyaLinkWizard.linkDevice (/Users/sheryars/.npm-global/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/link/index.js:117:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async link (/Users/sheryars/.npm-global/lib/node_modules/@tuyapi/cli/lib/link.js:47:19)`

i am getting same error as above. any suggestions what to do. tried on 2 devices both get timed out

**Comment by bburke782** [comment]
I have had a similar issue, i.e. timeouts and simply not seeing the socket. However after much trial and error I found that after disabling the "Npcap Loopback Adapter" in devices (this is in Windows 10) that everything started to work correctly.

**Comment by codetheweb** [comment]
I added a [troubleshooting section](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md#troubleshooting) to the setup instructions, please let me know if it helps.

**Comment by Nurffe** [comment]
After fighting some time with raspi3 and raspi4 to register devices I booted up ubuntu 20.04 livelinux on random laptop, installed required packages and had no problems registering devices. Don't know why but raspi3 (jester) and raspi4 (buster) both failed with this - even when wlan was only active interface

Anyways just a tip what worked for me when raspis failed

**Comment by codetheweb** [comment]
I just added another setup method that should be much more reliable. Instead of using `tuya-cli link`, you link the devices from within the official app and then can print out the parameters.

For everyone in this thread who's having issues, please upgrade `tuya-cli` and [check it out](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md).

Closing this issue for now as there's not enough data currently to figure out what the differences are between Tuya's and my/@kueblc's implementation of smartlink (and at this point it may not be worth trying to fix it if there are problems).
