### ISSUE TITLE
SaaS missing

### ISSUE THREAD

**Issue by kalety** [codetheweb/tuyapi#309]
Hi!, I'm try follow the instructions, but I don't see the "Saas Development" in my nav menu...
![Captura de pantalla 2020-04-11 a las 19 06 07](https://user-images.githubusercontent.com/19465177/79050034-9bf03180-7c27-11ea-9e17-8de9ba283a1c.png)

**Comment by vitramir** [comment]
They renamed it into "Cloud Development"

**Comment by vitramir** [comment]
@codetheweb update the docs, please

**Comment by codetheweb** [comment]
Updated. You're free to make a PR in the future @vitramir 😉
