### ISSUE TITLE
It's possible link to Alexa?

### ISSUE THREAD

**Issue by kalety** [codetheweb/tuyapi#310]
Good Work!, It's possible link the device, using your method, to alexa?.

Thanks for your hard work!

**Comment by codetheweb** [comment]
I'm not quite clear on what you want to accomplish.  The Tuya Smart app already provides Alexa integration.

**Comment by kalety** [comment]
Sorry if I don’t explain... When you register a device with Tuya app, Alexa registers it too, and send you a notification that you can use with it. My question is, if we register a device with your method (cool), there are possibilities to register trough the Tuyapi that Alexa recognizes it.

Thank you for your hard and successfully work!!!

Health!!

**Comment by codetheweb** [comment]
At this time that's not possible.  Sorry.

You could [connect your device to HA](https://github.com/mileperhour/localtuya-homeassistant), then connect HA to Alexa instead.

**Comment by kalety** [comment]
Thanks!. I am using HB too, trough the Alexa HB plugin it's possible too.
Thanks again and health!!
