### ISSUE TITLE
Client side

### ISSUE THREAD

**Issue by andrewshep** [codetheweb/tuyapi#319]
Anyone know if this could operate client side - viz embedded in webpage?

Many thanks

**Comment by kueblc** [comment]
No. As far as I know, you cannot establish sockets on arbitrary ports from a web browser.

**Comment by andrewshep** [comment]
Thanks v. much Colin, rather what I feared. Oddly, the description of
tuyapi doesn't seem to mention the operational environment, I guess though
it's node.js.

Andrew S.
