### ISSUE TITLE
Add TypeScript type definitions 

### ISSUE THREAD

**Issue by grenewode** [codetheweb/tuyapi#320]
Currently, the project does not provide any type definitions, which makes it difficult to use in typescript projects. 

Since the project is already extensively commented with jsdoc comments, much of the work is already done. There are still places where updates will need to be made, but those should be largely trivial, just a matter of adding more jsdoc comments to provide type hints where typescript cannot infer types.

I'd be happy to work on this.

**Comment by codetheweb** [comment]
I'd love to have type definitions, go for it 👍.

**Comment by hwr7dd** [comment]
This would be super helpful if someone is able to work on this

**Comment by duncte123** [comment]
I would love to take on this issue if it's still available

**Comment by codetheweb** [comment]
Go for it 🙂
