### ISSUE TITLE
Not working with IR blaster

### ISSUE THREAD

**Issue by dragonpiper** [codetheweb/tuyapi#322]
Has anyone been able to get this working with an ir blaster, for example https://www.amazon.com/MOES-Controller-Infrared-Universal-Compatible/dp/B07QH1X7PX ?

I tried looking at the traffic but it's all encrypted now, and the commands sent by tuya-api only return { dwid, gwid } from the data event . Was hoping i could avoid flashing ?

**Comment by codetheweb** [comment]
#134, #296

Please search for existing issues in the future before opening a new one.

The TL;DR from the above issues is that nobody's gotten it to work with TuyAPI before, although flashing seems to work fine.
