### ISSUE TITLE
No output of ID and KEY

### ISSUE THREAD

**Issue by afca1988** [codetheweb/tuyapi#330]
I tried to retrieve the parameters from two Tuya smartplugs using the first explained method.
So far so good regarding the use of the tuya-cli link commands. 

I put the devices in pairing mode (fast blinking) then give the commands with the needed info. It is searching for devices. And it seem that they do connect to something. But the outcome in terminal is this: 

✖ Device(s) failed to be registered!
Error: Timed out waiting for devices to connect.
    at TuyaLinkWizard.linkDevice (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/link/index.js:117:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async link (/usr/local/lib/node_modules/@tuyapi/cli/lib/link.js:47:19)

So no output of any ID an KEY.

what am I doing wrong?

**Comment by codetheweb** [comment]
I recently added a `cloud list` command to `tuya-cli`, please try it and see if you can list your devices.

Ex: `tuya-cli cloud list --api-key ...`

**Comment by afca1988** [comment]
> I recently added a `cloud list` command to `tuya-cli`, please try it and see if you can list your devices.
> 
> Ex: `tuya-cli cloud list --api-key ...`

Doesn't help me further. now i get the following error: unknown option '--ssid'
I'm 100% sure that the credentials are correct

**Comment by codetheweb** [comment]
You don't need the SSID parameter:
```
➜ tuya-cli cloud list --help
Usage: tuya-cli cloud [options]

Options:
  --api-key [apiKey]        your tuya.com API key
  --api-secret [apiSecret]  your tuya.com API secret
  --schema <schema>         your tuya.com app identifier
  -r, --region [region]     the region closest to you from the following list: us=Americas, eu=Europe, cn=Asia (default: "us")
  -h, --help                output usage information
```

**Comment by afca1988** [comment]
> You don't need the SSID parameter:
> 
> ```
> ➜ tuya-cli cloud list --help
> Usage: tuya-cli cloud [options]
> 
> Options:
>   --api-key [apiKey]        your tuya.com API key
>   --api-secret [apiSecret]  your tuya.com API secret
>   --schema <schema>         your tuya.com app identifier
>   -r, --region [region]     the region closest to you from the following list: us=Americas, eu=Europe, cn=Asia (default: "us")
>   -h, --help                output usage information
> ```

I think I'll have to give up. I gave this commands: 
tuya-cli cloud --api-key (my api key) --api-secret (my api secret) --schema smartplugsnick --region eu

the next thing i get is: []
MacBook-Air-van-Nick:~ nicktoet$

**Comment by codetheweb** [comment]
That means that the devices were not successfully linked. Sometimes they link, but `tuya-cli` still times out.

We can continue debugging if you want. If not, feel free to close the issue.

I'm also planning to add [a new method](https://github.com/codetheweb/tuyapi/issues/323) to get device parameters in the near future that should be easier to use.

**Comment by paqpaqpaq** [comment]
I have the exact same issues here.
Did everything as described, but the device (rgb socket) is not connecting.  It connects perfectly via the app though.

**Comment by codetheweb** [comment]
#232
