### ISSUE TITLE
How to work out what tuya device expects?

### ISSUE THREAD

**Issue by WhatDoor** [codetheweb/tuyapi#331]
Thanks for writing this API, its been super helpful. 

I am currently able to control on/off, light warmth and brightness on my lightbulb through this API. But, I am not sure how to go about controlling its colour... 

How do I go about finding out what kind of input the device expects?

**Comment by codetheweb** [comment]
If you do a search across [old issues](https://github.com/codetheweb/tuyapi/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+) people have posted some example schemas.

[This](https://github.com/clach04/python-tuya/wiki/DeviceSchemas) might also help.
