### ISSUE TITLE
after registering smart power switch cannot register tuya-cli link --api-key ...

### ISSUE THREAD

**Issue by cdprince** [codetheweb/tuyapi#336]
**Describe the bug**
initially I was able to register my device, I then tried to reset the device into pairing/registering mode again and rerun the tuya-cli link command, but I could never get the device to register again.

**To Reproduce**
pi@raspberrypi:~ $ tuya-cli link --api-key <API Key / Access ID/Client ID> --api-secret <API secret / Access Secret/Client Secret>  --schema <Channel ID>  --ssid <myssid> --password <ssidpasswd> --region us
✔ Device(s) registered!
[ { id: '73328546dc4f********',
    ip: '73.158.133.86',
    localKey: '****************',
    name: 'Smart plug' } ]
Where the <Xn> represent strings of lower case letters and numbers.

I had great trouble using code I found on the fixed bug area (possibly another bug, possibly docs):
pi@raspberrypi:~/git/tuyapi $ DEBUG=* node app5.js 
/home/pi/git/tuyapi/app5.js:4
const device = new TuyAPI({
               ^
ReferenceError: TuyAPI is not defined
    at Object.<anonymous> (/home/pi/git/tuyapi/app5.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

pi@raspberrypi:~/git/tuyapi $ cat app5.js 
const device = new TuyAPI({
  id: '73328546dc4f22*******',
  key: '****************'});

// Find device on network
device.find().then(() => {
  // Connect to device
  device.connect();
});

...So I tried resetting the smart power switch device (using arrow up on linux terminal for command tuya-cli link ...), and could not connect afterward, I even ran with DEBUG=*:
DEBUG=* tuya-cli link --api-key ...
⠏ Registering devices(s)...  @tuyapi/link:wizard Token:  { region: 'AZ', secret: '6A4s', token: 'Jzkh5q8g' } +0ms
  @tuyapi/link:manual Sending SmartLink initialization packets +0ms
  @tuyapi/link:wizard Polling cloud for details on token... +14ms
⠹ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +243ms
⠴ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +202ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +195ms
⠋ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +243ms
⠸ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +232ms
⠴ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +175ms
⠇ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +268ms
⠋ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +170ms
⠸ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +179ms
⠼ Registering devices(s)...  @tuyapi/link:manual Sending SmartLink data packets +2s
⠴ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +189ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +329ms
⠧ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +611ms
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +205ms
⠴ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +457ms
⠙ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +531ms
⠼ Registering devices(s)...  @tuyapi/link:manual Finished sending packets. +3s
⠏ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +1s
⠹ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +264ms
⠼ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +171ms
⠦ Registering devices(s)...  @tuyapi/link:wizard 0 devices returned by API. +169ms

**Expected behavior**
I expected the device to be registered like the first time, but after many tries on two switches I cannot connect.

**Debug Output**
done

**Screenshots**
I am not that adept/too lazy, but can, if need be

**Desktop (please complete the following information):**
pi@raspberrypi:~/git/tuyapi $ node -v
v10.21.0
pi@raspberrypi:~/git/tuyapi $ npm -v
5.8.0
pi@raspberrypi:~/git/tuyapi $ uname -a
Linux raspberrypi 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux

**Additional context**
Possible additional context, after pushing the device pairing button (slow mode) I attempted registering, the device, the device stopped blinking and I then pressed the button again to get it into pairing mode slow blink, after the device acheived the slow blink state, I noticed that the device had registered -- this happened the first and only time the device registered. 

I am a noob at node js

**Comment by cdprince** [comment]
The power switch devices were Juoyou, one in a consumer box, the other came in an industrial box.
One I was able to connect in slow blinking mode to Smart Life, the other I connected to Brilliant in fast blinking mode (slow blink mode did not seem to work).

**Comment by cdprince** [comment]
I have gotten the other wifi power switch device up and I am able to modify its behavior programatically.
I thought I would investigate the non-registering device (NRD).
I tried nmap, I noticed that both devices used irc port 6668, so I used:
nmap 10.0.0.1-255 -p 6668
I found that only one device was on the network -- the working device.  I tried turning NRD on and off, then I unplugged it and then I had two devices with port 6668 on the network.
I decided to check if the old key was retained:
pi@raspberrypi:~/git/tuyapi $ DEBUG=* tuya-cli set --ip 10.0.0.232 --id 73328546dc4*******a0 --key ************* --dps 3 --set True
  TuyAPI IP and ID are already both resolved. +0ms
  TuyAPI Connecting to 10.0.0.232... +11ms
  TuyAPI Error event from socket. 10.0.0.232 { Error: connect ECONNREFUSED 10.0.0.232:6668
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '10.0.0.232',
  port: 6668 } +1s
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Error from socket
    at Socket.client.on.err (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/index.js:350:30)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Socket.client.on.err (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/index.js:350:16)
    at Socket.emit (events.js:198:13)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:63:19)

I am not sure if this is supposed to be the expected behavior, error message wise, but using the old key did not work, which I did expect.
I go to try and register my device again, but first decide to check nmap 
nmap 10.0.0.232 -p 6668
and it is not on the network. 
So I unplug and plug the device again and check nmap again.
While I am registering I have another terminal window open and use nmap and the device goes from 10.0.0.131, to 10.0.0.65
This looks like a hardware issue -- Feel free to say this is not a bug.

**Comment by codetheweb** [comment]
I'm a little confused on what you're reporting. (Also, it would be much easier to read if you used [code fences](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) for output/code.)

It's expected that re-registering gives the device a different key.

**Comment by codetheweb** [comment]
Let me know if this helps: https://github.com/codetheweb/tuyapi/issues/308#issuecomment-650643347.

**Comment by cdprince** [comment]
BTW -- using tuya-cli set ...  --set True 
now works for me for tuya-cli version 1.13.3.  Not sure what happened.  I guess I did not put the tuya-cli version down.
The versions (os, npm, tuya-cli) could be enhanced to output in DEBUG=* mode auto-magically (and I am not complaining).
This can now be closed as far as I am concerned -- Thanks!
