### ISSUE TITLE
Setup.MD -- Click 'Add App Account' and scan the QR code from your app -- scan?

### ISSUE THREAD

**Issue by cdprince** [codetheweb/tuyapi#339]
**Describe the bug**
After updating the code, I tried to scan the QR Code, from the tuya app on my phone and it brought me to a tuyaSmart--qrLogin?token=<token>

I went to the tuya-cli wizard 
and received the following prompts:
pi@raspberrypi:~ $ tuya-cli wizard
? The API key from tuya.com: 4qw3ccd**********d8
? The API secret from tuya.com 58c******************************e9
? Select the region closest to you: Americas
? Provide the ID of a device currently registered in the app: 733****************a0
There was an issue fetching that device. Make sure your account is linked and the ID is correct.

The tuya-cli wizard argument never asked for the tuyaSmart--qrLogin?token
I tried this several times, I also tried the DEBUG=* method, but it does not seem to work.

**Comment by codetheweb** [comment]
You should be scanning the code with the Tuya Smart app, not a camera app. Sorry if that wasn't clear.

I updated the docs: https://github.com/codetheweb/tuyapi/commit/06ebab40d9e5a79849d71465f18918fe52872a4c

Please let me know if you still have issues or if it works.

**Comment by cdprince** [comment]
works -- Thanks!
