### ISSUE TITLE
Device ID with tuya-cli wizard

### ISSUE THREAD

**Issue by celeritas0725** [codetheweb/tuyapi#340]
The command `tuya-cli wizard` is asking for the _Device ID_. May I know where can I get it?

These are the outputs when typing the command above:

```
? The API key from tuya.com: <I get this from https://iot.tuya.com/>
? The API secret from <I get this from https://iot.tuya.com/>
? Select the region closest to you: <I get this from the choices
? Provide the ID of a device currently registered in the app: < I tried the virtual ID and my email address used in SmartLife/Tuya app but to no avail>
```
ERROR:
There was an issue fetching that device. Make sure your account is linked and the ID is correct.

**Comment by raghavrithvik** [comment]
+1

**Comment by codetheweb** [comment]
The virtual ID is the correct input, I suppose that question could be more clear.
Just to confirm, your Tuya dashboard looks something like this?

<img width="1560" alt="Screen Shot 2020-06-28 at 3 58 31 PM" src="https://user-images.githubusercontent.com/7410405/85958047-4ee34800-b958-11ea-8600-2b3e311d2f8b.png">

**Comment by celeritas0725** [comment]
This is to confirm that the Tuya dashboard is the same as yours. 

![Screenshot_20200629_065629](https://user-images.githubusercontent.com/56512303/85960426-e5a21a00-b9d5-11ea-829f-ce49b91c6e0a.jpg)

**Comment by codetheweb** [comment]
Yeah, everything looks right.

Out of curiosity, what region are you in/did you select? I've only actually tested it with the Americas / U.S. (although that shouldn't make a difference). Unfortunately, Tuya's OpenAPI doesn't return very descriptive errors so it's kinda blind debugging at this point.

**Comment by raghavrithvik** [comment]
The following solved my problem.
I chose Europe as the region and it gave the ID and key of the device. Asia & Americas didn't work for me.
My region is India.

**Comment by celeritas0725** [comment]
I'm from Asia but it is not working. As recommended, I tried America and was able to get the ID and key. Will try later if the keys are working. Thank you for your assistance!

**Comment by codetheweb** [comment]
Interesting, glad it's working.

I just shipped an update to @tuyapi/cli in v1.13.2 that auto-selects the region (by trying all 3 until one works). Hopefully that makes it easier to use. I also updated the question text to ask for the virtual ID.

Thanks for the feedback!

Closing for now, if you continue to have issues with the region you can reply to this thread and I'll reopen it. Otherwise, please make a new issue for any new problems.

**Comment by davidgurr** [comment]
I'm getting the same problem, but with the latest version of tuyapi that doesn't prompt for region.

It simply waits a *long* time and then says "There was an issue fetching that device". I've triple-checked the API key, secret and virtual ID.

**Comment by codetheweb** [comment]
@davidgurr can you please open a new issue with the output of `DEBUG=* tuya-cli wizard`?
