### ISSUE TITLE
Compatibility list

### ISSUE THREAD

**Issue by StephanMeijer** [codetheweb/tuyapi#343]
**Describe the issue**
I would like to see a list of compatible devices. I am specifically interested in  the compatibility with *Denver SHP-100*.

**Comment by Apollon77** [comment]
Is this realiostic? Tuya protocol is used in some million devices ... ;-)

**Comment by codetheweb** [comment]
Yeah, I'm sorry but I don't see this happening. Apart from the fact that there's hundreds of different devices, we would also have to keep track of firmware versions for each device.
