### ISSUE TITLE
Data taking 10 minutes to update (get)

### ISSUE THREAD

**Issue by gusbmello** [codetheweb/tuyapi#347]
Hi, I'm having this strange issue when I use the API with my Smart Plug:

The data on TuyaSmart APP (voltage/power/current) is updated every 1-3 seconds, but when using tuyapi it is updated only every 10 minutes.

Is this normal? Am i doing something wrong?

Code:
![image](https://user-images.githubusercontent.com/12779243/89911327-ac112100-dbc7-11ea-9dc0-bb4c937ad283.png)

This is how the data looks after plotting a graph with Grafana:

![image](https://user-images.githubusercontent.com/12779243/89911031-563c7900-dbc7-11ea-8c08-a19790bcc24a.png)

**Comment by codetheweb** [comment]
That code looks correct. My guess is that the app is pulling cloud data, and the device doesn't send updates locally for some reason. You could confirm that theory by sniffing traffic between your device and the app.

**Comment by gusbmello** [comment]
Update:

If I stay with the APP open while tuyapi is running it starts to get update every read.

![image](https://user-images.githubusercontent.com/12779243/89940968-be538500-dbf0-11ea-9d42-20c541fdfcc1.png)
(16:24 -> 16:34)

@codetheweb I'll sniff the traffic and see if I find something, thanks!

**Comment by gusbmello** [comment]
Sorry for the delay..

I just confirmed what @codetheweb said, even if I am in the same network (LAN), the app is pulling data from the Cloud.

I did some sniffing too:

- without_app.pcap: packets between my Smart Plug and tuyapi (with 'TuyaSmart' APP closed, only getting updates every 10m)
- with_app.pcap: packets between my Smart Plug and tuyapi (with 'TuyaSmart' APP opened, getting update every read)
- data_app: packets between my phone and Tuya server

PS: Using the same code I posted August 11.

[sniff.zip](https://github.com/codetheweb/tuyapi/files/5138734/sniff.zip)

**Comment by codetheweb** [comment]
Interesting, thanks. Sounds like the app might be sending updates to the plug from the cloud API, which seems like a weird data flow but 🤷.

I'll close this for now, feel free to reopen if you have additional questions.
