### ISSUE TITLE
device.get() never returns 

### ISSUE THREAD

**Issue by charliebudd** [codetheweb/tuyapi#348]
On Executing the following script the code will execute untill device.get(). At this point the program will await seamingly for ever. 

```
const TuyAPI = require('tuyapi');

const device = new TuyAPI({
    id: '##############',
    ip: '##############',
    key: '##############'
});

(async () => {
    console.log("Finding device...")
    await device.find();

    console.log("Connecting to device...")
    await device.connect();

    console.log("Getting device status...")
    let status = await device.get();

    console.log(`Current status: ${status}.`);

    device.disconnect();
})();
```
I've isolated the traffic between my computer and the device using wire shark. After the initial traffic for the connection, It seams that every 10 seconds there are three packets shot back and forth. Ive included a screen shot of the network dump below. Red is my computers IP, green my devices. 

![network dump](https://user-images.githubusercontent.com/51247511/90820006-a1bdf800-e328-11ea-9e4b-b7a8b68104f5.png)

I know my device works with the tuya-cli which I believe is built off of this package so it should work. 

Thanks for any help.

**Comment by codetheweb** [comment]
The CLI package uses effectively [the exact same code](https://github.com/TuyaAPI/cli/blob/2445db65fb1e487c8ef1f9381de38ac0421b5508/lib/control.js#L45), so if it works with the CLI it should indeed work fine with that script.

The 3 packets you're seeing are probably heartbeat packets.

What's the full command you use with the CLI to fetch device state?

**Comment by charliebudd** [comment]
Okay Ive found the problem. I was going to open a PR but It depends how you want to solve it. 

Essentialy theres additional state change which happens inside the find method which is missed out on if you supply both the IP and the ID of the device. For me the protocol version is wrong by default. This is corrected inside the find method if I dont supply my IP or ID but by suppllying both the method early outs and does not update my protocol version. Needless to say this seams a bit perplexing from a user point of few to have it fail if supplying more correct information. 

The answer may well be "Then you should supply the correct protocol version" which I have seen in your documentation. But i believe it would be more robust and user freindly to detect thtis automatically. Maybe change the "find" method to "init" (as its not just finding the device) and perform the whole setup regardless of if both the ip and id are provided. The performance is potentially an issue as this could be skipped after the first time. But perhaps thats best left to developers to implement?

**Comment by codetheweb** [comment]
> Essentialy theres additional state change which happens inside the find method which is missed out on if you supply both the IP and the ID of the device.

This is intentional, it's assumed all details are correct if the IP and ID are both provided. I don't think any changes to TuyAPI's behavior are required.
