### ISSUE TITLE
Set up steps

### ISSUE THREAD

**Issue by andylee1199** [codetheweb/tuyapi#35]
Hello, I asked this question before but I didn't get any reply. I have installed homebridge-tuya-outlet, and I found the DevID but u don't know how to found the local key. Also, can you tell me what's the full steps that can put tuya into HomeKit?Thanks so much.

**Comment by codetheweb** [comment]
To get the local key, follow the instructions [here](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md).

For installing homebridge-tuya-outlet:
1. Run `npm i -g homebridge-tuya-outlet`
2. Add this to your Homebridge configuration file, replacing `devId` and `localKey`:
```
{
  "accessory": "TuyaOutlet",
  "name": "Tuya Outlet",
  "devId": "xxxxxxxxxxxxxxxxxxx",
  "localKey": "xxxxxxxxxxxxxxx"
}
```

3. If you're able, assign your device a static IP and add that to the configuration file.  This makes it more reliable for the time being.
4. Restart Homebridge.

**Comment by andylee1199** [comment]
Thanks so much
