### ISSUE TITLE
Access to Cloud Development is now restricted

### ISSUE THREAD

**Issue by kart-able** [codetheweb/tuyapi#350]
The interface has recently changed as Tuya apparently want to check if developers are actually working for a registered company. So that I have been unable to access the Cloud Development. 

But I could create an app and get an AppKey and an AppSecret (whether these are the expected ones?). The only info missing is the device key. I have a product ID, but the wizard refuses it (or the whole provided keys).

**Comment by codetheweb** [comment]
> The interface has recently changed as Tuya apparently want to check if developers are actually working for a registered company. So that I have been unable to access the Cloud Development.

Can you provide a screenshot of what's changed? It seems to still be working for me (although I didn't try making a new account).

> But I could create an app and get an AppKey and an AppSecret (whether these are the expected ones?). The only info missing is the device key. I have a product ID, but the wizard refuses it (or the whole provided keys).

Are you talking about the 'virtual ID' when using `tuya-cli wizard`? That value is found inside the TuyaSmart app.

**Comment by kart-able** [comment]
On access to Cloud development:
![Annotation 2020-08-31 010549](https://user-images.githubusercontent.com/36565550/91671388-82904900-eb26-11ea-977e-cf7beb922b7a.jpg)
After a click on "Verify" you must fill in a form with your account information which remains incomplete till your identity is not verified > enterprise must be authenticated:
![Annotation 2020-08-31 010457](https://user-images.githubusercontent.com/36565550/91671462-2bd73f00-eb27-11ea-8173-173d937298fc.jpg)

**Comment by codetheweb** [comment]
😕 I'm pretty tired of Tuya arbitrarily changing their requirements.
Hopefully people will be able to use the 3 month trial or whatever to get API credentials.

Thanks for the info.
