### ISSUE TITLE
Error: you don't have access to this API

### ISSUE THREAD

**Issue by waqas-ogc** [codetheweb/tuyapi#357]
I'm getting following  error when I try using tuya-cli link

Device(s) failed to be registered!
Error: you don't have access to this API

**Comment by codetheweb** [comment]
Can you try the solution in this issue and see if it works?
https://github.com/codetheweb/tuyapi/issues/351

If it does, I'll update the setup instructions.

**Comment by codetheweb** [comment]
Setup docs have been updated: https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md.

If you still have issues, feel free to reopen.

**Comment by waqas-ogc** [comment]
Hi after applying changes in "API Group" , I'm still getting same error. 
Please note that I'm using second method i.e. "Linking a Tuya device with Smart Link" because I don't want to use Tuya official App.

**Comment by codetheweb** [comment]
Other people have reported that you need to wait a bit after making those changes. Try again in a few hours?
