### ISSUE TITLE
Only 2 tuya devices

### ISSUE THREAD

**Issue by toulouzz** [codetheweb/tuyapi#359]
Hi,

I can only add 2 tuya devices.
The toher I add appeared to be "disconnected".

Is it normal ? How can i fix it ?

Thanks

Thomas

**Comment by codetheweb** [comment]
What do you mean by 'disconnected'?

Can you provide some debug logs?

**Comment by toulouzz** [comment]
Hi,

I mean that i can't connect to my devices.
I checked all the credentials, everything's correct and i can only access
at this 2.

Devices are the same for "Cube Chambre" and "Reveil" for example and i can
only connect to two of them.

Is there something i ve to do or i missed ?

[image: image.png]

Thks

Best

Thomas

**Comment by codetheweb** [comment]
The image didn't load, I assume because you replied by email.

Can you also provide links to the product pages for your devices?

**Comment by Apollon77** [comment]
No details,  no follow up infos. closing. Please reopen if still relevant and happening with most recent versions.
