### ISSUE TITLE
Keep getting ECONNREFUSED when trying to connect

### ISSUE THREAD

**Issue by joopklepzeiker** [codetheweb/tuyapi#360]
I keep getting the ECONNREFUSED error when I try to connect to the light bulb. I have resolved the key with `tuya-cli wizard`
but I can't connect to it.

This is the full log I get:
`PS C:\Users\kevin\Desktop\Verrassing> node index.js
  TuyAPI IP and ID are already both resolved. +0ms
  TuyAPI Connecting to ip... +2ms
  TuyAPI Error event from socket. ip Error: connect ECONNREFUSEDip:6668
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: 'ip',
  port: 6668
} +2s
Error! Error: Error from socket
    at Socket.<anonymous> (C:\Users\kevin\Desktop\Verrassing\node_modules\tuyapi\index.js:351:30)
    at Socket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
  TuyAPI Socket closed: ip +16ms
Disconnected from device.
PS C:\Users\kevin\Desktop\Verrassing> `

**Comment by codetheweb** [comment]
That looks like your public IP rather than the local IP of the device. The local IP probably starts with `192.` or `10.`.

**Comment by joopklepzeiker** [comment]
Damnn that's stupid of me. How do I get the local ip of the device? I thought that was the one in the app

**Comment by joopklepzeiker** [comment]
Looks like my desktop can't find the device, laptop finds it by the id en key. Thanks you!

**Comment by codetheweb** [comment]
Glad you got it working.
If you want to hard-encode the IP in your script, the debug output should print the IP when finding the device.
