### ISSUE TITLE
[UPDATE] Important Update to SETUP.md

### ISSUE THREAD

**Issue by SPDurkee** [codetheweb/tuyapi#362]
I feel this small nugget of information is really important to help a lot of people trying to get their device keys.

The "Listing Tuya devices from the app" method also works for the "Smart Life" app. Because a lot of people use the Smart Life app, I think it should be noted (maybe bolded).

All devices that you want to use must be registered in the Tuya Smart app
shoud change to
All devices that you want to use must be registered in the **Tuya Smart** or **Smart Life** apps

**Comment by codetheweb** [comment]
👍 happy to accept a PR for this.

**Comment by SPDurkee** [comment]
PR created #364

**Comment by codetheweb** [comment]
Closed by #365.
