### ISSUE TITLE
socket.timeout: timed out

### ISSUE THREAD

**Issue by MrBuushy** [codetheweb/tuyapi#367]
Error:
line 4, in <module>
    data = d.status()
  File "C:\Users\Diaboli Sica\AppData\Local\Programs\Python\Python37\lib\site-packages\pytuya\__init__.py", line 279, in status
    data = self._send_receive(payload)
  File "C:\Users\Diaboli Sica\AppData\Local\Programs\Python\Python37\lib\site-packages\pytuya\__init__.py", line 175, in _send_receive
    s.connect((self.address, self.port))
socket.timeout: timed out

Code:
import pytuya

d = pytuya.OutletDevice('xxxxx', 'xxxxx', 'xxxxx')
data = d.status()

Questions:
1) Is there any way to use ethernet instead of wifi?
2) When using wifi, does the light bulb have to be near to the pc?
3) Can I have my phone near the light and let my pc control the light over the internet using the phone as a connector?

**Comment by kueblc** [comment]
Looks like you're looking for [python-tuya](https://github.com/clach04/python-tuya), not tuyapi, a JS library.

**Comment by MrBuushy** [comment]
Oh ok. I thought to put it here because it looked like python-tuya was dead.
