### ISSUE TITLE
Add app account from iot.tuya.com returns "Unknown error. Failed to log in" when scanning QR code

### ISSUE THREAD

**Issue by rstoks** [codetheweb/tuyapi#368]
Add app account from iot.tuya.com returns "Unknown error. Failed to log in" when scanning QR code. 
Any help would be appreciated, thanks!

**Comment by JC38** [comment]
Same problem here with both apps, Tuya App and Smart Life on Android

![image](https://user-images.githubusercontent.com/16527222/96368952-3f7e4980-1157-11eb-91b3-23f4a464e83a.png)

**Comment by codetheweb** [comment]
I just tried on iOS and it worked fine for me. It looks like they might have been [updating their services](https://github.com/codetheweb/tuyapi/issues/369); can you try again?

**Comment by rstoks** [comment]
> I just tried on iOS and it worked fine for me. It looks like they might have been [updating their services](https://github.com/codetheweb/tuyapi/issues/369); can you try again?

It works! Thanks guys,
