### ISSUE TITLE
Stuck at the First Step of Getting Keys at IoT.Tuya.com

### ISSUE THREAD

**Issue by yasurok** [codetheweb/tuyapi#369]
Maybe I am missing something big, but it seems I am stuck at the very first step of [getting necessary keys and stuff at iot.tuya.com](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md).

It reads:

> 1. Create a new account on iot.tuya.com and make sure you are logged in. Click "Cloud Development" in the top nav bar and click "Create". After you've created a new project, click into it. The access ID and access key are equivalent to the API key and API secret values need in step 6.

However, this is the screen I get when I click on "Cloud Development." I do not see any "Create" button anywhere.
![Tuya-Cloud-Development](https://user-images.githubusercontent.com/63393644/96363751-110d6800-1171-11eb-8e1e-0f300741d3d4.png)

I could start a free trial, but [the "Membership" page](https://developer.tuya.com/en/docs/iot/open-api/quick-start/membership-service) says:
> If you enable the Cloud Development Platform service after it was officially launched on July 16, 2020, you can apply for 3-month free trial. The free trial period starts from the application time.

and also
>Q: What happens if the free trial period expires or the membership expires?
>
> After the free trial period expires or the membership expires, you cannot continue to use the relevant open capabilities of the Cloud Development Platform. For example, you cannot request API operations or receive device messages.

Does this mean that I will not be able to get the keys and use them with TuyAPI for free on the (semi-)permanent basis?

Masters and gurus, please enlighten me.

Humbly,
Yasuro

P. S. Just so you know, I have no plan of directly using TuyAPI. I just want to use custom nodes for Node-RED that use TuyAPI, e.g., [node-red-contrib-tuya-smart-device](https://flows.nodered.org/node/node-red-contrib-tuya-smart-device).

**Comment by codetheweb** [comment]
Someone else recently reported the [same thing](https://github.com/codetheweb/tuyapi/issues/350). I believe that if the trial expires you can re-apply / make a different account. 
Obviously not ideal, but I don't think there's anything I can do unfortunately.

**Comment by yuto-ktok** [comment]
I had the same trouble and I fixed this trouble when I recreate my account.
(Maybe, it's Tuya site trouble...)

**Comment by yasurok** [comment]
> I had the same trouble and I fixed this trouble when I recreate my account.

Indeed I could too! Thanks for the info!
