### ISSUE TITLE
help to install 

### ISSUE THREAD

**Issue by userMak** [codetheweb/tuyapi#371]
Hi 
I am following these instructions
`This method is fast and easy. If you're having trouble manually linking your device with the below method, we recommend you try this. All devices that you want to use must be registered in either the Tuya Smart app or the Smart Life app.

Follow steps 1 through 4 from the "Linking a Tuya device with Smart Link" method below.
Click on "Cloud Development" in the top nav bar and click the project you created earlier. Under "Device Management" click "Linked Device" on the left side. Click the "Linked Devices by App Account" tab.
Click "Add App Account" and scan the QR code from your smart phone/tablet app by going to the 'Me' tab in the app, and tapping a QR code / Scan button in the upper right. Your account will now be linked.
On the command line, run tuya-cli wizard. It will prompt you for required information, and will then list out all your device names, IDs, and keys for use with TuyAPI. Copy and save this information to a safe place for later reference.`

in the cli asks me the following
`makis@makis-NUC7PJYH:~$ tuya-cli wizard
? The API key from tuya.com: ok
? The API secret from tuya.com ok
? Provide a 'virtual ID' of a device currently registered in the app:`

Where is the virual ID?

**Comment by codetheweb** [comment]
The virtual ID can be found by pushing the edit button on a device in the app (upper right corner), then selecting 'Device Information'.

**Comment by userMak** [comment]
> The virtual ID can be found by pushing the edit button on a device in the app (upper right corner), then selecting 'Device Information'.

sorry, can you give a screenshot please?

**Comment by userMak** [comment]
> > The virtual ID can be found by pushing the edit button on a device in the app (upper right corner), then selecting 'Device Information'.
> 
> sorry, can you give a screenshot please?

ok I see - in the tuya app. I fund it - thanks!
