### ISSUE TITLE
When registering devices: Error: you don't have access to this API

### ISSUE THREAD

**Issue by shoukolate** [codetheweb/tuyapi#373]
✖ Device(s) failed to be registered!
Error: you don't have access to this API
    at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/link/node_modules/@tuyapi/openapi/dist/api.js:68:31)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by codetheweb** [comment]
It looks like you might have missed this step:
> On the same page, click "API Group" on the left side. Change the status to Open for the following three API Groups by clicking "Apply" for each line, entering any reason, and clicking "OK": "Authorization Management", "Device Management", and "Device Control".

You might also have to wait for a few minutes after doing that for it to work.

**Comment by brushj** [comment]
Getting the same error with those options enabled from two different raspberry pi's. Wanted to make sure it wasn't just the first pi I loaded it on. It's been a few hours since I enabled them

> ✖ Device(s) failed to be registered!
Error: you don't have access to this API
    at OpenAPI._client.got_1.default.extend.hooks.afterResponse.response (/opt/nodejs/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/link/node_modules/@tuyapi/openapi/dist/api.js:68:31)
    at EventEmitter.emitter.on (/opt/nodejs/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)

<img width="1413" alt="Screen Shot 2020-10-30 at 3 40 22 PM" src="https://user-images.githubusercontent.com/11650838/97750265-d4bdfe00-1ac6-11eb-935e-1c2866db12c9.png">

**Comment by adraffy** [comment]
@brushj did you have any luck with this?  I'm stuck at the same step.

**Comment by brushj** [comment]
@adraffy I tried creating a new app last night just to verify and had no luck with that one last night. I just tried both out again, it has been over 24 hours for the first app, and still no go. same error:
>Error: you don't have access to this API

**Comment by adraffy** [comment]
I traced the API calls and noticed that getToken() was setting up some temporary user, so I also enabled: "User Management", "Network Management", "Data Service" and "Device Statistics".  Unsure if any of that helped.

Unfortunately, I did all this work, and them device I have Teckin SP-20, doesn't seem to report any energy data, I just get { dps: { '1': true, '9': 0 } }, which seems to be 1=on/off, 9=timer :(  

What Tuya device are you trying to access?

**Comment by brushj** [comment]
I have some TreatLife bulbs that I was trying to control. I was able to get everything by adding them through the App Account, but that defeats the purpose of trying to run it locally imo.

**Comment by brushj** [comment]
@adraffy after opening those additional items to the API Group and giving it 10 minutes I am able to register the bulbs now.

**Comment by codetheweb** [comment]
Glad you figured it out. Thanks @brushj for the PR.
