### ISSUE TITLE
Timeout waiting for status response from device

### ISSUE THREAD

**Issue by Natguillet** [codetheweb/tuyapi#374]
Hello,
I can easily connect to my device and retrieve its data but when I set the data, I always get this Timeout error.

My code is the same as in the example with a change to put '20' instead of '1' in the dps data.

I want to control these [lights](https://www.amazon.com/gp/product/B083WBLG3J/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1). 
I use the app Smart Life.

LOG:
`Connected to device
Data from device:  { devId: 'xxxxxxxxxxxxxxxxx',
  dps:
   { '20': false,
     '21': 'colour',
     '22': 1000,
     '23': 1000,
     '24': '00de03e803e8',
     '25':
      '06464601000003e803e800000000464601007803e803e80000000046460100f003e803e800000000',
     '26': 0 } }
Boolean status of default property: false.
Error! Timeout waiting for status response from device id: xxxxxxxxxxxxxxxxx
Disconnected from device.`

Desktop:**
 - OS: Windows 10
 - Node Version: 10.19.0

I hope I have given all the necessary information, thank you in advance for your help.

**Comment by bilange** [comment]
Hello, 

I am on the same boat (note that I am not experienced on this project), however I did these steps to get to the same timeout: 

- Did the whole setup instructions page, complete with my devices onboarding on my custom API access. Devices DID work with tuyapi without issues during that phase (while under my API access).
- Once I registered my device back onto the official Tuya app, I started having "Error! Timeout waiting for status response from device id: xxx". This still holds true after killing the app on the smartphone (as the Notes section said)
- Natguillet: I have an impression (and I'll let more experienced developers here confirm or deny) that changing APIs might cause our common issue. Were you switching APIs between the official app and your own account? You didn't specify in your original post.

**Comment by codetheweb** [comment]
@bilange device auth settings will change when re-registering. That's probably why the API is erroring out.

@Natguillet can you post the output with debug turned on (`DEBUG=* node script.js`)?

**Comment by Fabian-Ser** [comment]
Same error over here:
```
(node:13216) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Timeout waiting for status response from device id: xxxx')
    at TuyaDevice.emit (events.js:199:17)
    at E:\Path\to\the\node_modules\tuyapi\index.js:251:12
    at Timeout._onTimeout (E:\Path\to\the\node_modules\p-timeout\index.js:25:13)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:13216) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by Fabian-Ser** [comment]
Debugged output:                                                                                                                                                             `TuyAPI IP and ID are already both resolved. +0ms                                                                                                                                            TuyAPI Connecting to 192.168.2.12... +12ms                                                                                                                                                  TuyAPI Socket connected. +13ms                                                                                                                                                                                                                                                                                                                                                TuyaDevice {                                                                                                                                                                                    _events: [Object: null prototype] { connected: [Function] },                                                                                                                                  _eventsCount: 1,                                                                                                                                                                              _maxListeners: undefined,                                                                                                                                                                     device: {                                                                                                                                                                                       ip: '192.168.2.12',                                                                                                                                                                           port: 6668,                                                                                                                                                                                   id: '6cca4b3266982d41fdkeou',                                                                                                                                                                 gwID: '6cca4b3266982d41fdkeou',                                                                                                                                                               key: '2386f2cbc6339599',                                                                                                                                                                      productKey: undefined,                                                                                                                                                                        version: 3.1,                                                                                                                                                                                 parser: MessageParser {                                                                                                                                                                         version: '3.1',                                                                                                                                                                               cipher: [TuyaCipher],                                                                                                                                                                         key: '2386f2cbc6339599'                                                                                                                                                                     }                                                                                                                                                                                           },                                                                                                                                                                                            nullPayloadOnJSONError: false,                                                                                                                                                                foundDevices: [],                                                                                                                                                                             _connected: true,                                                                                                                                                                             _responseTimeout: 2,                                                                                                                                                                          _connectTimeout: 5,                                                                                                                                                                           _pingPongPeriod: 10,                                                                                                                                                                          _currentSequenceN: 0,                                                                                                                                                                         _resolvers: {},                                                                                                                                                                               _setQueue: PQueue {                                                                                                                                                                             _events: Events <[Object: null prototype] {}> {},                                                                                                                                             _eventsCount: 0,                                                                                                                                                                              _intervalCount: 0,                                                                                                                                                                            _intervalEnd: 0,                                                                                                                                                                              _pendingCount: 0,                                                                                                                                                                             _resolveEmpty: [Function: empty],                                                                                                                                                             _resolveIdle: [Function: empty],                                                                                                                                                              _carryoverConcurrencyCount: false,                                                                                                                                                            _isIntervalIgnored: true,                                                                                                                                                                     _intervalCap: Infinity,                                                                                                                                                                       _interval: 0,                                                                                                                                                                                 _queue: PriorityQueue { _queue: [] },                                                                                                                                                         _queueClass: [Function: PriorityQueue],                                                                                                                                                       _concurrency: 1,                                                                                                                                                                              _intervalId: undefined,                                                                                                                                                                       _timeout: undefined,                                                                                                                                                                          _throwOnTimeout: false,                                                                                                                                                                       _isPaused: false                                                                                                                                                                            },                                                                                                                                                                                            client: Socket {                                                                                                                                                                                connecting: false,                                                                                                                                                                            _hadError: false,                                                                                                                                                                             _parent: null,                                                                                                                                                                                _host: null,                                                                                                                                                                                  _readableState: ReadableState {                                                                                                                                                                 objectMode: false,                                                                                                                                                                            highWaterMark: 16384,                                                                                                                                                                         buffer: BufferList { head: null, tail: null, length: 0 },                                                                                                                                     length: 0,                                                                                                                                                                                    pipes: null,                                                                                                                                                                                  pipesCount: 0,                                                                                                                                                                                flowing: true,                                                                                                                                                                                ended: false,                                                                                                                                                                                 endEmitted: false,                                                                                                                                                                            reading: true,                                                                                                                                                                                sync: false,                                                                                                                                                                                  needReadable: true,                                                                                                                                                                           emittedReadable: false,                                                                                                                                                                       readableListening: false,                                                                                                                                                                     resumeScheduled: false,                                                                                                                                                                       paused: false,                                                                                                                                                                                emitClose: false,                                                                                                                                                                             autoDestroy: false,                                                                                                                                                                           destroyed: false,                                                                                                                                                                             defaultEncoding: 'utf8',                                                                                                                                                                      awaitDrain: 0,                                                                                                                                                                                readingMore: false,                                                                                                                                                                           decoder: null,                                                                                                                                                                                encoding: null                                                                                                                                                                              },                                                                                                                                                                                            readable: true,                                                                                                                                                                               _events: [Object: null prototype] {                                                                                                                                                             end: [Function: onReadableStreamEnd],                                                                                                                                                         timeout: [Function],                                                                                                                                                                          data: [Function],                                                                                                                                                                             error: [Function],                                                                                                                                                                            close: [Function],                                                                                                                                                                            connect: [Array]                                                                                                                                                                            },                                                                                                                                                                                            _eventsCount: 6,                                                                                                                                                                              _maxListeners: undefined,                                                                                                                                                                     _writableState: WritableState {                                                                                                                                                                 objectMode: false,                                                                                                                                                                            highWaterMark: 16384,                                                                                                                                                                         finalCalled: false,                                                                                                                                                                           needDrain: false,                                                                                                                                                                             ending: false,                                                                                                                                                                                ended: false,                                                                                                                                                                                 finished: false,                                                                                                                                                                              destroyed: false,                                                                                                                                                                             decodeStrings: false,                                                                                                                                                                         defaultEncoding: 'utf8',                                                                                                                                                                      length: 0,                                                                                                                                                                                    writing: false,                                                                                                                                                                               corked: 0,                                                                                                                                                                                    sync: true,                                                                                                                                                                                   bufferProcessing: false,                                                                                                                                                                      onwrite: [Function: bound onwrite],                                                                                                                                                           writecb: null,                                                                                                                                                                                writelen: 0,                                                                                                                                                                                  bufferedRequest: null,                                                                                                                                                                        lastBufferedRequest: null,                                                                                                                                                                    pendingcb: 0,                                                                                                                                                                                 prefinished: false,                                                                                                                                                                           errorEmitted: false,                                                                                                                                                                          emitClose: false,                                                                                                                                                                             autoDestroy: false,                                                                                                                                                                           bufferedRequestCount: 0,                                                                                                                                                                      corkedRequestsFree: [Object]                                                                                                                                                                },                                                                                                                                                                                            writable: true,                                                                                                                                                                               allowHalfOpen: false,                                                                                                                                                                         _sockname: null,                                                                                                                                                                              _pendingData: null,                                                                                                                                                                           _pendingEncoding: '',                                                                                                                                                                         server: null,                                                                                                                                                                                 _server: null,                                                                                                                                                                                timeout: 0,                                                                                                                                                                                   [Symbol(asyncId)]: 57,                                                                                                                                                                        [Symbol(kHandle)]: TCP {                                                                                                                                                                        reading: false,                                                                                                                                                                               onconnection: null,                                                                                                                                                                           [Symbol(owner)]: [Circular]                                                                                                                                                                 },                                                                                                                                                                                            [Symbol(lastWriteQueueSize)]: 0,                                                                                                                                                              [Symbol(timeout)]: Timeout {                                                                                                                                                                    _idleTimeout: -1,                                                                                                                                                                             _idlePrev: null,                                                                                                                                                                              _idleNext: null,                                                                                                                                                                              _idleStart: 1041,                                                                                                                                                                             _onTimeout: null,                                                                                                                                                                             _timerArgs: undefined,                                                                                                                                                                        _repeat: null,                                                                                                                                                                                _destroyed: true,                                                                                                                                                                             [Symbol(refed)]: null,                                                                                                                                                                        [Symbol(asyncId)]: 59,                                                                                                                                                                        [Symbol(triggerId)]: 0                                                                                                                                                                      },                                                                                                                                                                                            [Symbol(kBuffer)]: null,                                                                                                                                                                      [Symbol(kBufferCb)]: null,                                                                                                                                                                    [Symbol(kBufferGen)]: null,                                                                                                                                                                   [Symbol(kBytesRead)]: 0,                                                                                                                                                                      [Symbol(kBytesWritten)]: 0                                                                                                                                                                  }                                                                                                                                                                                           }                                                                                                                                                                                               TuyAPI GET Payload: +38ms                                                                                                                                                                     TuyAPI {                                                                                                                                                                                      TuyAPI   gwId: '6cca4b3266982d41fdkeou',                                                                                                                                                      TuyAPI   devId: '6cca4b3266982d41fdkeou',                                                                                                                                                     TuyAPI   t: '1604919378',                                                                                                                                                                     TuyAPI   dps: {},                                                                                                                                                                             TuyAPI   uid: '6cca4b3266982d41fdkeou'                                                                                                                                                        TuyAPI } +0ms                                                                                                                                                                                 TuyAPI Received data: 000055aa000000010000000a0000002c00000001e6506e3e0dfc3195d58643c9b6b22779ef9b124ddf16ada11cc7baf26aa0df78db96f09e0000aa55 +27ms                                          TuyAPI Parsed: +4ms                                                                                                                                                                           TuyAPI {                                                                                                                                                                                      TuyAPI   payload: "�Pn>\r�1�ՆCɶ�'y�\u0012M�\u0016��\u001cǺ�j��x",                                                                                                                             TuyAPI   leftover: false,                                                                                                                                                                     TuyAPI   commandByte: 10,                                                                                                                                                                     TuyAPI   sequenceN: 1                                                                                                                                                                         TuyAPI } +2ms                                                                                                                                                                               2                                                                                                                                                                                               TuyAPI SET Payload: +3s                                                                                                                                                                       TuyAPI {                                                                                                                                                                                      TuyAPI   devId: '6cca4b3266982d41fdkeou',                                                                                                                                                     TuyAPI   gwId: '6cca4b3266982d41fdkeou',                                                                                                                                                      TuyAPI   uid: '',                                                                                                                                                                             TuyAPI   t: 1604919381,                                                                                                                                                                       TuyAPI   dps: { '1': false }                                                                                                                                                                  TuyAPI } +3ms                                                                                                                                                                                 TuyAPI Received data: 000055aa00000002000000070000002c00000001e6506e3e0dfc3195d58643c9b6b22779ef9b124ddf16ada11cc7baf26aa0df78378ecca00000aa55 +24ms                                          TuyAPI Parsed: +5ms                                                                                                                                                                           TuyAPI {                                                                                                                                                                                      TuyAPI   payload: "�Pn>\r�1�ՆCɶ�'y�\u0012M�\u0016��\u001cǺ�j��x",                                                                                                                             TuyAPI   leftover: false,                                                                                                                                                                     TuyAPI   commandByte: 7,                                                                                                                                                                      TuyAPI   sequenceN: 2                                                                                                                                                                         TuyAPI } +1ms                                                                                                                                                                               (node:13216) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Timeout waiting for status response from device id: xxxx')
    at TuyaDevice.emit (events.js:199:17)
    at E:\Path\to\the\node_modules\tuyapi\index.js:251:12
    at Timeout._onTimeout (E:\Path\to\the\node_modules\p-timeout\index.js:25:13)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:13216) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
TuyAPI Pinging 192.168.2.12 +7s                                                                                                                                                               TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +9ms                                                                                                           TuyAPI Parsed: +2ms                                                                                                                                                                           TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +1ms                                                                                                                 TuyAPI Pong from 192.168.2.12 +4ms                                                                                                                                                            TuyAPI Pinging 192.168.2.12 +10s                                                                                                                                                              TuyAPI Received data: 000055aa00000000000000090000000c00000000b051ab030000aa55 +11ms                                                                                                          TuyAPI Parsed: +3ms                                                                                                                                                                           TuyAPI { payload: false, leftover: false, commandByte: 9, sequenceN: 0 } +1ms                                                                                                                 TuyAPI Pong from 192.168.2.12 +2m`

**Comment by codetheweb** [comment]
@Fabian-Ser it's a bit hard to read since the line breaks are omitted.
I believe your device uses the 3.3 protocol, given that it responds to the GET request with an encrypted packet. Try passing `{...version: 3.3}` in the constructor and see if that works.

**Comment by Fabian-Ser** [comment]
Hi @codetheweb thanks for the reply. 

I got the same error while adding version 3.3 to it:

> TuyaDevice {
  _events: [Object: null prototype] { connected: [Function] },
  _eventsCount: 1,
  _maxListeners: undefined,
  device: {
    ip: '192.168.2.12',
    port: 6668,
    id: '6cca4b3266982d41fdkeou',
    gwID: '6cca4b3266982d41fdkeou',
    key: '2386f2cbc6339599',
    productKey: 'keyuh8u8nhvwfs9t',
    version: '3.3',
    parser: MessageParser {
      version: '3.3',
      cipher: [TuyaCipher],
      key: '2386f2cbc6339599'
    }
  },
  nullPayloadOnJSONError: false,
  foundDevices: [ { id: '6cca4b3266982d41fdkeou', ip: '192.168.2.12' } ],
  _connected: true,
  _responseTimeout: 2,
  _connectTimeout: 5,
  _pingPongPeriod: 10,
  _currentSequenceN: 0,
  _resolvers: {},
  _setQueue: PQueue {
    _events: Events <[Object: null prototype] {}> {},
    _eventsCount: 0,
    _intervalCount: 0,
    _intervalEnd: 0,
    _pendingCount: 0,
    _resolveEmpty: [Function: empty],
    _resolveIdle: [Function: empty],
    _carryoverConcurrencyCount: false,
    _isIntervalIgnored: true,
    _intervalCap: Infinity,
    _interval: 0,
    _queue: PriorityQueue { _queue: [] },
    _queueClass: [Function: PriorityQueue],
    _concurrency: 1,
    _intervalId: undefined,
    _timeout: undefined,
    _throwOnTimeout: false,
    _isPaused: false
  },
  client: Socket {
    connecting: false,
    _hadError: false,
    _parent: null,
    _host: null,
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      paused: false,
      emitClose: false,
      autoDestroy: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: true,
    _events: [Object: null prototype] {
      end: [Function: onReadableStreamEnd],
      timeout: [Function],
      data: [Function],
      error: [Function],
      close: [Function],
      connect: [Array]
    },
    _eventsCount: 6,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: false,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: false,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: true,
    allowHalfOpen: false,
    _sockname: null,
    _pendingData: null,
    _pendingEncoding: '',
    server: null,
    _server: null,
    timeout: 0,
    [Symbol(asyncId)]: 79,
    [Symbol(kHandle)]: TCP {
      reading: false,
      onconnection: null,
      [Symbol(owner)]: [Circular]
    },
    [Symbol(lastWriteQueueSize)]: 0,
    [Symbol(timeout)]: Timeout {
      _idleTimeout: -1,
      _idlePrev: null,
      _idleNext: null,
      _idleStart: 5355,
      _onTimeout: null,
      _timerArgs: undefined,
      _repeat: null,
      _destroyed: true,
      [Symbol(refed)]: null,
      [Symbol(asyncId)]: 81,
      [Symbol(triggerId)]: 0
    },
    [Symbol(kBuffer)]: null,
    [Symbol(kBufferCb)]: null,
    [Symbol(kBufferGen)]: null,
    [Symbol(kBytesRead)]: 0,
    [Symbol(kBytesWritten)]: 0
  }
}
2
(node:10672) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Timeout waiting for status response from device id: 6cca4b3266982d41fdkeou')

**Comment by Fabian-Ser** [comment]
> const device = new TuyAPI({
    id: '6cca4b3266982d41fdkeou',
    key: '2386f2cbc6339599',
    version: 3.3
});

**Comment by codetheweb** [comment]
When you run your script with debug output enabled, is it the same as your post above where the device sends a response to the GET request but TuyAPI isn't able to parse it?

**Comment by Fabian-Ser** [comment]
Solved it, filling in the new generated key fixes the problem.

**Comment by Natguillet** [comment]
Hello, sorry for the response time. 
I don't understand how to solve the problem because the key always remains the same. 
Here is my output with the debug mode. I have two lights connected.
`2020-11-16T01:52:41.116Z TuyAPI Finding missing IP undefined or ID 56238886c82b960de056
2020-11-16T01:52:45.174Z TuyAPI Received UDP message.
2020-11-16T01:52:45.176Z TuyAPI UDP data:
2020-11-16T01:52:45.178Z TuyAPI { payload:
   { ip: '192.168.2.47',
     gwId: '07683018c82b960cae9a',
     active: 2,
     ability: 0,
     mode: 0,
     encrypt: true,
     productKey: 'keyxsd5gpv43w3vq',
     version: '3.3' },
  leftover: false,
  commandByte: 19,
  sequenceN: 0 }
2020-11-16T01:52:45.200Z TuyAPI Received UDP message.
2020-11-16T01:52:45.201Z TuyAPI UDP data:
2020-11-16T01:52:45.201Z TuyAPI { payload:
   { ip: '192.168.2.46',
     gwId: '56238886c82b960de056',
     active: 2,
     ability: 0,
     mode: 0,
     encrypt: true,
     productKey: 'keyxsd5gpv43w3vq',
     version: '3.3' },
  leftover: false,
  commandByte: 19,
  sequenceN: 0 }
2020-11-16T01:52:45.203Z TuyAPI Connecting to 192.168.2.46...
2020-11-16T01:52:45.229Z TuyAPI Socket connected.
Connected to device
2020-11-16T01:52:45.230Z TuyAPI GET Payload:
2020-11-16T01:52:45.230Z TuyAPI { gwId: '56238886c82b960de056',
  devId: '56238886c82b960de056',
  t: '1605491565',
  dps: {},
  uid: '56238886c82b960de056' }
2020-11-16T01:52:45.269Z TuyAPI Received data: 000055aa000000010000000a000000ac00000000a2b14c0541e45a84d173ad85bc4d4e23dc74e3939bc7131977ed1bab58fdaa3446e438fe52f4328063c636d6f23c0accce28f105abe078098d21e3f6d41d6cf2a0cebfccd974a32660ccdd20139c6edad7f315ee1fa6642d8a0004fa9ad2b266174676662433a8ded1a6a66aee231707effa8815d0075ad817b47706666e8b0f426ab36d70c0eca97968957d46363d539f596cc105589a9977b2eb031b0810fa6baba21b0000aa55
2020-11-16T01:52:45.269Z TuyAPI Parsed:
2020-11-16T01:52:45.269Z TuyAPI { payload:
   { devId: '56238886c82b960de056',
     dps:
      { '20': true,
        '21': 'colour',
        '22': 1000,
        '23': 1000,
        '24': '00c403e80387',
        '25': '000e0d00002e03e802cc00000000',
        '26': 0 } },
  leftover: false,
  commandByte: 10,
  sequenceN: 1 }
Data from device:  { devId: '56238886c82b960de056',
  dps:
   { '20': true,
     '21': 'colour',
     '22': 1000,
     '23': 1000,
     '24': '00c403e80387',
     '25': '000e0d00002e03e802cc00000000',
     '26': 0 } }
Boolean status of default property: true.
2020-11-16T01:52:45.270Z TuyAPI SET Payload:
2020-11-16T01:52:45.270Z TuyAPI { devId: '56238886c82b960de056',
  gwId: '56238886c82b960de056',
  uid: '',
  t: 1605491565,
  dps: { '1': false } }
2020-11-16T01:52:45.294Z TuyAPI Received data: 000055aa00000002000000070000000c0000000018cfc5da0000aa55
2020-11-16T01:52:45.294Z TuyAPI Parsed:
2020-11-16T01:52:45.294Z TuyAPI { payload: false, leftover: false, commandByte: 7, sequenceN: 2 }
2020-11-16T01:52:45.294Z TuyAPI Got SET ack.
Error! Timeout waiting for status response from device id: 56238886c82b960de056
2020-11-16T01:52:51.120Z TuyAPI Disconnect
2020-11-16T01:52:51.121Z TuyAPI Socket closed: 192.168.2.46
Disconnected from device.`

**Comment by codetheweb** [comment]
It looks like your code isn't quite right.

Instead of

```js
device.set({set: !(data.dps['20'])});
```

try
```js
device.set({dps: 20, set: !(data.dps['20'])});
```

**Comment by FliegenKLATSCH** [comment]
I also hit the timeout issue. Created #380.
The initial get interfered with the set call:
```
        this.device.connect().then(() => {
            this.device.set({set: value})
                .then(() => {
                    this.device.disconnect();
                });
        });
```

**Comment by codetheweb** [comment]
Merged the above PR.

@Natguillet check it out (and the updated documentation) to see if it solves your issue.

**Comment by ahape** [comment]
> It looks like your code isn't quite right.
> 
> Instead of
> 
> ```js
> device.set({set: !(data.dps['20'])});
> ```
> 
> try
> 
> ```js
> device.set({dps: 20, set: !(data.dps['20'])});
> ```

@codetheweb this fixed the issue for me. The program in the README uses the example `device.set({set: !(data.dps['1'])});`. Perhaps that needs to be updated with the new schema (dps 20 for on/off)?

**Comment by codetheweb** [comment]
The majority of devices I've seen so far have their on/off property at index 1.

I added a note about index 20 as well to the README.

**Comment by csmale** [comment]
I am seeing this too - all the GETs work, but a SET always gives "Timeout waiting for status response from device". I added a second different device (unlinked from the previous app (Gosund) and registered with Tuya Smart) and this did exactly the same. Someone mentioned "reregistering" the device - how far do I need to go back? I'd appreciate any tips/pointers!
