### ISSUE TITLE
Cant Fetch Required Paramaters

### ISSUE THREAD

**Issue by twann503** [codetheweb/tuyapi#38]
Hello, Im having trouble using Charles to get the IDs , I followed the direction and signed ther certificatte on my iphone and everything but still just getting gibberish, the text doesnt display like your direction does. 

https://gyazo.com/7f40922412ab92efe1004e7ff12933c8

Is there an easier way to pull the required IDs? Basically i'm trying to get the ID to implement into my own ios App to allow controlling of the switches I have.

**Comment by codetheweb** [comment]
It looks like Charles is only sniffing connect TCP requests for some reason.

Although I haven't updated the documentation yet, there is now a *much* easier way to get the parameters.  First you have to [make a Tuya account](https://iot.tuya.com/signup) and request API access.  Then install [this package](https://github.com/TuyaAPI/link), and run the usage example (after you put your device in linking mode).
