### ISSUE TITLE
Documentation isn't consistent with site.

### ISSUE THREAD

**Issue by auggy** [codetheweb/tuyapi#383]
**Describe the bug**
Can't find api key at Tuya.com documentation isn't consistent with iot.tuya.com

**To Reproduce**
1. Go to 'iot.tuya.com
2. all the top nav bar directions from the documentation aren't there 
3. can't find virtual ID

**Comment by auggy** [comment]
I figured it out

**Comment by codetheweb** [comment]
Tuya recently updated their site, I haven't gotten around to updating the docs yet.

**Comment by codetheweb** [comment]
Fixed in a58a261.
