### ISSUE TITLE
Any plans to implement Device Timing Management?

### ISSUE THREAD

**Issue by davidgurr** [codetheweb/tuyapi#385]
If I understand correctly, tuyapi uses the "Device Control" section of the official Tuya API.

But there's also a "Device Timing Management" section. This would be really neat to be able to use ... it means that you could set schedules in the Tuya device that will run independent of any Home Automation server.

That's attractive when you think of the common failure modes for Home Automation - router failure, intermittent WiFi, or server failure.

Have there been any discussions about implementing this?

**Comment by codetheweb** [comment]
That requires calling the Tuya cloud API, which this package doesn't do - it's focused on local control.

You should be able to accomplish this by using the [OpenAPI](https://github.com/TuyaAPI/openapi) wrapper.

**Comment by davidgurr** [comment]
I see that Tuya's OpenAPI only gives free access until July 15th 2021 for accounts opened before July 16th 2020, or three months for those opened after.

There's no public information on any personal use or hobbyist packages after that - only on Enterprise packages, which even then don't have pricing for the package bundles.

It would be *great* if someone with the appropriate tech could investigate a local control alternative for programming schedules in Tuya devices.

**Comment by codetheweb** [comment]
If I remember correctly some devices support setting schedules (like [this one](https://github.com/clach04/python-tuya/wiki/DeviceSchemas#geekbes-mini-smart-socket-ym-sw-1)) using DPS properties. But that changes on a device-by-device basis; as far as I know there's not a unified API for scheduling events locally.
