### ISSUE TITLE
Device failed to be registered. Time is invalid

### ISSUE THREAD

**Issue by Ariel-Rodriguez** [codetheweb/tuyapi#386]
**Describe the bug**
I am trying to use the API but i can't even success at setup steps. What is wrong with  **request time is invalid**?

**To Reproduce**
I followed [setup guide ]( https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md#linking-a-tuya-device-with-smart-link)and got stuck step #6

Then I followed the recommended guide using `tuya-cli wizard`

**Expected behavior**
I am able to controll a device using API.

**Debug Output**
**Postman/NPM**
 - request time is invalid

**Wizzard**
 - There was an issue fetching that device. Make sure your account is linked and the ID is correct.

```

```

**Screenshots**

NPM CLI
----
![image](https://user-images.githubusercontent.com/464285/101213693-0c4a3800-367b-11eb-9d02-87a9712f3367.png)

Postman
----
![image](https://user-images.githubusercontent.com/464285/101213869-5df2c280-367b-11eb-9fbf-b7111a06242a.png)

CLI Wizard
----
![image](https://user-images.githubusercontent.com/464285/101215506-410bbe80-367e-11eb-9731-06bb9562e7dc.png)
![image](https://user-images.githubusercontent.com/464285/101215587-64366e00-367e-11eb-8990-6347dce6b5bd.png)

API KEY and Secret from project
----
![image](https://user-images.githubusercontent.com/464285/101215691-8d56fe80-367e-11eb-9405-af0cd0db09d2.png)

**Desktop (please complete the following information):**
 - OS: WSL2 - Ubuntu
 - OS Version 20.0.4
 - Node Version 12.2.0

**Additional context**

**Comment by codetheweb** [comment]
I believe this error is related to clock synchronization. It's likely your device clock was set manually. Try changing your Windows time settings so that the time is set automatically.
