### ISSUE TITLE
Large Numbers of Keys

### ISSUE THREAD

**Issue by Akshue** [codetheweb/tuyapi#390]
I have an account with over 200 devices... When I pull keys with the wizard, I don't have any issue with the first 100. However, after 100 I get 

"... 122 more items]"

How can I view the remaining devices?  Can this output be saved directly to a file?

**Comment by codetheweb** [comment]
> I have an account with over 200 devices

Oh my...

I'm probably gonna be too busy for the next week or so to implement this, but I imagine a simple flag could be added to the `tuya-cli cloud list` command (same parameters as wizard, just not interactive) that stringifies the JSON response before printing it so you don't hit that limit.

Also happy to accept PRs. 😃

**Comment by codetheweb** [comment]
Sorry, forgot about this request.

Just published v1.15.0 of @tuyapi/cli, so after updating you now can pass `-s` or `--stringify` to `tuya-cli wizard` and it'll print out your full 200 devices 😛.
