### ISSUE TITLE
Problem with link deices by App Account

### ISSUE THREAD

**Issue by hyperion007** [codetheweb/tuyapi#394]
I am having issues with #323 and I scan the QR code from the app but all I get is a message in "message center" in the app, that says: "an Unknown Device mobile phone has just logged in to this account..." and the QR code expires as soon as it is scanned but there are no link devices listed on iot.tuya.com

I am using a BeagleBoneBlack and I don't have any wifi on it. It is connected to my router. Do I have to have it connected to the same wifi or can it be connected via ethernet? It should still be able to access the bulbs etc. right? 

I swapped all the < > for ' ' in the old method and that did get it started but still failed. 
"
✖ Device(s) failed to be registered!
Error: permission deny
    at OpenAPI._client.got_1.default.extend.hooks.afterResponse.response (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/link/node_modules/@tuyapi/openapi/dist/api.js:68:31)
    at EventEmitter.emitter.on (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
debian@beaglebone:/$ 
"

I'm very new to this and I'm attempting to get my light bulbs to work with Node-Red.

**Comment by eliashe92** [comment]
I've got the same problem

**Comment by Radon-iot** [comment]
Same issue here

**Comment by SpartanTech** [comment]
same here and not new to this. bulbs are connected to my network's wifi and its an open connection. seems like the method1 is now depreciated. please update or change

**Comment by codetheweb** [comment]
Does this fix it for you?

>  I played around with the permissions and enabled Home Management and Device User Mangement for my app in the tuya cloud console.

Moving to https://github.com/codetheweb/tuyapi/issues/396, please follow that issue for updates.
