### ISSUE TITLE
Instructions in SETUP.md for iot.tuya.com no longer working

### ISSUE THREAD

**Issue by torbjornaxelsson** [codetheweb/tuyapi#395]
**Describe the bug**

It looks like in the last few days there was a major update of iot.tuya.com. It's no longer possible to access Cloud Development without being manually verified for an enterprise account. This means it's no longer possible to follow the instructions in  SETUP.md to extract local keys, so unless someone finds a workaround this method should be marked as deprecated.

I'm aware of two currently working methods to extract local keys, both relying on a rooted Android device and neither is straight forward.

The first method is to use an old version of Smart Life app downloaded from APKmirror (the latest version does not work) and extract the keys from the app preferences. I did this today without issues. The method is described here https://github.com/clach04/python-tuya/wiki/Setup#extract-details-from-android-config-file

The second method is to dump the Android app memory. I have not tried this method. It's described here: https://github.com/codetheweb/tuyapi/issues/345

**To Reproduce**
1. Register a new account at iot.tuya.com
2. Try to create a cloud project as per instructions. You will get prompted to apply for enterprise verification.

**Expected behavior**
Ideally SETUP.md should outline currently working methods for extracting local keys as well as list methods that are no longer working as deprecated.

**Comment by codetheweb** [comment]
I just tried this and was able to create a new Cloud project under a new Tuya account that I just created.

I'm in the U.S. and selected U.S. when signing up; maybe it varies by region?

**Comment by torbjornaxelsson** [comment]
Thanks @codetheweb, I tried to register again and this time I can create a cloud project. Very strange since the account I created a few days ago still does not work. I selected Canada both times so doesn't seem to be region dependent. Maybe it was just a temporary glitch.

In any case, since it now I will close the issue! Cheers

**Comment by codetheweb** [comment]
Weird, glad it's working now.
