### ISSUE TITLE
QR code has expired issue

### ISSUE THREAD

**Issue by banky** [codetheweb/tuyapi#396]
**Describe the bug**
Hello, 

I'm having an issue where the tuya cloud provider fails when I try to connect to my smart life app. After scanning the code, I get this notification on my phone: 

```
A(n) Unknown Device mobile phone has just logged in to this account. If this is not your activity, we recommend that you modify the login password immediately to protect your account.
```

And on the Tuya page, I get a "QR code has expired" error. Could I please get some insight for this? 

**To Reproduce**
1. Create a new cloud app following steps in the readme
2. Add an app SDK
3. Try to add app account

**Expected behavior**
I expect that there should be no error in connecting to the Tuya service

**Debug Output**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - OS Version [e.g. 22]
 - Node Version [output of `node -v`]

**Additional context**

**Comment by enz1ey** [comment]
I'm having this same issue, for the last three days I've been unable to link my Smart Life or Tuya apps in the API portal.

**Comment by tommy21osu** [comment]
I am also having the same issue.

**Comment by banky** [comment]
Hey guys @enz1ey @tommy21osu. I played around with the permissions and enabled Home Management and Device User Mangement for my app in the tuya cloud console. Let me know if that works for you

**Comment by codetheweb** [comment]
> Hey guys @enz1ey @tommy21osu. I played around with the permissions and enabled Home Management and Device User Mangement for my app in the tuya cloud console. Let me know if that works for you

Did that fix it for you?

**Comment by BoneheadFraggle** [comment]
Yep. I already had activated Device User Mangement, but "Home Mannagement" did it for me (typo in Tuya). 

Thanks!

**Comment by enz1ey** [comment]
I had everything under API Groups enabled since two days ago, but it just worked for me. I'm wondering if there was something up on Tuya's back-end preventing the app to register with the QR code. Just tried scanning again, and instead of the QR code showing expired, it showed a success message and my devices are now showing in the portal.

**Comment by hyperion007** [comment]
It just magically worked for me now as well!

**Comment by banky** [comment]
Awesome, seems to have been resolved. I'll close this

**Comment by Radon-iot** [comment]
Great, works with me, thanks!

**Comment by codetheweb** [comment]
Sounds good, I updated the setup instructions with the API groups.

**Comment by SpartanTech** [comment]
Confirmed the fix works for me as well

**Comment by xzero0911** [comment]
Works for me too when get tuya Power Strip!
Thanks for save my life!

**Comment by pwnj0hn** [comment]
I am having the same issue now. Where did you find the "Home Management" setting?

**Comment by marioskamperis** [comment]
I am having the same issue as well.
Where are is the "Home Mannagement" setting?

**Comment by FalconFour** [comment]
Same here! This is so unbelievably frustrating - Tuya's console is an absolute jungle for such a simple ask.

WHERE is this "home man(n)agement" option? "API groups"? What tab, what sub-tab, what sub-sub-sub tab? I'm pulling my hair out dealing with this "QR code has expired" issue (still a very valid issue - why doesn't the setup guide say where to go?).

**Comment by ProDev76** [comment]
This problem still exists, I'm trying to use the Link App Account feature, but when I scan the QR Code it just straight up expires.

**Comment by skndz** [comment]
I'm also having this problem, using SmartLife app. Have tried all the data centers, got the necessary Service API's selected.

Any idea how i could fix it?

**Comment by Bagunda** [comment]
App show "no access". I turn on all permissions when creating new Cloud Project. And I cheched my region. All right.
But app "tuya smart" and "smart life" show "no access" after scan QR-code.
![2022-10-22 16-01-52](https://user-images.githubusercontent.com/16766521/197344565-b15f0c8b-4c8e-4737-9365-923930267853.JPG)
![2022-10-22_16-11-46](https://user-images.githubusercontent.com/16766521/197344568-53ecb3c3-56a3-41aa-b7ed-9f027a2ea55e.png)

**Comment by FalconFour** [comment]
Ah yes. At the time, I was using the wrong app. Tuya is a complicated, wild, fragmented ecosystem of many different products -- and many look-alike apps that seem to work on the same data, yet somehow... don't? So, grab another look-alike app and log in there, see if _that_ one's QR code works instead.

My conclusion was that my use-case was perfect for ditching Tuya completely, and hacking them with Tasmota firmware to "free" them from the wacky Tuya ecosystem. Now they work locally -- and more accurately! (corrected the 30% energy-monitoring error) Using Home Assistant and Nabu Casa for remote control from my home server, instead of Tuya's cloud.

**Comment by Chir1i** [comment]
I have all API's active and I still can't scan the qr code, is this still a problem in 2024? Wow

**Comment by maxakash** [comment]
> I have all API's active and I still can't scan the qr code, it is this still a problem in 2024? Wow

Did you manage to solve it?
