### ISSUE TITLE
tuya-cli wizard error "There was an issue fetching that device. Make sure your account is linked and the ID is correct."

### ISSUE THREAD

**Issue by rpelletierrefocus** [codetheweb/tuyapi#397]
I am unable to control a couple of my devices as of today so I went on to see if my keys had changed for some reason. But now it seems this is no longer working. 

When I enter "Provide a 'virtual ID' of a device currently registered in the app:"

I get an error. "There was an issue fetching that device. Make sure your account is linked and the ID is correct."

I have a suspicion this is related to a couple of other issues I am seeing that opened up.  #394 in particular

**Comment by codetheweb** [comment]
Closing as #396 is the root issue; feel free to reopen if you still have this issue after resolving that. Please discuss at #396 meanwhile so we can keep the discussion in one place.
