### ISSUE TITLE
Smart Linking Sylvania Smart+ bulbs results in "Error: permission deny"

### ISSUE THREAD

**Issue by KTibow** [codetheweb/tuyapi#398]
**Describe the bug**
I'm trying to grab my tokens for a sylvania smart+ bulb I got recently using the Smart Link method. But I get this error:
![image](https://user-images.githubusercontent.com/10727862/103423465-8f1bc100-4b5b-11eb-964e-6baad952c0f1.png)

**To Reproduce**
1. Run `npx tuya-cli link --api-key [] --api-secret [] --schema [] --ssid [] --password [] --region us` with a sylvania smart+
2. See error

**Expected behavior**
The tokens to be printed out.

**Debug Output**

I couldn't get debug to work, so here's what I have:
```
× Device(s) failed to be registered!
Error: permission deny
    at OpenAPI._client.got_1.default.extend.hooks.afterResponse (C:\Users\Kende\AppData\Roaming\npm\node_modules\@tuyapi\cli\node_modules\@tuyapi\link\node_modules\@tuyapi\openapi\dist\api.js:68:31)
    at EventEmitter.<anonymous> (C:\Users\Kende\AppData\Roaming\npm\node_modules\@tuyapi\cli\node_modules\got\dist\source\as-promise.js:87:38)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/10727862/103423531-f20d5800-4b5b-11eb-82f5-c1a4cb998769.png)

**Desktop (please complete the following information):**
 - OS Windows
 - OS Version 19042.685
 - Node Version v12.18.3

**Additional context**
Probably would work if they allowed to use the Tuya app itself.

**Comment by codetheweb** [comment]
> Probably would work if they allowed to use the Tuya app itself.

By this (and [the other comment](https://github.com/codetheweb/tuyapi/issues/387#issuecomment-753030278) you left) do you mean that your devices don't work at all with the official Tuya app? If they don't with work that, they probably won't work with TuyAPI.

**Comment by KTibow** [comment]
Nope, they work with a different app (a Sylvania OEM one). As I was pointed to on the HA forums, probably it was because I didn't run this with admin privileges.
