### ISSUE TITLE
Device with 4 outlets and usb

### ISSUE THREAD

**Issue by jcf6288** [codetheweb/tuyapi#40]
Is there a way to control individual outlets on a power strip?  I can with pytuya but no with tuyapi.  Thanks

**Comment by codetheweb** [comment]
Yes, it's possible.  First, you should get the schema of your device by calling `get({schema: true})`.  Then, set the DPS index you want to change with `set({dps: 2, set: true})`.  See the [docs](https://github.com/codetheweb/tuyapi/blob/master/docs/API.md#set) for more details.
