### ISSUE TITLE
Power statistic plug

### ISSUE THREAD

**Issue by foulek57** [codetheweb/tuyapi#400]
Hi,

I try to have the power statistic of a plug.

They are under "route" - year and '12' for december.

`01-03 22:11:22.574 31142  4822 E fb-jni  : ReactNativeJS 'route', '2020', '12', '40.26'
01-03 22:11:22.995 31142  4822 E fb-jni  : ReactNativeJS 'max ', 1.83, 10`

They are data from that i have with 'adb logcat'

`01-03 22:10:29.760 31142  4822 E fb-jni  : ReactNativeJS '-----主动查询DP', 'countdown'
01-03 22:10:29.795 31142  4822 E fb-jni  : ReactNativeJS '-----主动查询DP', 'countdown'
01-03 22:10:30.439 31142  4822 E fb-jni  : ReactNativeJS '-----数据上报', { countdown: 0 }, { '2': 0 }
01-03 22:10:30.706 31142  4822 E fb-jni  : ReactNativeJS '-----数据上报', { countdown: 0 }, { '2': 0 }
01-03 22:10:32.626 31142  4822 E fb-jni  : ReactNativeJS '-----数据上报', { cur_current: 208, cur_power: 127, cur_voltage: 2421 }, { '4': 208, '5': 127, '6': 2421 }
01-03 22:10:37.726 31142  4822 E fb-jni  : ReactNativeJS '-----数据上报', { cur_current: 218, cur_power: 148 }, { '4': 218, '5': 148 }
01-03 22:10:42.866 31142  4822 E fb-jni  : ReactNativeJS '-----数据上报', { cur_current: 211, cur_power: 140 }, { '4': 211, '5': 140 }
01-03 22:10:47.656 31142  4822 E fb-jni  : ReactNativeJS '-----数据上报', { cur_current: 207, cur_power: 127 }, { '4': 207, '5': 127 }
01-03 22:10:49.903 31142  4822 E fb-jni  : ReactNativeJS '-----数据上报', { cur_power: 134 }, { '5': 134 }
01-03 22:10:54.657 31142  4822 E fb-jni  : ReactNativeJS '-----数据上报', { cur_current: 208, cur_power: 125, cur_voltage: 2413 }, { '4': 208, '5': 125, '6': 2413 }
01-03 22:11:14.701 31142  4822 E fb-jni  : ReactNativeJS '-----数据上报', { cur_current: 211, cur_power: 163, cur_voltage: 2421 }, { '4': 211, '5': 163, '6': 2421 }
01-03 22:11:16.789 31142  4822 E fb-jni  : ReactNativeJS '-----数据上报', { cur_current: 207, cur_power: 127 }, { '4': 207, '5': 127 }
01-03 22:11:22.574 31142  4822 E fb-jni  : ReactNativeJS 'route', '2020', '12', '40.26'
01-03 22:11:22.995 31142  4822 E fb-jni  : ReactNativeJS 'max ', 1.83, 10
`

Any way to have this data with this API ?

**Comment by codetheweb** [comment]
TuyAPI doesn't necessarily return all the data that you see presented in the app. Some of it is pulled from Tuya's cloud API.

You should be able to get basic power stats from your device locally with TuyAPI, but I don't believe cumulative stats are available.

**Comment by foulek57** [comment]
Thanks for the answer, they are no way to get this data on cloud ? Or do you know if another work with the cloud ?

**Comment by codetheweb** [comment]
You might be able to use [this package](https://github.com/TuyaAPI/openapi).
