### ISSUE TITLE
There was an issue fetching that device. Make sure your account is linked and the ID is correct.

### ISSUE THREAD

**Issue by Eucliwood090** [codetheweb/tuyapi#401]
Hello, I'm sorry to come here but nothing I've been trying for a long time and nothing is working ...
`
 tuya-cli wizard
? The API key from tuya.com: ***
? The API secret from tuya.com **
? Provide a 'virtual ID' of a device currently registered in the app: *****
There was an issue fetching that device. Make sure your account is linked and the ID is correct.

I took the steps I have the 3 keys but nothing works I redid the manipulation several times but impossible.

Can you make a "tutorial" video? , I saw some video but the version of https://iot.tuya.com/ is old.
Thank you for your help
`

**Comment by codetheweb** [comment]
I don't currently have any plans to make a tutorial video.

Can you please run the wizard in debug mode (`DEBUG=* tuya-cli wizard` if you're on *sh, otherwise you'll have to set the environment variable `DEBUG` to `*`) and post the output?

**Comment by Eucliwood090** [comment]
... I am crazy, I have been trying for a week with no results I am posting here for help and today everything is working ...

Thanks for your help, thanks to the dev

cordially
