### ISSUE TITLE
Can not recover from poweroff

### ISSUE THREAD

**Issue by dvv** [codetheweb/tuyapi#403]
Hello!

I'm trying to expose a tuya device via mqtt.
The test code is below:

```js
;(async () => {
  const conf = {
    name: "bebebe",
    id: "bububu",
    key: "nonono",
    ip: "ThingsTurn_ZZZZ"
  }
  const dev = new TuyAPI({ version: "3.3", issueGetOnConnect: false, ...conf })
  dev.on("connected", () => {
    console.debug("+TUY", conf.name)
  })
  dev.on("disconnected", () => {
    console.debug("-TUY", conf.name)
  })
  dev.on("data", data => {
    if (data === "json obj data unvalid") return
    console.debug("*TUY", conf.name, data)
    if (!data.dps) return
    Object.entries(data.dps).map(([k, v]) => {
      mqtt.publish(`tuya/${conf.name}/dps/${k}/state`, String(v), { retain: true })
    })
  })
  while (true) {
    let status
    try {
console.debug("?TUY", conf.name)
      status = await dev.connect()
      await dev.get({ dps: 1 })
    } catch (ex) {
console.error("!TUY", conf.name, ex)
      status = false
    }
    mqtt.publish(`tuya/${conf.name}/status`, status ? "online" : "offline", { retain: true })
    await sleep(60000)
  }
})()
```

And this works just fine if the device is powered on.

The problem begins when I cut the power.
First of all I never (as far as I could wait patiently) get the `"disconnected"` event as long as the device is unpowered.
Secondly, the `while` loop gets stuck at `await dev.connect()` at the first iteration after the device is unpowered.
So nothing tells me the device has become non-controllable.

I'd expect here both disconnect issued and connect timed out.

Thirdly, when I power the device back on it somehow emits `"disconnected"` but the loop has been already blocked (forever?) in the previous `await dev.connect()` attempt.
So again nothing tells me the device is back online.

If it were reported disconnect and didn't block in connect it would proceed well here.

I honestly tried to cope with it myself (set socket timeout := ping_timeout + 1 etc.) but no result so far.

Is my code of a valid use of the library?
What can be done to fix the problem?

TIA

**Comment by codetheweb** [comment]
Please take a look at https://github.com/codetheweb/tuyapi/pull/406 and test it out, I believe it may resolve at least one of your issues.

I tested that branch with a physical device. TuyAPI emitted a `disconnected` event when I cut the power to the device, and using this script I was able to automatically reconnect:

```javascript
(async () => {
  for (let i = 0; i < 100; i++) {
    try {
      await device.connect();
      console.log('connected')
    } catch (error) {
      console.log('could not connect');
    }

    await delay(1000);
  }
})();
```

**Comment by codetheweb** [comment]
Closing per #406 and https://github.com/codetheweb/tuyapi/pull/406#issuecomment-766362734.
