### ISSUE TITLE
Typo and intermittent failures from last merge

### ISSUE THREAD

**Issue by tomporter518** [codetheweb/tuyapi#41]
It looks like there might be a typo at (line 356):
```javascript
client.on('error', err => {
    error(e);
});
```
e should actually be err.

I'm also seeing failure with this merge to consistently control my switches where the previous version had no issues. I do **not** believe the above typo is the cause, but I did find it because of the failure to set state. It could be messing with my retry logic however.

**Comment by codetheweb** [comment]
Yeah, sorry about that and other potential issues you've been seeing.

I've been using `master` for developing, as I assumed users would always have the latest stable version since I have to manually publish versions to NPM.  I should probably start using a `develop` branch.

**Comment by tomporter518** [comment]
I have NOT cloned the project. I only use npm but it does seem that when I `npm update tuyapi`, it will pull from master. FWIW, manually fixing the typo in my tuyapi/index.js has returned my script to reliable operation. I have some retry logic for when the device(s) report back an error. That was failing to get invoked because of the typo.

**Comment by codetheweb** [comment]
`npm update` does pull from master, but it uses the latest tagged version, so you should be good there.  I have no idea why NPM would use the latest (untagged) commit.  I just tested it out by creating a new folder, running `npm init && npm i tuyapi -S` and it correctly installed `tuyapi` @ 2.0.3.  The line of code that you quoted above was not present in `index.js`.
