### ISSUE TITLE
not a bug!    ==>   Unable to get API-Key and details for TUYA

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [codetheweb/tuyapi#412]
I'm trying to use your TUYAPI modul but unable to get an API and other details from iot.tuya.com as it appears they have updated their site. It is now not possible to go into CLOUD Development as personal user. Therefore you are unable to create a project (to get the API keys) or to link any devices (for virualID)

Any idea on how this can be solved otherwise?

Thanks for your help

**Comment by codetheweb** [comment]
Can you please post a screenshot of where you're getting stuck?

I have the "basic" user account plan and am still able to see cloud development.

**Comment by jokecr** [comment]
I believe I see the same issue. It now shows as expired and the only tier available is $3000, yikes

![Capture](https://user-images.githubusercontent.com/5993614/106397091-91727480-63c0-11eb-84d7-d37b43733a97.PNG)
![Capture2](https://user-images.githubusercontent.com/5993614/106397224-18bfe800-63c1-11eb-8065-967c05f17043.PNG)

**Comment by xX-Nexus-Xx** [comment]
Please see below. I as well had a chat with support team and they informed me that Cloud Development is no longer available for non-commercial users. Looks like they did some recent changes and you registered before

![image](https://user-images.githubusercontent.com/2195190/106400475-bc1d0580-6472-11eb-89b6-91c377bd271f.png)

This is the verification section
![image](https://user-images.githubusercontent.com/2195190/106400503-dd7df180-6472-11eb-9c6b-dee16625f802.png)

**Comment by codetheweb** [comment]
:(

Tuya has done this before and then seemed to reverse the change, but maybe they're making it permanent now?

Not much I can do unfortunately. If Tuya continues to lock down their services, there's not really any alternative besides [flashing custom firmware](https://github.com/ct-Open-Source/tuya-convert).

Open to new ideas on how to link devices / get keys.

**Comment by milo526** [comment]
And even the custom firmware is limited for new devices due to the use of newer chips and newer updates that come pre-installed on these devices :/

**Comment by Apollon77** [comment]
The "old andoid app way" is still working ... lets hope at least a bit ...

**Comment by alienator88** [comment]
The following steps work, I just created a new account today:

1. Open a Private/Incognito browser window
2. Navigate to iot.tuya.com
3. In the popup, set the Functional Cookies to No and Advertising Cookies to No
4. Submit Preferences and click Sign up to create a new account
5. Go to 10minutemail.com and grab a temporary email address
6. Fill in the temporary email address on iot.tuya.com along with the rest of the fields. I used United States for the country. Agree to terms and complete sign up
7. Enter the email verification code you received on the 10minutemail.com site in the Tuya page to confirm
8. Now login with the temporary email and password you setup
9. Click through the tutorial pop ups
10. Click Cloud > Projects on left sidebar
11. Click Free Trial which should open a new tab
12. Leave everything as is and click Buy now to start the trial
13. Close this tab and go back to the previous one
14. Click Cloud in the sidebar again
15. You should now be able to create a new project
