### ISSUE TITLE
npm: command not found

### ISSUE THREAD

**Issue by pocahozas** [codetheweb/tuyapi#415]
Hello.
I have a problem, maybe it's just a beginners problem. I am using a raspberry Pi 4 con HASSIO.

I have problems with the command line. When I run npm i @tuyapi/cli -g,   I get the following error: "bash: npm: command not found" so that I cannot install npm.
The same issue when running tuya-cli wizard,  I get the following error: -bash: tuya-cli: command not found

What is the way to do it correctly

Thank you very much

**Comment by milo526** [comment]
You are missing NPM, you will first need to install NPM (and probably node).
Since you do not have NPM installed, you cannot install the Tuya-cli.

**Comment by Yonny24** [comment]
Same issue here trying to add localtuya and now it requires npm.
I'm scratching my head at this point.

Can you point us in the right direction please?
Running Home Assistant OS 5.13

**Comment by codetheweb** [comment]
There are multiple ways to install Node & NPM. I recommend using [nvm](https://github.com/nvm-sh/nvm).

**Comment by JPMurara** [comment]
Hello codetheweb! I tried using the link. I just copied the command into the git bash. It did install something but the npm command still not work. Any other suggestion? Cheers.

**Comment by codetheweb** [comment]
You'll have to restart your shell / make a new one if you haven't already after installing nvm for it to activate. You also have to install a Node.js version after installing nvm with something like `nvm install node`.

**Comment by JPMurara** [comment]
thx guys, its working now. That's what I did:
1. download and install node.js https://nodejs.org/en/download/ (it comes with npm)
2. open the git terminal and type npm -v so I could see the version (6.14.15) that was installed from step 1
...and that was it. Easy.
Cheers!
