### ISSUE TITLE
door sensor

### ISSUE THREAD

**Issue by quinto99** [codetheweb/tuyapi#418]
Is door sensor supported?
I can't get id in tuya ap..

**Comment by codetheweb** [comment]
Sensors are not supported. They only connect to WiFi to report something; meaning that it isn't possible to have a persistent connection.

**Comment by nvx** [comment]
I've seen this fact mentioned a bunch of times, but I've got a Tuya PIR sensor and it stays connected to WiFi all the time (I can even  ping it continually without packets ever being missed). I do run mine powered from USB though not battery if that makes a difference.

**Comment by codetheweb** [comment]
Interesting, I've only heard of ones that are battery powered.

**Comment by nvx** [comment]
It has a battery, but the battery it came with died after a few days and powering from USB was quicker than sourcing the weird battery it came with.

https://www.kmart.com.au/product/mirabella-genio-wi-fi-motion-sensor/2622811 this is the specific one I have.
