### ISSUE TITLE
dps=1 is hardcoded in index.js

### ISSUE THREAD

**Issue by law1964** [codetheweb/tuyapi#42]
This only affects devices with more than one channel so is not a high priority. 

Adding an if clause like the following to index.js  around line 190 will fix it:

          if (options.dps !== undefined) {
              resolve(data.dps[options.dps]);
          }
          else {
              resolve(data.dps['1']);
          }

Thanks!

**Comment by codetheweb** [comment]
This is actually already sort of supported - you can call `get({schema: true})`.  But that returns everything.  Your way is much more simple and elegant. 👍 

Will add in next release.

**Comment by codetheweb** [comment]
Added in a621cd66a2e8010517e0645adedda6651f06f566.
