### ISSUE TITLE
Reversing the music_data data point in light sources

### ISSUE THREAD

**Issue by AryToNeX** [codetheweb/tuyapi#420]
The music_data DP (27) is an interesting one found in some Tuya light sources. It is interesting because it does not get set directly into the light source's memory, plus, the change in colour is instant.
This could allow for more fine tuned control of the bulbs by third party software, like RGB effect engines.

I began researching the matter just today, and for now I know that `music_data` is a `string` type data point. It contains an HEX string like `000fc03e8032000000000` (when I send this to the bulb, it turns bright purple).

The next goal is understanding how this HEX string is made. It doesn't seem to be just a padded HEXHSB or HSB value.

I need help on this.

**Comment by AryToNeX** [comment]
I got to work however TuyAPI waits for the response when there isn.t any (this particular DP is set and forget). This causes lags

For anyone wanting to use it, btw, craft the payload like so

```
'0' (strange padding thing) + HSB (like color data) + '0000' (brightness, needs to be zero) + '0000' (temperature, needs to be zero)
```

**Comment by codetheweb** [comment]
:+1: glad you got it working, continuing discussion about new feature in PR.
