### ISSUE TITLE
Timeout reject is "uncatchable"...

### ISSUE THREAD

**Issue by Apollon77** [codetheweb/tuyapi#429]
**Describe the bug**
When in the course of a connection to a device a timeout happens (somewhen AFETR the initial connect went through) the reject in https://github.com/codetheweb/tuyapi/blob/master/index.js#L349 is uncatchable.

my code is ...connect(...).catch(err => ...); But I still get error sreported by Sentry from time t time.

**Expected behavior**
Change that to an error event emit to allow an handling of this error

**Comment by codetheweb** [comment]
Do you think it would make sense to do both a reject and emit? Then initial connect() calls could throw an error that can be caught with try/catch and reconnect calls would emit an error.

**Comment by Apollon77** [comment]
in fact you need to remember that have resolved or rejected the promise already and then you should not do another reject ... and yes emitting always would be ok I think - cleaner is that it is one OR the other :-)

**Comment by msillano** [comment]
I'm using tuyapi in a production environment (see [tuyaDAEMON](https://github.com/msillano/tuyaDAEMON))  and that is a big problem having many devices (see also [issue#35](https://github.com/vinodsr/node-red-contrib-tuya-smart-device/issues/35)).

[node-red-contrib-tuya-smart-device](https://github.com/vinodsr/node-red-contrib-tuya-smart-device) ver. 2.0.0 (uses tuyapi 6.1.1)  added  the capability to set the timeouts. This is an help, using prime numbers we can reduce  the stress, but it is not a solution:  better if timeouts are dynamic, i.e.  modifiables at run time.

Best regards
m.s.

**Comment by Apollon77** [comment]
This issue is not really about making timeouts more configurable ... it is really rejecting a promise that was resolved before already

**Comment by codetheweb** [comment]
Sorry for the late response. I've been busy lately but I hope to take a look at this next week.

**Comment by msillano** [comment]
> This issue is not really about making timeouts

Yes Apollon, but things are strictly connected.

In production environement, with 30+ devices, many of which offline, the default tuyapi  behavior  is not acceptable:  the debug pad is  congested  by error messages, and all the time is  wasted on useless attempts to connect.

Two action lines: 
1) to reduce the device intrusions, i.e. remove all error messages (yes, resolving in rigth mode promises): a status info is enough to monitor devices.
2) The use of  dynamic timeouts, to 'hibernate' the offline devices, in a compromise between reaction times and computational load .

Conclusion, I'm VERY interested in any progress in that field. ;)

Best regards,
m.s.

**Comment by Apollon77** [comment]
@msillano in fact right, but maybe this is a separate issue ;-) We should not try to mix stuff here in issues too much

**Comment by codetheweb** [comment]
> in fact you need to remember that have resolved or rejected the promise already and then you should not do another reject ... and yes emitting always would be ok I think - cleaner is that it is one OR the other :-)

I agree that it's cleaner to do one or the other; just trying to accommodate both the event-driven and promise style APIs.

How does reject + emit on initial connect call, then emit every time after that on errors sound?

**Comment by Apollon77** [comment]
I would not emit on initial call because you neeed to catch the reject in any case else nodejs process dies :-) SO maybe have a "reolve/reject on initial thing, emits after that
