### ISSUE TITLE
30 day eval for Tuya IoT projects?

### ISSUE THREAD

**Issue by scottcopus** [codetheweb/tuyapi#433]
https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md

I tried following the directions above to create a project on the _iot.tuya.com_ website as described in the section **Linking a Tuya device with Smart Link** under step #2.  But the directions don't account for something I witnessed which might be something new implemented by Tuya now?  When creating the first project, it offers a page to sign up for different levels of "Cloud Development Plans".  They offer a **"trial"** plan.  The next plan up is USD $3,000/year and goes up from there.  So I signed up for the trial.  I thought the trial plan mentioned 30 days initially, but looking at it again it may not expire for one year maybe.

Does anyone know if this means that devices must be set up within this 30 day (or one year) window?  Or as long as I get my access ID/key/etc initially, 'tuyapi' and these directions should continue to work in perpetuity?

thanks!  -Scott

**Comment by JanMostert** [comment]
Good question. I signed up this week as well and saw the same plan. I presume that, when a year has past and you need to add another device, you are free to create another account

**Comment by codetheweb** [comment]
They seem to be continually changing the plans and requirements, so currently it seems to be a bit of a lost cause to try and keep the docs up to date. 

Like @JanMostert said, you can just sign up for another account if your trial ends. The IDs are good forever, the key changes each time you relink a device.

**Comment by codetheweb** [comment]
good point @scottcopus

https://github.com/codetheweb/tuyapi/commit/058a16aa9a4f6e8b1495d57a73f1406fb40445f6

If you want to add more please open a PR. :+1:
