### ISSUE TITLE
"Api Products" instead of "API Group"

### ISSUE THREAD

**Issue by indiocochino** [codetheweb/tuyapi#438]
**Describe the bug**
I can't see "API Group" option

**To Reproduce**
I'm following steps for linking Tuya device with Smart Link but in step 5 I see only 2 options under API Management:
- API Products
- API Explorer
If I click on API Proudcts there are options to subscribe to different API products similiar to the shown in the 5th steps but when I try to purchase the product (0$ cost) it shows an error saying that the product has been removed??

![image](https://user-images.githubusercontent.com/13852116/110544919-bcbd5180-812c-11eb-8ead-adaeb069dd48.png)

Thanks in advance!

**Comment by alexlmiller** [comment]
I'm seeing the same thing as well - I emailed Tuya support as their support documentation is also still showing the old "API Group" setup. Waiting to hear back

**Comment by alexlmiller** [comment]
@indiocochino FYI I just tried again this morning and you can now successfully click through on the APIs and "Purchase" them for $0

**Comment by NikiHard** [comment]
don't know how to issue a permit?

> @indiocochino FYI I just tried again this morning and you can now successfully click through on the APIs and "Purchase" them for $0
don't know how to issue a permit?

**Comment by indiocochino** [comment]
> > @indiocochino FYI I just tried again this morning and you can now successfully click through on the APIs and "Purchase" them for $0
> 
> don't know how to issue a permit?
Thanks for your quick answers!
Yes I know how to issue but yesterday when I tried to purchase it showed an error message.

However it works now!

**Comment by alexlmiller** [comment]
I've created a PR for this issue to update the setup instructions to guide users through the new interface

https://github.com/codetheweb/tuyapi/pull/439

**Comment by indiocochino** [comment]
Great!
After subscribe to the new APIs you need enter in each one and create a new authorization (in tab "Project") to link to you project.

**Comment by robinzhx** [comment]
> Great!
> After subscribe to the new APIs you need enter in each one and create a new authorization (in tab "Project") to link to you project.

I don't see the New Authorization option now. possibly tuya dev remove it?

**Comment by codetheweb** [comment]
https://github.com/TuyaAPI/cli/issues/117
