### ISSUE TITLE
Getting ECONNRESET

### ISSUE THREAD

**Issue by jbrepogmailcom** [codetheweb/tuyapi#441]
**Describe the bug**
Getting following error most of the time. It returned correct values only once.

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Error from socket: read ECONNRESET
```

**To Reproduce**
Running 
```
tuya-cli get --ip 10.0.0.13 --id 7683150124xxxxx90b8e --key d0d9d02xxxxx63ae --all
```

**Expected behavior**

**Debug Output**
Post the output of your program/app/script when run with the `DEBUG` environment variable set to `*`.  Example: `DEBUG=* node test.js`.  Copy the output and paste it below (in between the code fences):

```
janbenes@homeautomation:~$ DEBUG=* node test.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - OS Version [e.g. 22]
 - Node Version [output of `node -v`]

**Additional context**

**Comment by Apollon77** [comment]
This normally means that you device closed the connection to the local port. Try to power off/on the devcie. and make sure the Mobiler App is closed completely

**Comment by jbrepogmailcom** [comment]
Done that and now ```tuya-cli get``` is runnning forever. Does it mean it is waiting for the device to push the status?

**Comment by jbrepogmailcom** [comment]
sorry, forgot to add ```--protocol-version 3.3```. Now it is running.
