### ISSUE TITLE
Change in web layout. Missing device section

### ISSUE THREAD

**Issue by sziyan** [codetheweb/tuyapi#445]
Device button to add a device is now missing from projects page, thus unable to add device from app.

![image](https://user-images.githubusercontent.com/17675786/112757005-4c626b80-901a-11eb-8131-81cbb447c4d6.png)

Edit: Seems like only projects created before 24th Mar 2021 supports adding of device.

https://developer.tuya.com/en/docs/iot/open-api/user-guide/managing-devices/link-devices?id=Ka471nu1sfmkl

**Comment by codetheweb** [comment]
🙃 why does it feel like Tuya is intentionally trying to prevent people from controlling their devices...

Updated the docs: https://github.com/codetheweb/tuyapi/commit/8d30a6f36b637425f89e6e3de15c4affd0e60868
