### ISSUE TITLE
Can't reach device

### ISSUE THREAD

**Issue by beans14** [codetheweb/tuyapi#446]
Hello i need help with something.When i try to run this it gives me an error connection time out.Also when i try to ping the lights ip it doesn't respond.The reason i am trying to fix this is because i am trying to make a command for my discord bot that changes the color of the light.

**Comment by kueblc** [comment]
You'll get more meaningful support if you include details about your problem and follow the template given when opening an issue. Please include a code sample, debug logs, something we can use to understand what the issue is.

**Comment by beans14** [comment]
const TuyAPI = require('tuyapi');

const device = new TuyAPI({
    id: '0500532284f3ebfd5ef1',
    key: '',
    ip: '',
    version: '3.3',
    issueRefreshOnConnect: true});

// Find device on network
device.find().then(() => {
    // Connect to device
    device.connect();
});

// Add event listeners
device.on('connected', () => {
    console.log('Connected to device!');
});

device.on('disconnected', () => {
    console.log('Disconnected from device.');
});

device.on('error', error => {
    console.log('Error!', error);
});

device.on('dp-refresh', data => {
    console.log('DP_REFRESH data from device: ', data);
});

device.on('data', data => {
    console.log('DATA from device: ', data);

});

// Disconnect after 10 seconds
setTimeout(() => { device.disconnect(); }, 1000);

**Comment by beans14** [comment]
When i do node ./tuya.js (the files name) it says error connection timeout i have looked around at other issues and they all say to try to ping it and when I do it doesnt respond.

**Comment by codetheweb** [comment]
If it doesn't respond to pings it almost certainly won't work with TuyAPI. Your network is probably misconfigured somewhere. 

Are both the device and your computer on the same subnet with no firewall between them?

**Comment by beans14** [comment]
@codetheweb im running it from a vps

**Comment by codetheweb** [comment]
That won't work, both devices need to be on the same local network. If you need to use a VPS for your application, you may want to try controlling your devices through the [cloud API](https://github.com/TuyaAPI/openapi).

**Comment by beans14** [comment]
@codetheweb what is the difference between the cloud api and what i was trying to use.

**Comment by beans14** [comment]
Also what do i use for the username and password.

**Comment by codetheweb** [comment]
https://github.com/TuyaAPI/openapi/issues/9.
