### ISSUE TITLE
Refresh method ... can this code work?

### ISSUE THREAD

**Issue by Apollon77** [codetheweb/tuyapi#449]
Please see https://github.com/codetheweb/tuyapi/blob/master/index.js#L236 ... can this work if options.dps is an array as per documentation?

I tested it (not in tuyaapi but in pure code) and it never worked. Result was always "undefined".
data.dps is an object ala {"101":1,....} and options.dps is an array [101,102,103]

**Comment by Apollon77** [comment]
Maybe also @stevoh6 ? :-)

**Comment by codetheweb** [comment]
My bad, should have caught that in the PR review.

Updated the docs and published 7.1.0.

**Comment by Apollon77** [comment]
np, I alsochecked that PR and did not noticed it ...so all fine :-)
