### ISSUE TITLE
Another possible throw vs reject?

### ISSUE THREAD

**Issue by tomporter518** [codetheweb/tuyapi#45]
I am wondering if this might be another scenario were a reject would be useful. My cron'd script failed this morning due to this throw.

https://github.com/codetheweb/tuyapi/blob/f07a2a5ab0bfa5d1ebfdaa7270d8cfa407c2de7f/index.js#L255

**Comment by codetheweb** [comment]
Once again, you're right.

I did some research and looked at other instances of `throw` and `reject`; everything else seems to be fine.

Fixed.

**Comment by tomporter518** [comment]
Thanks for the quick turn around. As you can probably tell, I use this package quite a bit. I have cron'd entries on a raspberry pi to randomly (within a specified window) control some switches.

**Comment by codetheweb** [comment]
👍
