### ISSUE TITLE
can not understand URL scheme parameter

### ISSUE THREAD

**Issue by ajocius** [codetheweb/tuyapi#454]
Followed guide to the point 3 that was suggesting:
`Go to App -> App SDK -> Develpment in the nav drawer. Click "Create" and enter whatever you want for the package names and URL Scheme (for the Android package name, you must enter a string beginning with com.). Take note of the URL Scheme you entered. This is equivalent to the schema value needed in step 6. Ignore any app key and app secret values you see in this section as they are not used.`

I have following input boxes:

1. App Name
2. App package for iOS
3. App package for Android
4. Channel ID

What is URL scheme that I will later need to use in step 6 ?

**Comment by codetheweb** [comment]
Looks like the docs lagged behind, sorry. It's the channel ID. Updated in f54843b.
