### ISSUE TITLE
tuya-cli link only discovers 1 or 2 devices at a time

### ISSUE THREAD

**Issue by jfmach** [codetheweb/tuyapi#458]
tuya-cli link finds some of my devices but not most of them. I am trying to add 12 light bulbs and it only finds one or two at a time, often the same ones than in previous attempts, which sets a new key each time.

After repeated attempts I have not been able to discover more than 6 out of 12 devices.

I can't control the bulbs independently and they are installed in a difficult to reach location so I'd really like to avoid having to climb/extract them from their fixtures if at all possible to do them one by one.

Any suggestions? Thank you

**Comment by codetheweb** [comment]
Have you tried setting the `--num` parameter?

**Comment by jfmach** [comment]
Ah didn't see this option, I tried and it would timeout if trying to register more than 3, BUT, I realized that it did not matter and it registered all 12 of them anyway, and I could just retrieve all the keys with "tuya-cli wizard" afterwards.

Now on to registering them in homebridge. Thanks!
