### ISSUE TITLE
Listing Tuya devices from the Tuya Smart or Smart Life apps

### ISSUE THREAD

**Issue by Gunsmithy** [codetheweb/tuyapi#461]
Hi there!

I just wanted to report what seems to be inaccurate documentation.
In the [Setup Guide here](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md) I found the following note:
"Note: Tuya no longer supports this for accounts created after March 24, 2021. If you created your cloud account after that date, this method will not work."

I created my cloud account on April 3rd, 2021 and therefore followed the "Linking a Tuya device with Smart Link" for smart plugs at my parents' house just fine.

After buying some new Teckin SP20 plugs for myself I found this method didn't work and I tried the "Listing Tuya devices from the Tuya Smart or Smart Life apps" for the heck of it and it worked just fine.

I also created my Smart Life account today, April 23rd, 2021, so both accounts are after the above supposed threshold.
I was able to link my Smart Life account to my Tuya Cloud IoT account fine and list my plugs with their local key using the tuya-cli wizard command and successfully add them to Home Assistant with the LocalTuya integration.

I guess something changed since this disclaimer was added? Might want to update it so as to not discourage others. I was just about to buy different plugs instead.

Let me know if I can provide any more information about this, and thanks for the amazing project! :)

**Comment by codetheweb** [comment]
Alright thanks, I'll remove that for now.

> I was just about to buy different plugs instead.

I would recommend that anyways instead of playing a cat/mouse game with Tuya 😛.

**Comment by Gunsmithy** [comment]
Hahaha, you are absolutely not wrong. Most of my plugs are flashed with ESPHome, I've just been dabbling in Local Tuya for unfortunate devices where ESPHome won't work. Thanks again!
