### ISSUE TITLE
Device(s) failed to be registered

### ISSUE THREAD

**Issue by AleXSR700** [codetheweb/tuyapi#462]
Hello everyone,

maybe this is linked to my account being new and you stating that this method is broken now, but according to other users it is still working. So am I doing something wrong or is this the expected behavior now?

If this is because my device is new, is there an alternative way to get this information?

By the way, this may be linked, but in iot.tuya.com I see one linked App Account (linked it manually) with two devices, but when I click on the "device list", none are shown.

`✖ Device(s) failed to be registered!
{ GotError: getaddrinfo EAI_AGAIN openapi.tuyaeu.com openapi.tuyaeu.com:443
    at onError (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/request-as-event-emitter.js:140:29)
    at handleRequest (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/request-as-event-emitter.js:173:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26) name: 'RequestError', code: 'EAI_AGAIN' }`

P.S.: I am running Raspberry Pi OS (latest) on an RPi 4 and was only connected to wifi (already to the target 2.4 Ghz network). I am running HA on that Pi as a supervised installtion. So lots of IPs etc. on that systrm in case that could cause issues.

My initial Android App account is Germany, my iot.tuya.com is US (as recommended) and I tried US and EU servers with this tool.

**Comment by codetheweb** [comment]
That looks like a network issue; I don't think your system can resolve Tuya's domain name. Double-check your network config. To test, try pinging `openapi.tuyaeu.com` or `dig openapi.tuyaeu.com`.

**Comment by AleXSR700** [comment]
Hi,
you are right. I cannot ping openapi.tuyaeu.com from here. But neither from my RPi nor my Windows PC. Is that server maybe dead or no longer correct?

**Comment by codetheweb** [comment]
Hmm the EU endpoint does seem to be down. But it's still [listed on their documentation](https://developer.tuya.com/en/docs/iot/api-request?id=Ka4a8uuo1j4t4), so maybe it's just a temporary outage? I'll check back in a day or two.

That last error is from Tuya, so you can reach the China endpoint but it's saying you don't have an account there (accounts are siloed by country).

**Comment by HugoCC97** [comment]
Hello!

I need for my final degree project to receive data from my tecking plug that's integrated with tuyapi as I saw. I follow the instructions of this project and I had the same issue but with different result by console:

× Device(s) failed to be registered!
Error: permission deny
    at OpenAPI._client.got_1.default.extend.hooks.afterResponse (C:\Users\hugo_\AppData\Roaming\npm\node_modules\@tuyapi\cli\node_modules\@tuyapi\link\node_modules\@tuyapi\openapi\dist\api.js:68:31)
    at EventEmitter.<anonymous> (C:\Users\hugo_\AppData\Roaming\npm\node_modules\@tuyapi\cli\node_modules\got\dist\source\as-promise.js:87:38)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

Could you know exactly what is happening?

**Comment by HugoCC97** [comment]
To be sure, schema value is the same as Device ID?

**Comment by codetheweb** [comment]
No, it isn't. Please double-check the setup instructions and **open a new issue** if you still have problems.

**Comment by FrancYescO** [comment]
i'm on MacOS, i'm trying to register a [LEDVANCE wifi bulb](https://www.ledvance.com/consumer/products/smart-home/smart-home-products-with-wifi-technology/smart-lamps-with-wifi-technology/smart-classic-lamps-with-wifi-technology/classic-bulb-shape-with-wifi-technology-c6443) and it still fails with
```
tuya-cli link --api-key xxx --api-secret xxx --schema xxx --ssid "xxx" --password xxx --region eu
✖ Device(s) failed to be registered!
Error: Timed out waiting for devices to connect.
    at TuyaLinkWizard.linkDevice (/Users/francyesco/.nvm/versions/node/v14.16.0/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/link/index.js:159:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async link (/Users/francyesco/.nvm/versions/node/v14.16.0/lib/node_modules/@tuyapi/cli/lib/link.js:47:19)
```

they have a [specific app](https://play.google.com/store/apps/details?id=com.ldvsmartwifi.smart) for the pairing, that i have also sniffed and is comunicating with `a1.tuyaeu.com/api.json` but comunication seems encrypted like in https://github.com/codetheweb/tuyapi/issues/280

the bulb get detected also in smart life app (and in some other tuya based app like SILVANA) but the linking go in timeout, only in their app all is successful.

any help to go over to get the local key?

**Comment by codetheweb** [comment]
If your device fails to pair with the official Tuya Smart app it won't work with this either - sorry. Closing and locking this issue as conversation is no longer related to original problem. If you want additional help, please open a new issue.
