### ISSUE TITLE
Only 1 of 2 identical devices are able to link, timeout issue?

### ISSUE THREAD

**Issue by marcelser** [codetheweb/tuyapi#464]
Hi I  have 2 identical Tuya Wifi Smart Air Boxes. I followed the setup instructions on how to link those 2 devices with the link command.

So put 2 both into link mode and run the tuya-cli link command. I first tried with 'eu' endpoint but after 3 tries I gave up it always timed out.

Then I used the 'us' endpoint I got an output of 1 device but the devices stopped blinking. I can also now see the one which was registered. By pulling the plugs I found out which one was registered (not blinking fast anymore after plugging in again and also showing as offline when plug was pulled) and which one is not.

The point is even if I try 5-10 times more when the 2nd device is in linking mode with 'us' or 'eu' I always get again 
Error: Timed out waiting for devices to connect.

Interestingly the device stops blinking fast after some seconds but it never successfully connects. Is it maybe just to slow connecting to tuya web? Can increase the timeout and try again? Other Ideas why 2nd devices refuses to join no matter how often I try?

**Comment by codetheweb** [comment]
To clarify: are you always linking both at once or one after another? If you're trying to link both at once, you should pass `-n 2` as a flag to `link`.

Otherwise, the only thing I can think of is that their firmware versions are different. You can check this under "Device Update" in the Tuya app.

**Comment by Apollon77** [comment]
No details, no follow up infos. closing. Please reopen if still relevant and happening with most recent versions.
