### ISSUE TITLE
Question: Missing DPs

### ISSUE THREAD

**Issue by Floppy** [codetheweb/tuyapi#466]
This is more of a question than a bug, as I suspect that this is down to my shoddy understanding of Tuya devices.

I have a dimmer switch, which shows the following in the detail view on iot.tuya.com:
<img width="768" alt="Screenshot 2021-05-09 at 22 55 22" src="https://user-images.githubusercontent.com/3565/117588283-4fbd3c80-b11a-11eb-83e7-b519d4e03bdc.png">

However, when I run the CLI:
```
❯ tuya-cli get --ip {redacted} --id {redacted} --key {redacted} --protocol-version 3.3 -a
{ dps: { '1': true, '2': 138, '3': 110 } }
```
It only shows me the DPs which are Boolean or Integer, it's not showing the Enums. Is that expected? Are those things in the detail view not, in fact, DPs?

Any pointers anyone can give me would be much appreciated. As I say, I'm sure it's my understanding that's lacking here, not `tuyapi` :)

**Comment by codetheweb** [comment]
That list of functions IIRC are properties that you can set using Tuya's cloud API. The available properties that you can set locally are different. For example, my smart plug has a property for a timed on/off which is not available locally:
![Screen Shot 2021-05-11 at 9 40 38 PM](https://user-images.githubusercontent.com/7410405/117910433-8a051600-b2a1-11eb-81a3-0a3d9634ed3d.png)

**Comment by Floppy** [comment]
Ah, OK, that makes sense. I'll poke the Tuya cloud API to see if there's anything I can do with those, but as I suspected it's not a bug for this project. Thanks :)
