### ISSUE TITLE
'API Products' not available

### ISSUE THREAD

**Issue by rajil** [codetheweb/tuyapi#473]
There is no 'API Products' option in the left drawer,

![image](https://user-images.githubusercontent.com/379266/119261887-f44d7d00-bbf6-11eb-96b1-f9c4a0445fdd.png)

**Comment by codetheweb** [comment]
Thanks, updated: https://github.com/codetheweb/tuyapi/commit/62b9da961b063ccf3870c48b6c834ab930547a9f
