### ISSUE TITLE
no device link button

### ISSUE THREAD

**Issue by firemanz8** [codetheweb/tuyapi#476]
ive been following the steps but there is no link device button

**Comment by steatar** [comment]
i think you created CUSTOM DEVELOPMENT project, while you should've created SMART HOME PAAS project. create PAAS project and there will be link device

i did it too, the instructions are not specific about it

**Comment by codetheweb** [comment]
Sorry about that, I just recently updated the instructions.

Let me know if you're still having issues @firemanz8.
