### ISSUE TITLE
UnhandledPromiseRejection

### ISSUE THREAD

**Issue by msillano** [codetheweb/tuyapi#477]
In case of device ON  that goes OFF, tuyAPI fires a  Unhandled promise rejection:
the error occurred at line 446
````
(node:16444) UnhandledPromiseRejectionWarning: Error: connection timed out
    at Socket.<anonymous> (d:\node-red\flow-1984\node_modules\tuyapi\index.js:446:18)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:315:20)
````
which is
````
          // Periodically send heartbeat ping
          this.pingpongTimeout = setInterval(async () => {
            await this._sendPing();
          }, this._pingPongPeriod * 1000);

````
Any idea to cath it?
For more info see [ISSUE#64](https://github.com/vinodsr/node-red-contrib-tuya-smart-device/issues/64#issuecomment-854039200)

Best regards
m. s,

**Comment by codetheweb** [comment]
Sorry, I was unable to reproduce this.

My script:

```js
const device = new TuyAPI({
  id: '',
  key: '',
  version: '3.1'});

(async () => {
  await device.find();
  await device.connect();

  device.on('connected', () => {
    console.log('Connected to device!');
  });

  device.on('disconnected', () => {
    console.log('Disconnected from device.');
  });

  device.on('error', error => {
    console.log('Error!', error);
  });
})();
```

I unplugged my device ~1 minute after starting the above script.

Result:

[![asciicast](https://asciinema.org/a/QMcGY6pNmWG4riIVJLAgUNPSy.svg)](https://asciinema.org/a/QMcGY6pNmWG4riIVJLAgUNPSy)

A disconnected event was fired normally.

(I realize the above screencast includes my device ID/key; I'll reset it.)

**Comment by msillano** [comment]
Solved adding a `.catch()` to the returned promise. See [ISSUE#64](https://github.com/vinodsr/node-red-contrib-tuya-smart-device/issues/64#issuecomment-856197665).
Sorry for the inconvenience.

Best regards.
m.s.
