### ISSUE TITLE
Linked Devices

### ISSUE THREAD

**Issue by USO0815** [codetheweb/tuyapi#488]
Hello,

I can't find the Linked Devices under the Cloud tab!

Greetings Nico

**Comment by codetheweb** [comment]
Not sure what you mean, sorry. 

What specific step of the setup process are you having trouble with?

**Comment by USO0815** [comment]
Thank you very much for your help!
The way with Tuya IOT account is out of order since May! We have to use another way to get the local keys. But this is very simple and and there are also good videos on Youtube. Search for: HOW TO - Get All Local Tuya Keys (ALL KEYS, SIMPLE, NO SOLDERING).

Thank you and greetings Nico

**Comment by codetheweb** [comment]
Ok, sounds like you figured it out. Feel free to make a PR if you feel that any documentation needs to be updated.
