### ISSUE TITLE
tuya-cli link: Device(s) failed to be registered! Error: sign invalid

### ISSUE THREAD

**Issue by AlexKidd88** [codetheweb/tuyapi#497]
I have an Issue registering my devices:

`tuya-cli link --api-key xxx --api-secret xxx --schema xxx --ssid xxx --password xxx --region eu
✖ Device(s) failed to be registered!
Error: sign invalid
    at OpenAPI._client.got_1.default.extend.hooks.afterResponse.response (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/link/node_modules/@tuyapi/openapi/dist/api.js:68:31)
    at EventEmitter.emitter.on (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

I already triple checked the api-key, api-secret and schema parameters and don't know what could be the issue.

On iot.tuya.com there is a note stating: "To better secure your cloud development, Tuya will upgrade the signature algorithm. Projects created after June 30, 2021 are subject to signature verification with the new algorithm. View details."
Maybe this has something to do with it.

I would appreciate some help.

**Comment by robbinjanssen** [comment]
@AlexKidd88 I ran into the same problem, this is because of the new signature algorithm. 

It has been partly fixed in https://github.com/codetheweb/tuyapi/issues/492, but as far as I understand https://github.com/TuyaAPI/cli/issues/130 needs to be fixed before you can run the link command again.

**Comment by codetheweb** [comment]
Correct.

As always, happy to accept PRs. :)

**Comment by robbinjanssen** [comment]
@codetheweb I could try, but i've only stumbled across this library yesterday, so I have no clue on what is tied together and how :)

Looking at the issues, you would like to see [this](https://github.com/TuyaAPI/link/blob/master/index.js#L1) (and every usage of the Cloud class) to be replaced with [this library](https://github.com/tuya/tuya-connector-nodejs)?

**Comment by codetheweb** [comment]
👍 yep

**Comment by promy** [comment]
I am running into the same issue ;-) 
Does it require @codetheweb  to change something, or is it something i need to change on my raspberry pi
(sorry, only a noob hobby programmer...)

**Comment by codetheweb** [comment]
Closed: https://github.com/TuyaAPI/cli/issues/130

Fixed in 1.17.2 of @tuyapi/cli.
