### ISSUE TITLE
LEDVANCE device link / help getting local-key

### ISSUE THREAD

**Issue by FrancYescO** [codetheweb/tuyapi#509]
Starting from https://github.com/codetheweb/tuyapi/issues/462#issuecomment-895473143

Basically they used a customized version of the tuya app/protocol, someone sayd it registered a similar bulb [using the tuyapi link](https://community.home-assistant.io/t/sylvania-smart-wifi/223985/27?u=francyesco) functionality but as described in my case was not working

do you have any suggestion to extract somehow the localkey (i've also tried to search in the app files on android using root explorer, but found nothing useful, neither via logcat)?

PS. i've also tried tuya-convert that was unsuccessful https://github.com/ct-Open-Source/tuya-convert/issues/974

**Comment by codetheweb** [comment]
I've been seeing a few issues about LEDVANCE lately, it doesn't seem that they work with the official Tuya Smart app and so won't work with TuyAPI (as far as getting keys goes). I'm sorry but there's not really any other options besides what's listed in `SETUP.md` and trying to extract the keys via the filesystem on Android.

**Comment by FrancYescO** [comment]
for completeness, i managed to sniff the localkey with frida:

https://community.home-assistant.io/t/ledvance-wifi-bulbs/301478/7?u=francyesco
