### ISSUE TITLE
Hidden DPS inputs

### ISSUE THREAD

**Issue by RealIndica** [codetheweb/tuyapi#510]
I have found that with some devices with extended features (such as my robot hoover; it has a find device option that plays a sound. The DPS for this is 116 (boolean).

However, even looking at the schema the dps 116 does not show up at all. Is there a way to check if individual DPS keys exist to find hidden dps inputs via brute force?

However, I can still write to this dps input; it is just not visible.

Cheers

**Comment by codetheweb** [comment]
That's really interesting, I haven't heard of something like that before.

There's nothing in this library specifically to do a brute-force keyspace search, but I don't imagine it would be too hard to write a simple loop that tries setting incremental DPS values.

**Comment by RealIndica** [comment]
I have always found it quite odd that there's huge number spaces between dps keys such as "1, 2, 10, 11, 16, 17, 18, 19, 20, 110, 112" etc.

It's understandable that a lot would be unused, but hidden dps keys is very new to me. 

I would like to "backup" the original dps values before brute forcing them incrementally to see what they do to prevent irreversible damage/weirdness to the device. 

Very interested to see if other devices have this too.

**Comment by RealIndica** [comment]
So I tried what you said anyway (lol) and it did reveal an extra dps key, although it doesn't seem to do much but disable the same value of another dps key.

Whilst setting all the keys (from 0 to 200) to true, it also reset the life left in the hepa filter, brushes etc for the hoover.

**Comment by helixd-2k18** [comment]
I see DPS beyond than 26, when DP refreshed. But I can't get DPS `27` (hidden, unknown), `28` (forgot), `29` (forgot), `30` (rhythm mode), `31` (forgot), `32` (forgot), even by by `DP_QUERY` requests.

**Comment by codetheweb** [comment]
Closing in favor of the discussion [here](https://github.com/codetheweb/tuyapi/discussions/518).
