### ISSUE TITLE
I dont know where to find "command line" from the last step

### ISSUE THREAD

**Issue by Markobu98** [codetheweb/tuyapi#512]
So I have gotten so far that all my devices are shown up and now I need to enter "tuya-cli wizard" in some command line. However I dont know which command line I should paste this in

**Comment by codetheweb** [comment]
Did you run `npm i @tuyapi/cli -g` yet? If so, just run `tuya-cli wizard` in the same place. If not, it depends on your OS. Terminal for macOS / Linux, Command Prompt for Windows.

**Comment by Markobu98** [comment]
So I got to type "tuya-cli wizard" in to the command line of my OS (I have HASS.OS installed on a rpi39 I have tried typing it into the command line of my pi in home assistant, using ssh&web terminal

**Comment by codetheweb** [comment]
I'm not entirely sure what you're saying. I believe the web terminal you're talking about should work for it.

**Comment by Markobu98** [comment]
I have tried typing it in the command line you can access via the add-on in home assistant. However it said command not found

**Comment by codetheweb** [comment]
Did you run `npm i @tuyapi/cli -g`?

**Comment by Markobu98** [comment]
I did but it said command not found
