### ISSUE TITLE
Tuya local controll where is the best place to get news

### ISSUE THREAD

**Issue by guyluz11** [codetheweb/tuyapi#514]
I am building a Hub to control smart devices and I like to add tuya support, the code is written in dart so I will need to convert it.

We are going for local requests to the devices without the cloud.

Does this package support local control, if so does it use the new tuya official API that I think they released?.

In case it is local but not official where is the best place to check for news moving to the official (if this repo is thinking of moving).

If it is only cloud-based where is the best place to get news of moving to local requests (if thinking of moving)?.

I am overwhelmed with information and tuya repos so I hope asking here ok.

**Comment by codetheweb** [comment]
This package is **only** for local control. Tuya has not released an API for local control, [although they're planning to do so at some point](https://github.com/codetheweb/tuyapi/discussions/501).
