### ISSUE TITLE
Cant scan qr code with Tuya app

### ISSUE THREAD

**Issue by Fornball** [codetheweb/tuyapi#515]
**Describe the bug**
Nothing happens when I try scanning the qr code for the authorization of devices
**To Reproduce**
1. First section from here step 3 "Click "Add App Account" and scan the QR code from your smart phone/tablet app by going to the 'Me' tab in the app, and tapping a QR code / Scan button in the upper right. Your account will now be linked."
https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md
**Expected behavior**
The qr code is supposed to be scanned, instead nothing happens, aka the same response as if I would point the camera at a wall
**Desktop (please complete the following information):**
 - OS: Ubuntu(desktop), Android 11 on phone(tried multiple phones with different android versions)

**Comment by Fornball** [comment]
So, for me it was quite the dumb reason. I had darkreader extension on(an extension for chrome to force websites to render in dark mode) and it messed with the qr code.

**Comment by Mozoloa** [comment]
Holy s**t, I'm laughing so hard right now, this is so stupid and obviously the exact same happened to me, thanks for replying to me, this extension is pretty sneaky sometimes !

**Comment by fglkorgdfgfg** [comment]
> Holy s**t, I'm laughing so hard right now, this is so stupid and obviously the exact same happened to me, thanks for replying to me, this extension is pretty sneaky sometimes !

can you help me I still have the issue

**Comment by Fornball** [comment]
Open a new issue and describe your problem in detail there @fglkorgdfgfg

**Comment by goatiy** [comment]
> So, for me it was quite the dumb reason. I had darkreader extension on(an extension for chrome to force websites to render in dark mode) and it messed with the qr code.

Thank you so so much i tried it hours and hours and it was just the stupid Dark Reader
