### ISSUE TITLE
These DPS values are not received by `get` request. 

### ISSUE THREAD

**Issue by helixd-2k18** [codetheweb/tuyapi#517]
I have two `IoT A61 RGB` and `IoT C1 RGB` bulbs, both from Hiper. I am facing an issue where DPS are not displayed on get data, although they are displayed on refresh. This is DPS from 27 to 32. And another problem is that one status is hidden in debug (this is DPS 27). Another problem is that DPS starts at 20, not 0.

```js
let data = {
  dps: {
    '20': false,
    '21': 'white',
    '22': 103,
    '23': 88,
    '24': '000003e803e8',
    '25': '000e0d0000000000000000c80000',
    '26': 0
    //'27' is problem, it unknown
    // should to be have '28', '29', '30', '31', '32'
  }
}
```

Those hidden DPS... 

- `27` (hidden, unknown),
- `28` (music_data, empty),
- `29` (control_data, empty),
- `30` (rhythm_mode, base64),
- `31` (sleep_mode, base64),
- `32` (wakeup_mode, base64)

**Comment by codetheweb** [comment]
1. > DPS are not displayed on get data, although they are displayed on refresh

	I've seen this before, just seems to be an oddity of some devices.
2. > one status is hidden in debug (this is DPS 27).

	Again, device oddity.

3. > Another problem is that DPS starts at 20, not 0.

	See above. 😛 

I'm not seeing any issues that are specifically TuyAPI-related (if I misinterpreted something, please let me know). Converting this to a discussion for now.
