### ISSUE TITLE
Issue with WebRTC

### ISSUE THREAD

**Issue by Daniele6** [codetheweb/tuyapi#520]
Hello, i'm trying to use WebRTC. Where can i find the device_id of a real device?
I added a virtual device and i wrote his device ID in the webrtc-demo-go file but i have the follow issue:
mqtt.go:31: moto_id not exist in webrtc-configs, body: {"code":1106,"msg":"permission deny","success":false,"t":1633358800243}
mqtt.go:27: allocate motoID fail: moto_id not exist
main.go:42: start mqtt fail: moto_id not exist

Can anybody help me? 
Thank you
![errore](https://user-images.githubusercontent.com/58933904/135875704-076f1d32-2a49-4c1b-8760-73b923cbba04.png)

**Comment by codetheweb** [comment]
I assume you're trying to use https://github.com/tuya/webrtc-demo-go/?

Please open an issue over there instead.
