### ISSUE TITLE
ENOTFOUND Errors

### ISSUE THREAD

**Issue by dugdathug** [codetheweb/tuyapi#54]
So close, at least I feel like it.  My environment is Ubuntu via HyperV on a windows 10.  The VM has access to the same wireless as the power strip I'm attempting to take hostage.    I wish I were smart enough to figure this out by myself.  I do very much appreciate the work you're doing.
My debug is shared on my g-drive here ==> https://docs.google.com/document/d/1mWSme6a7RJfqUNIP__O028pZ5n2UY5srr9-5aUCX9bU/edit?usp=sharing

**Comment by dugdathug** [comment]
This was resolved by placing the broadcasthost ip into the /etc/hosts file.

**Comment by codetheweb** [comment]
Moved issue to https://github.com/TuyaAPI/link/issues/3.

**Comment by codetheweb** [comment]
[Fixed](https://github.com/TuyaAPI/link/issues/3#issuecomment-412565815).  Please update the CLI tool with `npm i @tuyapi/cli@1.1.0 -g`.
