### ISSUE TITLE
ENOTFOUND Error - broadcasthost ip

### ISSUE THREAD

**Issue by joehanes** [codetheweb/tuyapi#55]
**Describe the bug**
I believe I have a similar problem as described in issue #54 
Unfortunately I have no idea which IP adress to put into for 

     broadcasthost ip

**Additional context**
I am not sure if my socket can actually be registered with your API,...
it works fine with the Smart Life ios App.
The machine I use above is a linux Mint machine 

this is my output on the console
xxx@xxx ~ $ tuya-cli link-wizard 
? Make the indicator light on your device flash.
                For most devices, this means holding down the main button.
                Press return when it's blinking. Yes
? What's your WiFi called? XXXXXXX
? What's the password for your WiFi? [hidden]
? How many devices do you want to link? 1
? Do you want to save devices that are successfully linked? Yes
✖ Device(s) failed to be registered!
{ Error: getaddrinfo ENOTFOUND broadcasthost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:50:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'broadcasthost' }

**Comment by codetheweb** [comment]
[Fixed](https://github.com/TuyaAPI/link/issues/3#issuecomment-412565815).  Please update the CLI tool with `npm i @tuyapi/cli@1.1.0 -g` and try again.
