### ISSUE TITLE
Permission deny due to cross-region access

### ISSUE THREAD

**Issue by bphermansson** [codetheweb/tuyapi#550]
I try to use tuya-cli to access devices:

DEBUG=* .npm/bin/tuya-cli wizard

But I get this:
There was an issue fetching that device. Make sure your account is linked and the ID is correct.

In the debug output:
  Error: 1106: permission deny
...
  Error: GET_TOKEN_FAILED 2007, your ip(2.70.69.nnn) cross-region access is not allowed

What to do?

**Comment by codetheweb** [comment]
Your devices are probably registered in a different region (through the app) than what the API supports. 

IIRC there's a way to set your region when signing up, try signing up again with a different region?

**Comment by bphermansson** [comment]
Seems reasonable, my account in the app has place China and I live in Sweden. I'll try to make a new account for the app, guess I have to reconnect all devices...

**Comment by useronym** [comment]
Okay somehow my app got unpaired from the Tuya project. Readded it, made sure I can see my device listed on the website, and now it seems to work. Confusing error message from the API.
Thanks for the great work!

**Comment by jorgnyg** [comment]
Solved this problem by creating a new Smart Life app account in the region "United States of America". Then added the smart device to this account and added the new (USA) account in the "Link Tuya App account" section at Tuya IoT Platform.
Also make sure your region at https://myaccount.tuya.com/account is set to USA. This can be changed without creating a new developer account.

**Comment by prodigy7** [comment]
I followed the instructions, but I have the problem that when I retrieve the device from the command line I always get the `message cross-region access is not allowed`.
I made sure that the app and the project use the same data centre (I am in Germany, so Central Europe is correct). I also tried creating an account smart life in the USA and a developer account in the USA, but without success.

**Comment by Milofow** [comment]
For people like me searching for a solution. For me the solution was changing the endpoint. 

See image below:
<img width="816" alt="Scherm­afbeelding 2022-11-11 om 20 57 10" src="https://user-images.githubusercontent.com/73555911/201422410-7cf484fc-2d39-4550-9d4a-4531e56322ed.png">
