### ISSUE TITLE
Add support the new device - IR + RF Remote controller 

### ISSUE THREAD

**Issue by Bloodiss** [codetheweb/tuyapi#555]
Hello
Could you add support for the new device - IR + RF Remote controller 
https://www.moeshouse.com/collections/smart-remote-control/products/newest-version-wifi-rf-ir-universal-remote-controller-tv-air-conditioning-smart-home-blaster-infrared-rf-appliances

![moes](https://user-images.githubusercontent.com/89671629/146685045-7a88ed43-775d-4dbb-a265-593e24700640.jpg)
{
    name: 'Smart IR Controller',
    id: 'bfXXXXXXXXXXXXXXXi',
    key: '7aXXXXXXXXXXXXXXe',
    subDevices: [
      {
        name: 'Projector',
        id: 'bfb5bXXXXXXXXXXXXXXn',
        cid: '2cXXXXXXXXXXXXXXXX0c'
      },
      {
        name: 'Air conditioner',
        id: 'bf4XXXXXXXXXXXXXXX6sz',
        cid: '15XXXXXXXXXXXXXXXXe7f'
      }

**Comment by codetheweb** [comment]
I think you meant to open an issue here: https://github.com/rospogrigio/localtuya.
