### ISSUE TITLE
Temperatures Reported in Different Units

### ISSUE THREAD

**Issue by enz1ey** [codetheweb/tuyapi#558]
In the Home app, the current temperature of a Tuya device is being reported (correctly, according to my preferences) in degrees Fahrenheit. However, the set temperature is reporting in degrees Celsius.

![IMG_2457](https://user-images.githubusercontent.com/6290727/147779044-9fb00bf5-7051-49fe-b563-44ec4a7c4825.png)

**Comment by kueblc** [comment]
This is the issue tracker for tuyapi, an unofficial nodejs library for handling low level communication with Tuya devices over LAN. You are probably looking for https://github.com/tuya/tuya-homebridge
