### ISSUE TITLE
Devices cannot be linked

### ISSUE THREAD

**Issue by martijndierckx** [codetheweb/tuyapi#559]
I've followed these steps:

1. Setup Dev account
2. Created Cloud project in EU
3. Linked these service APIs: IoT Core, Authorization, Smart Home Scene Linkage
4. Linked my Tuya app account (tried both the Smart Life app and the Tuya Smart app)
5. Ran 'tuya-cli wizard'

But the cli-tool keeps saying: "There was an issue fetching that device. Make sure your account is linked and the ID is correct."

If I check the Devices page on the Tuya dev console, it mentions 0 devices:
<img width="1110" alt="Screenshot 2022-01-01 at 21 38 04" src="https://user-images.githubusercontent.com/3973630/147859772-437e5c9b-b1ad-43e4-b9b3-0422aa3982c5.png">

The lightbulb has been linked correctly to the app. It shows up in the app and I can find the Virtual ID.
So what am I missing?

The light:
Nedis WIFILT10GDST64

**Comment by zMastaa** [comment]
I had this same problem, it seemed to be a Data Center issue with authorization with the Tuya App. Change to **Central Europe Data Center**

**Comment by martijndierckx** [comment]
Changing from West to Central EU fixed the issue! Thanks
