### ISSUE TITLE
looking for a PHP alternative

### ISSUE THREAD

**Issue by vespino** [codetheweb/tuyapi#560]
I have been able to connect to the Cloud API using PHP which works, but I would like to see if it's possible to control my Tuya devices using PHP locally since I'm not familiar with node or python.

**Comment by codetheweb** [comment]
I don't know of any PHP ports of TuyAPI so you'd have to write it from scratch yourself. It's probably much easier to learn a little JS or Python. :)

**Comment by vespino** [comment]
Is it possible to provide me with the required payload for switches and lights so I can look into building an alternative?

**Comment by codetheweb** [comment]
[This is a little outdated but might help you get started](https://github.com/codetheweb/tuyapi/wiki/Communication-Details).

The best way to figure out the protocol is to look at existing source code.

**Comment by vespino** [comment]
Thanks, I will look into that.
