### ISSUE TITLE
Questions related to data log

### ISSUE THREAD

**Issue by BrianSBUS** [codetheweb/tuyapi#561]
Just a question since I saw you guys working on retrieving data from Tuya via the API method, I am currently trying to obtain the data from my third-party temperature sensor and would like to obtain those data logs without using the IoT platform since it can only store up to 7 days of data and I would like to store more of those data for analysis. Is it possible to obtain those data via API unencrypted and can be stored else where?

**Comment by MkMunich** [comment]
I would like the same: getting the device values directly instead of puhing them into the cloud.
If someone has a solution, how to 'read' the values e.g. with an ESP32 would be great!

**Comment by codetheweb** [comment]
Sensors aren't generally continuously connected to WiFi, so this likely isn't possible. You could try intercepting requests from the sensors to Tuya's cloud, but as far as I know that hasn't been tried before.

**Comment by Apollon77** [comment]
I think with the cloud API you can get a MQTT connection to get all updates as well ?! maybe thats a may, WIll experiment around soon
