### ISSUE TITLE
Data is not decrypted

### ISSUE THREAD

**Issue by buiductri** [codetheweb/tuyapi#563]
Hi, I am new with tuyapi. I stumped upon this issue when I don't know how to fix it anymore. After getting the local id and key, detect which local ip it is, and run the example, I got this:
```
Connected to device!
Data from device: i;s
                     i�����`�\�a��q�^�kx��t�LK��
/root/tuya/index.js:33
  console.log(`Boolean status of default property: ${data.dps['1']}.`);
                                                             ^

TypeError: Cannot read property '1' of undefined
    at TuyaDevice.device.on.data (/root/tuya/index.js:33:62)
    at TuyaDevice.emit (events.js:198:13)
    at TuyaDevice._packetHandler (/root/tuya/node_modules/tuyapi/index.js:627:12)
    at packets.forEach.packet (/root/tuya/node_modules/tuyapi/index.js:507:43)
    at Array.forEach (<anonymous>)
    at Socket.client.on.data (/root/tuya/node_modules/tuyapi/index.js:503:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
```

Look like data received is not correctly decrypt. If anyone have solution for this, please let me know. Thanks a lot guys.

**Comment by codetheweb** [comment]
Can you run with the env var DEBUG set to * and post the output? (`DEBUG=* node ...` in *sh).

**Comment by buiductri** [comment]
Sure @codetheweb, here is the output
```
root@ubuntu:~/tuya# DEBUG=* node index.js
  TuyAPI IP and ID are already both resolved. +0ms
  TuyAPI Connecting to 192.168.xxx.xxx... +25ms
  TuyAPI Socket connected. +26ms
Connected to device!
  TuyAPI GET Payload: +10ms
  TuyAPI { gwId: 'ebf04c****************',
  TuyAPI   devId: 'ebf04c****************',
  TuyAPI   t: '1643178660',
  TuyAPI   dpId: [ 4, 5, 6, 18, 19, 20 ],
  TuyAPI   uid: 'ebf04c****************' } +0ms
  TuyAPI GET Payload: +25ms
  TuyAPI { gwId: 'ebf04c****************',
  TuyAPI   devId: 'ebf04c****************',
  TuyAPI   t: '1643178660',
  TuyAPI   dps: {},
  TuyAPI   uid: 'ebf04c****************' } +1ms
  TuyAPI Received data: 000055aa00000001000000120000002c00000001693b730b698ed0faccdb1660d55cc561d6d071c65e8d6b78949174ea4c4bff8bf273fede0000aa55 +16ms
  TuyAPI Parsed: +12ms
  TuyAPI { payload: 'i;s\u000bi�����\u0016`�\\�a��q�^�kx��t�LK��',
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 18,
  TuyAPI   sequenceN: 1 } +1ms
  TuyAPI Received DP_REFRESH empty response packet. +2ms
  TuyAPI Received data: 000055aa000000020000000a0000002c00000001693b730b698ed0faccdb1660d55cc561d6d071c65e8d6b78949174ea4c4bff8bba31245f0000aa55 +2ms
  TuyAPI Parsed: +2ms
  TuyAPI { payload: 'i;s\u000bi�����\u0016`�\\�a��q�^�kx��t�LK��',
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 10,
  TuyAPI   sequenceN: 2 } +0ms
  TuyAPI Received DATA packet +1ms
Data from device: i;s
                     i�����`�\�a��q�^�kx��t�LK��
/root/tuya/index.js:39
  console.log(`Boolean status of default property: ${data.dps['1']}.`);
                                                             ^

TypeError: Cannot read property '1' of undefined
    at TuyaDevice.device.on.data (/root/tuya/index.js:39:62)
    at TuyaDevice.emit (events.js:198:13)
    at TuyaDevice._packetHandler (/root/tuya/node_modules/tuyapi/index.js:627:12)
    at packets.forEach.packet (/root/tuya/node_modules/tuyapi/index.js:507:43)
    at Array.forEach (<anonymous>)
    at Socket.client.on.data (/root/tuya/node_modules/tuyapi/index.js:503:19)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
```

**Comment by codetheweb** [comment]
It's possible your local key changed. Can you try retrieving it again?

You might also want to try setting the protocol version to 3.3.

**Comment by buiductri** [comment]
Thank for the advice @codetheweb. I decided to reset all my devices and do it again from scratch. It works now. There are some steps might differ with the doc. So here are some key notes I gathered during the setup, hope it can help others:
 - I set up my devices via Tuya's "Smart Life" app
 - In the Tuya iot platform (https://us.iot.tuya.com/cloud/), create new project as described in the doc
 - Go into the project and add my Tuya app account:
![image](https://user-images.githubusercontent.com/22960369/152631980-57744429-a8f8-4d72-a48c-d3fada0a1f7f.png)
 - If the dashboard show 0 devices, the region may be incorrect. You can list more Data Center in the project's edit page:
![image](https://user-images.githubusercontent.com/22960369/152632117-b9a941a2-cf57-4f71-90ec-49682e85c59e.png)
 - Then remove above Tuya app account and re-add it
 - If the dashboard show > 0  devices then it's good to move forward
 - Take note of the UID, click on API Explorer on the left panel, or go to https://iot.tuya.com/cloud/explorer
 - List all info of Tuya app account devices by navigate to "Get the user's device list"
![image](https://user-images.githubusercontent.com/22960369/152632346-792a969c-bb36-406c-94e5-32ab8a7677b2.png)
 - Remember to match the project and region with the project
 - The field `id` and `local_key` is input data for `id` and `key` respectively.
 - In my case, explicit set `version` to `3.3` does the trick (thank again @codetheweb)
 - Also input local ip into `ip` field, this field is also important in my case, otherwise it won't connect.
 - The code may look like this
```
const TuyAPI = require('tuyapi');

const device = new TuyAPI({
  id: 'eb29******************',
  key: 'd08e************',
  ip: '192.168.***.***',
  version: '3.3',
  issueRefreshOnConnect: true,
});
```
I'm not sure where it went wrong before. So I list all of my steps here.
