### ISSUE TITLE
Api Key hame some expiration date?

### ISSUE THREAD

**Issue by italoc** [codetheweb/tuyapi#567]
The api key need for work with local Tuya  have some exipation date or is perpetual?

**Comment by codetheweb** [comment]
Can you please be more specific about what API key you're talking about?

The local device key changes when you re-link a device but should otherwise remain stable.

**Comment by italoc** [comment]
I mean local device key….

last question, if I use local Tuya my device never use the Tuya cloud, is correct?

**Comment by codetheweb** [comment]
Your device will still contact cloud services unless you firewall it off. But TuyAPI operates entirely locally.
