### ISSUE TITLE
error while using link-wizard and trying to obtain local-key

### ISSUE THREAD

**Issue by Minichota** [codetheweb/tuyapi#57]
Okay, the issue is something I'm not sure of but its some socket error so I'm pasting the callback

"minichota@Matthew:/mnt/c/Windows/System32$ sudo tuya-cli link-wizard
? Make the indicator light on your device flash.
                For most devices, this means holding down the main button.
                Press return when it's blinking. Yes
? What's your WiFi called? something-.-
? What's the password for your WiFi? [hidden]
? How many devices do you want to link? 1
? Do you want to save devices that are successfully linked? Yes
⠹ Registering devices(s)...events.js:183
      throw er; // Unhandled 'error' event
      ^

Error [ERR_SOCKET_CANNOT_SEND]: Unable to send data
    at Socket.onListenError (dgram.js:362:22)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at _handle.lookup (dgram.js:267:14)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)"
I'm on windows and I'm not sure, I'm using bash to run this, can someone please explain

**Comment by codetheweb** [comment]
Might be related to the [broadcast error](https://github.com/TuyaAPI/link/issues/3#issuecomment-412565815).  Please update the CLI tool with `npm i @tuyapi/cli@1.1.0 -g` and try again.

If it still doesn't work, please post the output of `DEBUG=* sudo tuya-cli link-wizard`.

Also, what's the output of `node -v`?

**Comment by Minichota** [comment]
well, now I'm getting a timeout error, I'm using the same wifi network that I used with my phone and the tuya app, I'm not sure why I'm getting it.

**Comment by codetheweb** [comment]
@Minichota please see my above comment.  I need more details before I can help.

**Comment by Minichota** [comment]
Well, when I used to debugger one, it appeared to work... now my only issue is that I'm using a python version of this api and I'm getting timeout errors when attempting to run it. I think I'm done with this part of the process though

**Comment by codetheweb** [comment]
Ok.  If you're using the Python port, please open future issues at [clach04/python-tuya](https://github.com/clach04/python-tuya).

I'm closing this for now, feel free to reopen it if you need to.

**Comment by codetheweb** [comment]
@Gunnthorian what's your NodeJS version?  It should be >=8.0.0.

Can you please try running `DEBUG=* tuya-cli link-wizard` and then post the output?

**Comment by Gunnthorian** [comment]
@codetheweb my node version is 10.8.0

After running it with the debug the outlet worked (no idea why, I just saw a success message) I will be heading home with more to test and I'll let you know.
