### ISSUE TITLE
No device while pairing with smart life app

### ISSUE THREAD

**Issue by jpreculeau** [codetheweb/tuyapi#570]
Hello,

I'm trying to  determine device key of my devices in order to use it in an octoprint tuya plugin.
I'm using tuyapi for that.

I've made it throught the step 1 to 3 of the how to [](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md#linking-a-tuya-device-with-smart-link)Linking a Tuya device with Smart Link
then I did all the step of the howto [](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md#listing-tuya-devices-from-the-tuya-smart-or-smart-life-apps)Listing Tuya devices from the Tuya Smart or Smart Life apps

And this is the result

pi@octopi:~ $ tuya-cli wizard
? The API key from tuya.com: fvr******* (I've understood that the API Key was in fact the "Access ID/Client ID" of my cloud project)
? The API secret from tuya.com ****** (the Access Secret/Client Secret of my cloud project)
? Provide a 'virtual ID' of a device currently registered in the app: ********** (found inthe details of the device in the smart life app on IOS)
There was an issue fetching that device. Make sure your account is linked and the ID is correct.

And at the end I've found at that in the Link Tuya App Account there is "0" under devices. I wonder what's wrong with the  linking of  my cloud project and the SmartLife app account.

Off course there is Devices in my acount wich are perfectly working.

![Image 5](https://user-images.githubusercontent.com/2980218/155502506-0eaf62d3-e722-4e69-a033-8077e55b3091.png)
![Tuya_Cloud2](https://user-images.githubusercontent.com/2980218/155502508-970391d3-39c2-4410-8937-ce7853a630c7.png)
![Tuya_Cloud3](https://user-images.githubusercontent.com/2980218/155502511-cec40667-cb8f-4e9a-a2fc-f30826e76804.png)

![image](https://user-images.githubusercontent.com/2980218/155500226-28aeff6f-df81-4129-bb79-b6ce47688ca5.png)

**Comment by jpreculeau** [comment]
I've tried to follow the manual method to register a device with the step 4 to 8 and I get this result 👍 
✖ Device(s) failed to be registered!
Error: Timed out waiting for devices to connect.
    at TuyaLinkWizard.linkDevice (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/link/index.js:161:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)

I've triple check all parameters. Tried a very simple ssid/pass with only Aa0...9 as character on my box It's the same result.

**Comment by gcm-explo1t** [comment]
> And at the end I've found at that in the Link Tuya App Account there is "0" under devices. I wonder what's wrong with the linking of my cloud project and the SmartLife app account.

I can confirm I have the same problem.

**Comment by Soleone** [comment]
I have the same problem. Shows 0 devices after connecting via QR code, but I am logged into an app account on mobile and the device is successfully registered there. Just can't import it into the cloud account.

**Comment by craigcurtin-dev** [comment]
And i have the same problem also

Was using this integration last year and worked fine. Received the emails from Tuya saying my account was going to expire and it did appear to do so as My Home Automation system was not receiving valid data from my Heatpump.

My Heatpump is a fairland and uses their own Tuya App which is how i added it last year (although the portal was different then) it no longer appears to work with the Fairland App. 

I will try with the Tuya Smartlife app and report back

**Comment by michelefa1988** [comment]
Same here, an y ideas. work arounds?

**Comment by Apollon77** [comment]
No details, no follow up infos. closing. Please reopen if still relevant and happening with most recent versions.
