### ISSUE TITLE
tuya-cli wizard returns key: undefined

### ISSUE THREAD

**Issue by nospam2k** [codetheweb/tuyapi#576]
**Describe the bug**
Running the tuya-cli wizard is returning key: undefined

**To Reproduce**
Link light with Tuya Smart App.
Checked tuya api info is correct and can see device in tuya.com
Entered api key, secret and virtual ID. Returns name and id correctly but key: undefined

**Expected behavior**
Should have a key.

**Debug Output**
No errors reported

**Screenshots**
N/a

**Desktop (please complete the following information):**
MacOs Monterey
Node 12.22.10

**Additional context**
Nothing else

**Comment by Apollon77** [comment]
Please reopen or recreate when still relevant
