### ISSUE TITLE
Replace deprecated async_get_registry with async_get instead

### ISSUE THREAD

**Issue by joopmartens** [codetheweb/tuyapi#580]
**Describe the bug**
HomeAssistant gives the following message in the log:

Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom component author for localtuya using this method at custom_components/localtuya/__init__.py, line 315: ent_reg = await er.async_get_registry(hass)

**To Reproduce**
Start/restart HA or integration and check log.

**Expected behavior**
Start/restart without HA log messages

Running HA 2022.6.2

**Comment by kueblc** [comment]
Looks like you're looking for [rospogrigio/localtuya](https://github.com/rospogrigio/localtuya). This is the tuyapi library enabling local communication with Tuya devices, not the home assistant component.
