### ISSUE TITLE
Add New Device Support (HUYNDAI P83WF/P84WF)

### ISSUE THREAD

**Issue by KaportsevIA** [codetheweb/tuyapi#589]
Dehumidifier D030 as HUANDAI SAHARA 20 (P83WF/P84WF) recognized as simple switch.

`
{
  "result": {
    "active_time": 1641845113,
    "biz_type": 0,
    "category": "cs",
    "create_time": 1641554697,
    "icon": "smart/icon/ay15105372588696Qo9c/d07e57e4353c13e0eb9d98bcb4b23908.png",
    "id": "bf051b71dbeaf5775efppb",
    "ip": "x.x.x.x",
    "lat": "xx.xxxx",
    "local_key": "xxxxxxx",
    "lon": "xx.xxxx",
    "model": "D030（24小时）",
    "name": "Huyndai SAHARA 20 (P83WF/P84WF)",
    "online": true,
    "owner_id": "47665646",
    "product_id": "r6gik8xajfg0lv1y",
    "product_name": "Dehumidifier-D030 ",
    "status": [
      {
        "code": "switch",
        "value": false
      },
      {
        "code": "dehumidify_set_value",
        "value": 50
      },
      {
        "code": "fan_speed_enum",
        "value": "high"
      },
      {
        "code": "humidity_indoor",
        "value": 77
      },
      {
        "code": "temp_indoor",
        "value": 25
      },
      {
        "code": "sleep",
        "value": false
      },
      {
        "code": "child_lock",
        "value": false
      },
      {
        "code": "fault",
        "value": 0
      }
    ],
    "sub": false,
    "time_zone": "+03:00",
    "uid": "xxxxxxx",
    "update_time": 1649578582,
    "uuid": "xxxxxxx"
  },
  "success": true,
  "t": 1656612857199,
  "tid": "xxxxxxx"
}
`

**Comment by codetheweb** [comment]
I don't think this is related to TuyAPI.
