### ISSUE TITLE
Add New Device Support (YNDX-00010)

### ISSUE THREAD

**Issue by KaportsevIA** [codetheweb/tuyapi#590]
LED Lights YNDX-00010 not recognized.

`
{
  "result": {
    "active_time": 1646930270,
    "biz_type": 0,
    "category": "dj",
    "create_time": 1639759101,
    "icon": "smart/icon/bay1580798841490ypCK/7ffcbee221a1cf5a9970fb9413f21e6f.png",
    "id": "xxxx",
    "ip": "xx.xx.xx.xx",
    "lat": "xx.xxx",
    "local_key": "xxxxxxx",
    "lon": "xx.xxx",
    "model": "Yandex color bulb",
    "name": "Yandex blub 1",
    "online": true,
    "owner_id": "47665646",
    "product_id": "muushnich7dcbbxi",
    "product_name": "Yandex彩色球泡",
    "status": [
      {
        "code": "switch_led",
        "value": true
      },
      {
        "code": "work_mode",
        "value": "white"
      },
      {
        "code": "bright_value_v2",
        "value": 1000
      },
      {
        "code": "temp_value_v2",
        "value": 487
      },
      {
        "code": "colour_data_v2",
        "value": "{\"h\":230,\"s\":1000,\"v\":1000}"
      },
      {
        "code": "scene_data_v2",
        "value": "{\"scene_num\":1,\"scene_units\":[]}"
      },
      {
        "code": "countdown_1",
        "value": 0
      },
      {
        "code": "music_data",
        "value": ""
      },
      {
        "code": "control_data",
        "value": ""
      }
    ],
    "sub": false,
    "time_zone": "+03:00",
    "uid": "xxxxx",
    "update_time": 1646930275,
    "uuid": "xxxxxxx"
  },
  "success": true,
  "t": 1656613265650,
  "tid": "xxxxxxx"
}
`

**Comment by codetheweb** [comment]
I don't think this is related to TuyAPI.
