### ISSUE TITLE
Ledvance devices problem with pairing and key

### ISSUE THREAD

**Issue by devmet34** [codetheweb/tuyapi#591]
Hello,

I ve got a ledvance smart+ plug indoor eu 10A version. It use tuya core services and app components but they removed tuya linking from the app.. Tuyapi time out registering. Tried to link device via tuya iot methods but failed. Port 6668 is open but telnet with putty times out, not sure if its functioning properly. Tuyapower / tinytuya apps can detect the device and get plug id, plug version etc but cant get monitoring data as it's encrypted. At this point we need local key not only for getting monitoring data but also for other things like tuya or 3rd party integrations. 

Here is my question, some older smart life app versions save keys in plaintext xml files so you can get it on a rooted device. Has anyone had any experience with ledvance? Thank you

**Comment by Apollon77** [comment]
Is this still relevant? If yes please recreate with recent details
