### ISSUE TITLE
Cannot authorise IoT core API

### ISSUE THREAD

**Issue by noordo123** [codetheweb/tuyapi#593]
Im trying to subscribe to the IoT core API, but everytime I try to it just pops up with API产品开通失败 (API product activation failed).

**Comment by DavidPHH** [comment]
I had this issue for ages, think the bug was there for months. I randomly decided to try again and I was able to add services. I did nothing differently, or anything special it just started working on its own.
Just replying to notify you it has (maybe) been fixed.

**Comment by christianhorn** [comment]
Maybe it helps someone: if it was something on their side, it seems fixed - I was able to subscribe to the IoT core API in the last days, no issues.

**Comment by Apollon77** [comment]
@codetheweb Can be closed
