### ISSUE TITLE
install failure

### ISSUE THREAD

**Issue by clach04** [codetheweb/tuyapi#6]
C:\tmp>npm install @codetheweb/tuyapi
    npm ERR! code E404
    npm ERR! 404 Not Found: @codetheweb/tuyapi@latest

    npm ERR! A complete log of this run can be found in:
    npm ERR!     ......2017-11-30T02_11_55_438Z-debug.log

where 2017-11-30T02_11_55_438Z-debug.log contains:

    0 info it worked if it ends with ok
    1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
    1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
    1 verbose cli   'install',
    1 verbose cli   '@codetheweb/tuyapi' ]
    2 info using npm@5.5.1
    3 info using node@v8.9.1
    4 verbose npm-session c8ac1559b4c1c76e
    5 silly install loadCurrentTree
    6 silly install readLocalPackageData
    7 http fetch GET 404 https://registry.npmjs.org/@codetheweb%2ftuyapi 339ms
    8 silly fetchPackageMetaData error for @codetheweb/tuyapi@latest 404 Not Found: @codetheweb/tuyapi@latest
    9 verbose stack Error: 404 Not Found: @codetheweb/tuyapi@latest
    9 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
    9 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
    9 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
    9 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
    9 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
    9 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
    9 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
    9 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
    9 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
    9 verbose stack     at runCallback (timers.js:789:20)
    9 verbose stack     at tryOnImmediate (timers.js:751:5)
    9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
    10 verbose cwd C:\tmp
    11 verbose Windows_NT 10.0.14393
    12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "@codetheweb/tuyapi"
    13 verbose node v8.9.1
    14 verbose npm  v5.5.1
    15 error code E404
    16 error 404 Not Found: @codetheweb/tuyapi@latest
    17 verbose exit [ 1, true ]

**Comment by orizzle** [comment]
npm install codetheweb/tuyapi

worked for me (no @)

**Comment by codetheweb** [comment]
Thanks @clach04 for the fix.
