### ISSUE TITLE
[Question] Do requests manually (http)

### ISSUE THREAD

**Issue by Aaroneisele55** [codetheweb/tuyapi#601]
Hello,
I want to integrate my tuya plugs that all work with the tuyapi module into some device that needs urls for http requests.
How can i do this (urls should be like "http://IP:Port/?on=true" so the device can activate them using GET requests)

Is there kind of a template that i can modify to suit my Devices?

Thanks
Aaron

**Comment by Apollon77** [comment]
You need to write a JavaScript program which actually does that ... The library will only help to get status und control the tuya devices. it do not offer an HTTP interface
