### ISSUE TITLE
Zigbee smart plug

### ISSUE THREAD

**Issue by matodi423** [codetheweb/tuyapi#604]
Hi, I just started few weeks ago with homebridge. 
So I just tried to connect a smart plug working with Zigbee working with a zigbee bridge.
The plug was added too homebridge but when I click on the bulb nothing happen. 

My question was. Can I add a smart plug on Zigbee or only Wi-Fi accessories can be added with LAN Tuya ? 

Thanks, sorry for my bad english :)

**Comment by kardoka** [comment]
Hi, you could try to query the Zigbee smart plug DPS by creating a Device object for the Zigbee gateway and passing the `cid` parameter to `Device.get()`, where the `cid` would be the device ID for the smart plug.
