### ISSUE TITLE
Connect to Smart Filament Led LSC Smart Connect. 

### ISSUE THREAD

**Issue by Sztacho** [codetheweb/tuyapi#611]
Hi. I am trying to create a mini panel on a PC with which I can control the lighting in a room. I've tried making an account, linking everything together on https://www.tuya.com/ but have not been able to download the key. I was getting messages about lack of permissions. 

Therefore I come to you with a question, is there a way to connect without this key or another way to get the key?

**Comment by kardoka** [comment]
As far as I know, there used to be a [way to connect to Tuya devices by MITM](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md#deprecated---linking-a-tuya-device-with-mitm), but that is probably not possible anymore.

In general, you need to obtain the local key from [iot.tuya.com](iot.tuya.com). Have you followed [the tutorial](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md) step by step?

**Comment by Sztacho** [comment]
Yes I do. Maybe I will try again.

**Comment by Miniontoby** [comment]
Thanks!

Using the mitm method with an older APK of the LSC Smart Connect app has worked for me!

You don't need the iot platform at all.
