### ISSUE TITLE
Install instructions not working

### ISSUE THREAD

**Issue by hooverds54** [codetheweb/tuyapi#618]
It would seem simple enough but execution of the command

npm i @tuyacli -g   

generates error

npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "@tuyacli": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:

**Comment by hooverds54** [comment]
Yes I feel like a fool.  However that just created a different problem

hooverds@hooverds-MS-7D25:~/Downloads$ `npm i @tuya/cli -g`
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@tuya%2fcli - Not found
npm ERR! 404 
npm ERR! 404  '@tuya/cli@*' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hooverds/.npm/_logs/2023-01-04T19_52_28_408Z-debug-0.log

**Comment by Apollon77** [comment]
Or maybe you read the linked page agsin??

> npm i @tuyapi/cli -g

**Comment by hooverds54** [comment]
thanks for quick response.  i felt like a fool but even after correcting a new issue arises.  i documented in same threadSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Ingo Fischer ***@***.***> Date: 1/4/23  14:47  (GMT-05:00) To: codetheweb/tuyapi ***@***.***> Cc: hooverds54 ***@***.***>, Author ***@***.***> Subject: Re: [codetheweb/tuyapi] Install instructions not working (Issue #618) 
if you refer to https://github.com/TuyaAPI/cli#installation then you missed a slash
