### ISSUE TITLE
Tuya cloud IoT platform not registering Tuya App

### ISSUE THREAD

**Issue by tommmy93** [codetheweb/tuyapi#619]
**Describe the bug**
I cannot link the cloud platform to the app.

I'm trying to link Tuya into homebridge. To do that, I need to set up a Tuya cloud IoT Platform. I follow the YouTube tutorials on this (https://www.youtube.com/watch?v=YH6d-2VJMaU) around the 2 minute mark it demonstrates what I'm trying to do. Link the Tuya development to the app via QR code.

I am on the right data centres and I scan the code on my phone and the second I do, the QR code becomes expired, it takes me to the permissions page (Read/Write/Control) I click accept.
Then nothing happens, there's no Link shown on the Cloud platform, I've searched everywhere - all devices, linked accounts. It literally says 'Already added 0 accounts and linked 0 devices.'

When I try this again, it says that it's already been linked - but still not showing?
I've tried this with 3 projects now, the third project won't let me link the app because I get an error message saying that I can only link the app to 2 projects, and I'll have to delete one of the links - except I can't because it's not there.

UPDATE:
I can search for the account using the drop down, but still doesn't show in the table - last screenshot

**To Reproduce**
follow the YouTube tutorial https://www.youtube.com/watch?v=YH6d-2VJMaU

1. Go to https://we.iot.tuya.com/cloud
2. Click on '....' Cloud > Development > New Project > Smart home > Link Tuya Account
3. See error?

**Expected behavior**
I expect my account to be linked. It to show up in the box and be searchable - just link the tutorial

**Debug Output**

**Screenshots**

<img width="439" alt="Screen Shot 2023-01-10 at 11 34 16" src="https://user-images.githubusercontent.com/72134660/211541567-86aa472b-981a-4a52-86db-e0b54051d4f6.png">

<img width="1141" alt="Screen Shot 2023-01-10 at 11 34 49" src="https://user-images.githubusercontent.com/72134660/211541676-3165d5a1-511c-4638-aad5-15087ae37a06.png">

<img width="740" alt="Screen Shot 2023-01-10 at 11 35 52" src="https://user-images.githubusercontent.com/72134660/211541852-42f5b56f-c6c9-4517-9b07-8710ee6f6bff.png">

![IMG_8907](https://user-images.githubusercontent.com/72134660/211542123-2c6d734a-81a9-4302-b52e-9093b2d3c0c4.PNG)

UPDATE SCREENSHOT
<img width="725" alt="Screen Shot 2023-01-10 at 11 44 16" src="https://user-images.githubusercontent.com/72134660/211543687-644ec4d3-0930-42f4-8616-2935719a6a1e.png">

**Desktop (please complete the following information):**
Doing on a Mac

**Additional context**

**Comment by maximumcollins** [comment]
Seconding this - mine is doing the same thing

**Comment by maximumcollins** [comment]
Ok I figured it out - I was using the Star Projector's app and not the Smart Life app from Tuya, downloaded that app, added my projector manually to it and the adding account process works seamlessly now
