### ISSUE TITLE
Weird encrypted response from tuya bulb ?

### ISSUE THREAD

**Issue by obaldius** [codetheweb/tuyapi#626]
I have two indentic bulbs that have been working flawlessly for a couple of months. Just recently one of them stopped working and looking at their responses I found the following.

![Sin título](https://user-images.githubusercontent.com/61756214/234997787-0cdd3d36-21b8-4790-bc8d-1396d813b163.png)

First response is from the working bulb, second one is the one that isn't working. Is somebody experiencing this issue?

I tried setting the Tuya Protocol Version to 3.3 to no avail.

The second bulb has stopped reacting to any request.

**Comment by kueblc** [comment]
It may have been assigned a new local key when the device updated to 3.3. Have you tried reprovisioning?

**Comment by obaldius** [comment]
> It may have been assigned a new local key when the device updated to 3.3. Have you tried reprovisioning?

May I ask, how can I do that?

**Comment by weromemuero** [comment]
I've removed the device like ten times now with no luck... keys change but I'm getting local keys with special characters that doesn't works, i get the following on the homebridge terminal: 

mhF]f;xT*}n]****, key for Foco Fachada (eb0c78be1146023769xlky), is not a valid key.

Thanks for the help anywways. 

I truly appreciate any suggestions.

**Comment by Apollon77** [comment]
Maybe the homebridge plugin has added checked for allowed characters? Seems more like a message from there then from the library here. Maybe this check need to be adjusted?
