### ISSUE TITLE
Tuya IOT Platform error 1106: permission deny

### ISSUE THREAD

**Issue by rknabben** [codetheweb/tuyapi#632]
I have looked at the instructions over and over again,

I've created an Cloud account,  a project for smart home, Central Europe datacenter (as per https://github.com/tuya/tuya-home-assistant/blob/main/docs/regions_dataCenters.md )

Service Authentication (IoT Core, Authorization Token Mgmt. Smart Home Scene Linkage, Data Dashboard Service) authorization is added.

App was created, and linked under "Link my App"; 

But in the Homey App only error 1106 Permission Deny will pop up.
The API Explorer somewhat works; I can get information about 1 device.
 (I added 1 device to the TUYA SMART app, which was imported by the IoT Platform (Link Tuya App Account) 

I don't have a clue where to look next.

**Comment by amon-ra** [comment]
Same problem here

**Comment by 1ubuntuuser** [comment]
@rknabben Did you find a solution? same issue here.

**Comment by kaohlive** [comment]
did any of you find the cause of this issue? Having the same error in the new official Tuya app off homey :(

**Comment by rknabben** [comment]
Triple check the country. 
I can't remember exactly what I set and what it needed to be, as it is so long ago, but the country code that is set caused the problem at my side, changed it to the correct setting and it worked. 

The official app never asked me for anything, nor did I setup anything, just install and go.
