### ISSUE TITLE
Cannot install with "npm install codetheweb/tuyapi"

### ISSUE THREAD

**Issue by masterofobzene** [codetheweb/tuyapi#633]
All I get is:

C:\Users\SERVER>npm install codetheweb/tuyapi
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by Apollon77** [comment]
Yes this way you install from GitHub and need to have git as executable installed which do not seem to be there. Download and install git - or install thepackage from npm.
