### ISSUE TITLE
302 status on my TuyaPlatform plugin

### ISSUE THREAD

**Issue by rmkromkamp** [codetheweb/tuyapi#638]
I've added the TuyaPlatform plugin and inserted all the necessary information but I get an error message when rebooting the Raspberry Pi

[TuyaPlatform] [TuyaOpenAPI] Status: 302 Found

All Tuya devices do not show up on homekit. They all do work within the Tuya Smart app

**Comment by kueblc** [comment]
This issue tracker is for tuyapi, an unofficial JS library for controlling Tuya devices over LAN.

Maybe you were looking for [homebridge-tuya-platform](https://github.com/0x5e/homebridge-tuya-platform)?
