### ISSUE TITLE
Just lost all my Local Tuya devices

### ISSUE THREAD

**Issue by tomd-tc** [codetheweb/tuyapi#646]
**Describe the bug**
After refreshing the account, I lost all my devices.

**To Reproduce**
1. Go to Settings > Devices & Services > LocalTuya
2. Click on Configure > Reconfigure Cloud API account > Submit > change nothing > click Submit
3. See error: "No devices or entities"

**Expected behavior**
Additional devices if applicable, but definitely not an empty list.
```

```

**Screenshots**

**Desktop (please complete the following information):**
Core 2024.1.6
Supervisor 2024.03.0
Operating System 12.1
Frontend 20240104.0

**Comment by Apollon77** [comment]
LocalTuya !== TuyaPI ... wrong repo
