### ISSUE TITLE
How can I remove saved key / secret key

### ISSUE THREAD

**Issue by stephenmhall** [codetheweb/tuyapi#66]
The first time I tried the link-wizard I said yes remember key, however it did not work with the same results as the other open failed to register issue. I was not sure if I had added the correct secret key so wish to try again. How do I un-save the keys?

**Comment by codetheweb** [comment]
```
> tuya-cli link-wizard --help

  Usage: link-wizard [options]

  interactively link a new device (recommended for new users)

  Options:

    --overwrite  show prompts for API credentials, even if some are already saved
    -h, --help   output usage information
```

Use the `--overwrite` flag.  Your resulting command would be `tuya-cli link-wizard --overwrite`.
