### ISSUE TITLE
API not subscribed : Get infrared remotes failed.

### ISSUE THREAD

**Issue by DieBreuers** [codetheweb/tuyapi#665]
Hey i get the message in my Homebridge log:
[9/24/2024, 10:24:53 PM] [Tuya] [TuyaOpenAPI] 
API not subscribed. Please go to "Tuya IoT Platform -> Cloud -> Development -> Project -> Service API",
and Authorize the following APIs before using:
- Authorization Token Management
- Device Status Notification
- IoT Core
- Industry Project Client Service (for "Custom" project)

[9/24/2024, 10:24:53 PM] [Tuya] [TuyaDeviceManager] Get infrared remotes failed. deviceId = NaN, code = 28841101, msg = No permissions. This API is not subscribed.

At the IOT Platform all the APIs are authorized. 
The other devices work really well. Only this one doesn't want to work. 
A Screenshot of the IOT side:
<img width="1978" alt="Bildschirmfoto 2024-09-24 um 22 57 05" src="https://github.com/user-attachments/assets/a0cb39ab-b874-4a82-a2fc-6ffea7703ecf">

Iam running: 
Homebridge v1.8.4 (HAP v0.12.2) node v20.17.0

Tuya @0x5e/homebridge-tuya-platform v1.7.0-beta.54

Thanks

**Comment by Apollon77** [comment]
For which functionality this is? This library is about local Tuya connections, not cloud!

**Comment by DieBreuers** [comment]
I Try to use some IR devices. 
Directly in SmartLife everything works well. 
But Ill try to get them into HomeKit via Homebridge. 
And the Log File in Homebridge gives me this information. 
Okay as you say I have given the permissions for the local connections. 
Where can i give the permission for Cloud?

**Comment by Apollon77** [comment]
Please ask in the homebridge project
