### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by human211** [codetheweb/tuyapi#674]
**Describe the bug**
I have a key holder device (Bluetooth) which is connected to the Internet via a Bluetooth gateway.
I have access to it via the Internet using an SMART LIFE.
I decided to set up notifications about opening the key holder in Telegram with Tuyapi. But for some reason I can't set up access to the device (by id, key and ip):
```
const device = new TuyAPI({
  id: '****',
  key: '***,
  ip: '94.25.***.***',
  version: '3.3',
  issueRefreshOnConnect: true,
});

// Find device on network
device.find().then(() => {
  // Connect to device
  device.connect();
});
```
But get error
```
Error: connection timed out
    at Socket.<anonymous> (D:\test\backend\node_modules\tuyapi\index.js:597:26)
```
What am I doing wrong? Maybe Tuyapi only works on a local network or without gateways?

**Comment by Apollon77** [comment]
Can you ping the IP from the hist where tuyapi runs on? is the smartlife app closed?

**Comment by human211** [comment]
where the Tuyapi works the device does not ping... yes, it seems that this is the problem. thanks!
By the way, how does the smart life connect to the device if it does not ping? Or the device itself periodically sends requests?

**Comment by Apollon77** [comment]
When smart life can not connect to the device it uses the cloud data.
And btw: battery powered devices are usually not online on IP level. There you only have cloud
