### ISSUE TITLE
Migrating from NodeJS to other language

### ISSUE THREAD

**Issue by grosjo** [codetheweb/tuyapi#677]
Hi

I am trying to control my Tuya devices from an OpenWrt box (linux, but nodejs is not available on non-FPU devices, only other languages like php or perl or python or else)

General questions : 
- Have you found a doc somewhere of the protocol to access the device on port 6668 ? 
- How to actually connect to the device without Internet ? (we have wifi all over, but internet is really unstable here)
- Can give me some pointer in your code, in order to be able to use it in another language to achieve my goal ?

Thank you so much

**Comment by Apollon77** [comment]
HI @grosjo Hm ... Yes documentation is rare, so most is "code from reverse engineered information". I think the easiest way to understand the logic is to start with the index.js here ... run it and use debug log to see what happens internally. SO you can also follow code flows and get an understanding. And then you know what you need to rewrite in an other language.

**Comment by grosjo** [comment]
Found tinytuya in Python, @jasonacox , great job
