### ISSUE TITLE
Get works but set doesn't

### ISSUE THREAD

**Issue by ckdarby** [codetheweb/tuyapi#70]
**Describe the bug**
Unable to use tuya.set()

**To Reproduce**
```
const TuyaDevice = require('tuyapi');

let tuya = new TuyaDevice({
  id: '012005726001946e7f40',
  key: 'xxxxxxxxxxxxxxxx',
  ip: '192.168.0.3'});

tuya.get().then(status => {
  console.log('Status:', status);

  tuya.set({set: !status}).then(result => {
    console.log('Result of setting status to ' + !status + ': ' + result);

    tuya.get().then(status => {
      console.log('New status:', status);
      return;
    });
  });
});
```

**Expected behavior**
Expect the lights to go off?

**Debug Output**

```
  TuyAPI Device:  +0ms
  TuyAPI { id: '012005726001946e7f40',
  TuyAPI   key: 'xxxxxxxxxxxxxxxx',
  TuyAPI   ip: '192.168.0.3',
  TuyAPI   port: 6668,
  TuyAPI   version: 3.1,
  TuyAPI   cipher:
  TuyAPI    TuyaCipher {
  TuyAPI      cipher:
  TuyAPI       { algorithm: [Object],
  TuyAPI         mode: [Object],
  TuyAPI         blockSize: 16,
  TuyAPI         _finish: false,
  TuyAPI         _input: null,
  TuyAPI         output: null,
  TuyAPI         _op: [Function],
  TuyAPI         _decrypt: false },
  TuyAPI      decipher:
  TuyAPI       { algorithm: [Object],
  TuyAPI         mode: [Object],
  TuyAPI         blockSize: 16,
  TuyAPI         _finish: false,
  TuyAPI         _input: null,
  TuyAPI         output: null,
  TuyAPI         _op: [Function],
  TuyAPI         _decrypt: true },
  TuyAPI      version: 3.1 } } +1ms
  TuyAPI Payload:  { gwId: '012005726001946e7f40', devId: '012005726001946e7f40' } +2ms
  TuyAPI Socket attempt 1 +2ms
  TuyAPI Sending this data:  000055aa000000000000000a000000467b2267774964223a223031323030353732363030313934366537663430222c226465764964223a223031323030353732363030313934366537663430227d000000000000aa55 +0ms
  TuyAPI Socket connected. +7ms
  TuyAPI Received data back: +21ms
  TuyAPI 000055aa000000000000000a00000114000000007b226465764964223a223031323030353732363030313934366537663430222c22647073223a7b2231223a747275652c2232223a227768697465222c2233223a3235352c2234223a3235352c2235223a226666303030303030303066666666222c2236223a223030666630303030303030303030222c2237223a226666666635303031303066663030222c2238223a226666666638303033666630303030303066663030303030306666303030303030303030303030303030303030222c2239223a226666666635303031666630303030222c223130223a226666666630353035666630303030303066663030666666663030666630306666303030306666303030303030227d7de27ffec00000aa55 +0ms
Status: true
  TuyAPI Payload: +2ms
  TuyAPI { devId: '012005726001946e7f40',
  TuyAPI   uid: '',
  TuyAPI   t: '1534822576',
  TuyAPI   dps: { '1': false } } +0ms
  TuyAPI Socket attempt 1 +2ms
  TuyAPI Sending this data:  000055aa000000000000000700000087332e316532626163616135653561633834616546476b39646c4379644c4372414a524b736e4634664851646a4138624e33724973577443384d5346547974637648666d4f693557676c47794d6837675562616447522f77712b2b324e6b62336f3577505955312f4d4d685151564551797462737a6e356a5a6156374f6e513d000000000000aa55 +0ms
  TuyAPI Socket connected. +23ms
  TuyAPI Socket attempt 2 +6s
  TuyAPI Sending this data:  000055aa000000000000000700000087332e316532626163616135653561633834616546476b39646c4379644c4372414a524b736e4634664851646a4138624e33724973577443384d5346547974637648666d4f693557676c47794d6837675562616447522f77712b2b324e6b62336f3577505955312f4d4d685151564551797462737a6e356a5a6156374f6e513d000000000000aa55 +0ms
```

**Desktop (please complete the following information):**
 - OS: Linux
 - OS Version Ubuntu 16.04 
 - Node Version v10.8.0

**Comment by codetheweb** [comment]
`get()` works but `set()` fails if the key parameter is incorrect.  Can you please try setting up your device again to regenerate the key?

**Comment by ckdarby** [comment]
@codetheweb Are there instructions on generating the key?

I tried using `tuya-cli link-wizard` but nothing would pair with it when my lights were blinking.

**Comment by codetheweb** [comment]
Other users have also reported issues with the link wizard, and I'm trying to track down the bug (although it works flawlessly for me).

You can view the old setup instructions [here](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP_DEPRECATED.md).

**Comment by ckdarby** [comment]
Just for reference sake for anyone else who stumbles across this, the lighs I have an issue using the wizard with is: LUMIMAN LM530

**Comment by ckdarby** [comment]
@codetheweb Have not attempted yet looked like a bunch of work but I have at least installed the Android app to capture packets.

**Comment by ckdarby** [comment]
@codetheweb Did not work. Got some pcap but nothing that looked usable with a key or keyId, etc.

**Comment by uDude** [comment]
@ckdarby , late response.  Just connect to the device using the Tuuapi and use your alexa/phone app/whatever to set parameters.  See what dps values change and set those sequentially.

**Comment by ankurp** [comment]
Any update on this. I am also having issues with Merkury bulbs and plugs which I cannot set via this API. The set method times out.

**Comment by codetheweb** [comment]
@ankurp does `get()` work?  Can you please provide a link to where you bought your device?

**Comment by codetheweb** [comment]
@ankurp do you mean that drumfreak's plugin works as expected for your bulbs, or are you pointing out that they implemented color controls?

If it's the first, then you're probably setting the wrong property on your device.  Try starting Homebridge with `DEBUG=* homebridge` to see what properties drumfreak's plugin is changing.

**Comment by christophermh44** [comment]
Hi,

I am discovering your library since a few days and I am getting lost with the way I have to use to communicate with my light bulbs.

I have a similar problem than described here: I can get data but I cannot set them. 

I got the keys by reading the logs from my smartphone ("adb shell" and "logcat" while navigating in Tuya Smart app). But it seems that the keys are not correct (maybe I use the bad value?) 

So, the more I read this topic, the more I think that I have not the good key to change values on my light bulbs. Here is my question: how can I get the real generated key by Tuya?

As far as I understand, those keys are generated when the devices are linked to an application. I tried to create one on Tuya's website to use the app key and secret with tuya-link but they are valid for only 1 month (or I have to pay 1500$ to publish a smartphone app that I will not use!)

Thanks for your help :)

**Comment by codetheweb** [comment]
@christophermh44 did you try the method given [here](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md) to obtain the key pairs?

**Comment by christophermh44** [comment]
> @christophermh44 did you try the method given [here](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md) to obtain the key pairs?

Yes, but I got errors while trying to get ids.

By the way, I finally succeed to get my device ids by looking into files inside /data/data/com.tuya.smartlife/shared_prefs/*.xml

**Comment by codetheweb** [comment]
Glad you got it working @christophermh44.

Closing this as the common problem appears to be an incorrect key parameter.
