### ISSUE TITLE
after using new app of tuya developer portel, I am unable to register the device, illegal client id

### ISSUE THREAD

**Issue by amitn16** [codetheweb/tuyapi#71]
root@openhab:/etc/openhab2/scripts/njsTuya/scripts# tuya-cli link-wizard
? Make the indicator light on your device flash.
                For most devices, this means holding down the main button.
                Press return when it's blinking. Yes
? What's your WiFi called? NETGEAR05
? What's the password for your WiFi? [hidden]
? How many devices do you want to link? 1
? Do you want to save devices that are successfully linked? Yes
✖ Device(s) failed to be registered!
{ code: 'ILLEGAL_CLIENT_ID', message: 'Illegal clientId' }

**Comment by amitn16** [comment]
Thanks.. I am able to reset key details.. but it is giving below error. please guide
`` ? Do you want to save devices that are successfully linked? Yes
✖ Device(s) failed to be registered!
{ Error: getaddrinfo ENOTFOUND broadcasthost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'broadcasthost' }
``

**Comment by codetheweb** [comment]
Looks like you're using an older version of `tuya-cli`, update with `npm i @tuyapi/cli@1.2.0 -g`.

**Comment by amitn16** [comment]
Hi,
Yes.. I am having 2 plugs  (1 normal and another with extra RGB light). both are able to control, but the plug which is having extra RGB light..actually i am able to toggle only RGB light switch off/on not plug.

but my main problem is I am not able to integrate with Openhab. can you help in it.

**Comment by codetheweb** [comment]
Glad to hear you got the setup process working.

I think there's a few people that have been developing an OpenHab plugin based off `tuyapi`, but I'm not sure how far along they are.  Try searching for `openhab tuya bulb` and see what comes up.

Also tagging @unparagoned as I think they did some OpenHab development.
