### ISSUE TITLE
Tuya Water Sensor

### ISSUE THREAD

**Issue by yoavw** [codetheweb/tuyapi#77]
I got a Tuya switch and a Tuya water sensor.  The switch works fine with the API so I know the API works with linked devices.  The water sensor is more challenging.

The sensor stays offline, and only comes online every once in a while to report status, or immediately when it senses water.  It only stays online for ~2 seconds (then goes off the wifi network again).  During those times, I try to poll its status using the API with the correct devId, gwId, key.  I consistently get "json obj data unvalid" instead of a "dps" containing the sensor status as I would expect.

I tried to scan for more commands, aside from 0xa (status).  It only responds to 0x2 and 0x9, both of which return a fixed value regardless of the sensor, so the status probably has to be read with 0xa like other Tuya devices.

Anyone else ran across Tuya devices returning "json obj data unvalid" instead of valid json status?

**Comment by codetheweb** [comment]
I'm sorry, but since I don't have that device I probably won't be able to help much.

It sounds like it uses a fundamentally different flavor of firmware, as all the devices I've seen so far stay permanently connected to a network.  What's the interface in the offical app like?  Are you able to tell if it sends something like a wake-up packet over UDP?

You could try getting the sensor's status with Tuya's [cloud API](https://github.com/TuyaAPI/cloud) as well.

**Comment by Apollon77** [comment]
@yoavw can you enable debug to get the exact message details? Then it should be easier to exactly see what happened there

**Comment by Apollon77** [comment]
I also digged a bit into these "come online on event" devices ... It seems that are NOT send info UDP info on 6666 out once online. It seems they only connect to tuya cloud, send their status and then go offline again :-(

This would mean we need to reverse engineer the app (again) to see how the app gets that.Maybe MQTT or such?

Anyone have an info?

**Comment by uspass** [comment]
I have one of those tuya water leak sensor.
I have drawn the schematics and made some comments on.
It has, beside 8266, a second processor that actually deals with IO.
All info so far is here:
https://github.com/uspass/Tuya-Water-Leak-Sensor
On the other hand, I'm stuck as i have no clue what the serial TxRx protocol between ESP and EFM might be.
I have disassembled the code and try to figure it out, but it's a long shot.
Any info is welcome.

Thanks,
us

**Comment by codetheweb** [comment]
@uspass that's some really cool work, good job.

Unfortunately, disassembling code is outside of my skillset and I can't really provide any more information.  I believe @experimint may have a similar sensor type, you may want to reach out to them.

**Comment by uspass** [comment]
@codetheweb 
Thank you for the info.

**Comment by experimint** [comment]
I could send a sensor out to you @uspass 
Send me an e-mail at sander@experimint.nl and we'll take it from there.

**Comment by codetheweb** [comment]
Closing this because it's outside of the scope of this project.

Feel free to keep using it as a discussion thread if you want.
