### ISSUE TITLE
Received an email from Tuya 

### ISSUE THREAD

**Issue by NorthernMan54** [codetheweb/tuyapi#78]
Everyone I received this email today from Tuya as a result of signing up.  I wrote them a nice email back and asked about getting acces to the local api documentation and publishing of api keys in a open source project.  If I hear back, I will share.

Dear，
 
This is Bella from Tuya Smart,Nice to meet you.
 
Noted that you have registered Tuya IOT Platform,do you mind taking a while to answer some questions as below:
1) Are you private developer or enterprise user?
2) Where do you get the info of Tuya IOT Platform?
3) Are there any suggestion on improvement of Tuya IOT Platform?
4) Do you have any project on Smart Product development?
5) Have you used Tuya Service before? Can you share with us the feedback？
6）If yes,what product?
 
FYI,below is short introduction of Tuya Smart:
Tuya Smart is a global IoT platform and the largest voice AI interactive platform in the world，that enables products smarter for consumers, brands, OEM manufacturers and retail chains. It provides users with a one-stop AI IoT solution that covers hardware access, cloud services and APP software development, forming a service closed-loop of AI + manufacturing.
 
Thanks for your support.
 
Regards
BELLA
cid:8ABD8141@4D3CE576.5C8C135A
楼玲佳  |  Bella
平台运营部  |  Platform Operation Dep.
Tel: 86 400 881 8611  |  Cell: 86 150 8864 8589  | Email:loulj@tuya.com
Tuya Inc.  |  tuya.com  |  在微信上关注我们                  
旧金山  |  杭州  |  深圳  |  San Francisco  |  Hangzhou  |  Shenzhen

**Comment by codetheweb** [comment]
Thanks for sharing.  If we could get access to higher-quality documentation that would be great.

**Comment by NorthernMan54** [comment]
Closing until I hear anymore
