### ISSUE TITLE
illegal client 

### ISSUE THREAD

**Issue by lohasleduser** [codetheweb/tuyapi#85]
I was not able to connect my LOHAS led bulbs so I created a new app but had selected for the wizard to save my old keys how do I change them to the new keys

Device(s) failed to be registered!
{ code: 'ILLEGAL_CLIENT_ID', message: 'Illegal clientId' }

**Comment by codetheweb** [comment]
```bash
➜ tuya-cli link-wizard --help
Usage: link-wizard [options]

interactively link a new device (recommended for new users)

Options:

  --overwrite  show prompts for API credentials, even if some are already saved
  -h, --help   output usage information

➜
```

Use the `overwrite` flag like so: `tuya-cli link-wizard --overwrite`.

You could also pass in the parameters directly with `tuya-cli link --help`.
