### ISSUE TITLE
New to this, are there limits on this API?

### ISSUE THREAD

**Issue by pcanella** [codetheweb/tuyapi#86]
I see that this finds the device on your wifi network and allows you to connect to it, update it, etc. However, I'm curious if this repo/npm package pings Tuya in some way, or does it just ping your smart device directly? I just wasn't sure how involved Tuya is after you get the app token and secret. 

GREAT idea btw!

**Comment by codetheweb** [comment]
The device pings Tuya with its current status at a certain interval.  And it's neccessary to contact Tuya to get the key pair during the setup process.  Other than that, all interaction with the device is currently done locally.

**Comment by pcanella** [comment]
PERFECT! Thank you so much for the quick response!
