### ISSUE TITLE
Tuya platform no longer seems to allow free app creation to retrieve API?

### ISSUE THREAD

**Issue by eddeandres** [codetheweb/tuyapi#90]
I created a Tuya account but after clicking to create an app I'm now presented with a buy now option for $1499 with no other option to continue.

**Comment by codetheweb** [comment]
That's unfortunate 😞.  I tagged you in a response over in #65.

**Comment by Apollon77** [comment]
Hm ... since yesterday I have problems reaching iot.tuya.com at all ... it seems thay changed something :-(
