### ISSUE TITLE
Move to a proxy-based system for aquiring local keys

### ISSUE THREAD

**Issue by codetheweb** [codetheweb/tuyapi#91]
Viable option: [anyproxy](https://www.npmjs.com/package/anyproxy).

Details:
- Be CLI based like current setup process
- Need to be able to print QR code in console for link to certificate setup for SSL sniffing

**Comment by Apollon77** [comment]
The qr thing will be tricky ... or better: we need to do by our self. Using the anyproxy web interface link is no option?

**Comment by codetheweb** [comment]
I would rather have it be self-contained in the terminal (so no web interface).

Was looking at something like [this](https://www.npmjs.com/package/qrcode-terminal).

**Comment by codetheweb** [comment]
Finished.

https://github.com/codetheweb/tuyapi/issues/65#issuecomment-431626504

**Comment by codetheweb** [comment]
You can try it, but from what I've read custom root certificates have to be trusted on an app by app basis.

**Comment by Apollon77** [comment]
I have no Android :-) ANd yes on the Charles Proxy page it is harder with Android ... 

I just saw

http://anyproxy.io/en/#trust-root-ca-in-android

**Comment by Apollon77** [comment]
I have no Android :-) ANd yes on the Charles Proxy page it is harder with Android ... 

I just saw

http://anyproxy.io/en/#trust-root-ca-in-android

And one user tested with Android 5 and 8 ... And here is also one better info:

https://support.google.com/nexus/answer/2844832?hl=en
