### ISSUE TITLE
Command Slow

### ISSUE THREAD

**Issue by thib5** [codetheweb/tuyapi#94]
I'm using this to send command thought command line : 
https://github.com/unparagoned/njsTuya
but it take up to 10 second to trigger the command...
it gave me this warning I don't know if it's related : resolveIds() is deprecated since v3.0.0. Will be removed in v4.0.0. Use resolveId() instead.

Thanks

**Comment by codetheweb** [comment]
I don't think njsTuya is still maintained.  I would recommend using the [`tuya-cli`](https://www.npmjs.com/package/@tuyapi/cli) tool instead.

In the future, please open issues related to njsTuya in the njsTuya repo instead of this one.
